// Level 6 texts (master level - 최고급)
// Native speaker level: literature, scientific articles, philosophy, specialized topics
// Grammar: -(으)ㄴ/는 한, -거니와, -(으)ㄹ진대, -노라면, -(으)ㄹ뿐더러, -는 바이다

const level6Texts = {
    personal: [
        {
            id: 'personal-1',
            title: "Philosophy of Life's Journey",
            subtitle: "삶의 철학적 여정",
            korean: `<p><span class="korean-word" data-translation="looking back on the years lived" data-pronunciation="살아온 세월을 돌아보노라면 [saraon seworeul dorabonorамyeon]">살아온 세월을 돌아보노라면</span> <span class="korean-word" data-translation="despite numerous hardships" data-pronunciation="숱한 고난에도 불구하고 [sutan gonane-do bulguhago]">숱한 고난에도 불구하고</span> <span class="korean-word" data-translation="every moment" data-pronunciation="매 순간이 [mae sungani]">매 순간이</span> <span class="korean-word" data-translation="held meaning" data-pronunciation="의미를 품고 있었음을 [uimireul pumgo isseosseumeul]">의미를 품고 있었음을</span> <span class="korean-word" data-translation="I realize" data-pronunciation="깨닫게 됩니다 [kkaedatke doemnida]">깨닫게 됩니다</span>.</p>
<p><span class="korean-word" data-translation="in youth" data-pronunciation="젊은 시절에는 [jeolmeun sijeoreneun]">젊은 시절에는</span> <span class="korean-word" data-translation="achieving success" data-pronunciation="성공을 이루는 것이야말로 [seonggongeul iruneun geosiyamallo]">성공을 이루는 것이야말로</span> <span class="korean-word" data-translation="the purpose of life" data-pronunciation="삶의 목적이라 [sarеui mokjeokirа]">삶의 목적이라</span> <span class="korean-word" data-translation="I mistakenly believed, however" data-pronunciation="착각했거니와 [chakgakhaetgeoniwa]">착각했거니와</span> <span class="korean-word" data-translation="with the passage of time" data-pronunciation="세월이 흐르면서 [sewori heureumyeonseo]">세월이 흐르면서</span> <span class="korean-word" data-translation="relationships with people" data-pronunciation="사람들과의 관계가 [saramdeulgwaui gwangyega]">사람들과의 관계가</span> <span class="korean-word" data-translation="are more precious" data-pronunciation="더욱 소중하다는 것을 [deouk sojunghadaneun geoseul]">더욱 소중하다는 것을</span> <span class="korean-word" data-translation="I came to realize" data-pronunciation="알게 되었습니다 [alge doeeotseumnida]">알게 되었습니다</span>.</p>
<p><span class="korean-word" data-translation="as long as a person is alive" data-pronunciation="인간이 살아 있는 한 [ingani sara inneun han]">인간이 살아 있는 한</span> <span class="korean-word" data-translation="not only suffers" data-pronunciation="고통을 겪을뿐더러 [gotongeul gyeokeulppundeoreo]">고통을 겪을뿐더러</span> <span class="korean-word" data-translation="but also joy" data-pronunciation="기쁨도 [gippeumdo]">기쁨도</span> <span class="korean-word" data-translation="can experience" data-pronunciation="느낄 수 있는 바이니 [neukkilsu inneun baini]">느낄 수 있는 바이니</span> <span class="korean-word" data-translation="this is precisely" data-pronunciation="이것이야말로 [igеosiyamallo]">이것이야말로</span> <span class="korean-word" data-translation="the essence of human existence" data-pronunciation="인생의 본질이라 [insaengui bonjirira]">인생의 본질이라</span> <span class="korean-word" data-translation="I believe" data-pronunciation="생각합니다 [saenggakhamnida]">생각합니다</span>.</p>
<p><span class="korean-word" data-translation="if one thinks about the future" data-pronunciation="앞날을 생각할진대 [apnareul saenggakhalchindae]">앞날을 생각할진대</span> <span class="korean-word" data-translation="accumulated experience" data-pronunciation="쌓아온 경험을 [ssaaon gyeongheomeul]">쌓아온 경험을</span> <span class="korean-word" data-translation="to the next generation" data-pronunciation="다음 세대에 [daeum sedae-e]">다음 세대에</span> <span class="korean-word" data-translation="to pass on" data-pronunciation="전하는 것이 [jeonhaneun geosi]">전하는 것이</span> <span class="korean-word" data-translation="my duty" data-pronunciation="제 소임이라 [je soimira]">제 소임이라</span> <span class="korean-word" data-translation="I believe" data-pronunciation="여깁니다 [yeogipnida]">여깁니다</span>.</p>`,
            translation: "Looking back on the years lived, I realize that despite numerous hardships, every moment held meaning. In my youth, I mistakenly believed that achieving success was the purpose of life, but with time I came to realize that relationships with people are far more precious. As long as a person is alive, they experience not only suffering but also joy — this is the very essence of human existence. Thinking about the future, I consider it my duty to pass on accumulated experience to the next generation.",
            image: "",
            quiz: [
                { question: "젊은 시절 무엇이 삶의 목적이라 생각했습니까? (Что считал целью жизни в молодости?)", options: ["인간관계", "성공", "건강", "학문"], correct: 1 },
                { question: "세월이 흐르며 무엇이 더 소중하다는 것을 알았습니까? (Что понял со временем?)", options: ["재산", "명예", "사람들과의 관계", "권력"], correct: 2 },
                { question: "인생의 본질은 무엇이라 했습니까? (Что есть сущность жизни?)", options: ["고통만 있다", "기쁨만 있다", "고통과 기쁨을 느끼는 것", "성공하는 것"], correct: 2 },
                { question: "앞날에 대한 소임은 무엇입니까? (Каков долг перед будущим?)", options: ["부를 축적하는 것", "경험을 다음 세대에 전하는 것", "은퇴하는 것", "여행하는 것"], correct: 1 }
            ]
        },
        {
            id: 'personal-2',
            title: "Reflections on the Meaning of Labor",
            subtitle: "노동의 의미에 관한 성찰",
            korean: `<p><span class="korean-word" data-translation="in modern society" data-pronunciation="현대 사회에서 [hyeondae sahoeseo]">현대 사회에서</span> <span class="korean-word" data-translation="labor" data-pronunciation="노동은 [nodongeun]">노동은</span> <span class="korean-word" data-translation="not only a means of livelihood" data-pronunciation="생계 수단일뿐더러 [saenggye sudanilppundeoreo]">생계 수단일뿐더러</span> <span class="korean-word" data-translation="a way of self-realization" data-pronunciation="자아실현의 방편이기도 합니다 [jaаsilhyeonui bangpyeonigido hamnida]">자아실현의 방편이기도 합니다</span>.</p>
<p><span class="korean-word" data-translation="whatever work one does" data-pronunciation="어떤 일을 하든 [eotteon ireul hadeun]">어떤 일을 하든</span> <span class="korean-word" data-translation="as long as self-respect is maintained" data-pronunciation="자존감을 지키는 한 [jajongameul jikineun han]">자존감을 지키는 한</span> <span class="korean-word" data-translation="that work" data-pronunciation="그 일은 [geu ireun]">그 일은</span> <span class="korean-word" data-translation="is worthy of respect" data-pronunciation="존엄한 것이거니와 [joneomhan geosigеoniwa]">존엄한 것이거니와</span> <span class="korean-word" data-translation="the contribution to society" data-pronunciation="사회에 기여하는 바도 [sahoee giyеohaneun bado]">사회에 기여하는 바도</span> <span class="korean-word" data-translation="is great" data-pronunciation="크다 하겠습니다 [keuda hagetseumnida]">크다 하겠습니다</span>.</p>
<p><span class="korean-word" data-translation="if one reflects on work ethics" data-pronunciation="직업 윤리를 생각할진대 [jigeop yullireul saenggakhalchindae]">직업 윤리를 생각할진대</span> <span class="korean-word" data-translation="honesty and responsibility" data-pronunciation="정직함과 책임감이야말로 [jeongjikamgwa chaekimgamiyamallo]">정직함과 책임감이야말로</span> <span class="korean-word" data-translation="the foundation of professionalism" data-pronunciation="전문성의 근간이라 [jeonmunsеongui geunganira]">전문성의 근간이라</span> <span class="korean-word" data-translation="one can assert" data-pronunciation="할 수 있는 바입니다 [hal su inneun baimnida]">할 수 있는 바입니다</span>.</p>
<p><span class="korean-word" data-translation="when one works diligently" data-pronunciation="묵묵히 일하노라면 [mukmukhi ilhanorаmyeon]">묵묵히 일하노라면</span> <span class="korean-word" data-translation="one day" data-pronunciation="언젠가는 [eonjenga-neun]">언젠가는</span> <span class="korean-word" data-translation="recognition will come" data-pronunciation="인정받게 되는 법이니 [injeongbatke doeneun beopini]">인정받게 되는 법이니</span> <span class="korean-word" data-translation="patience" data-pronunciation="인내야말로 [innaeуamallo]">인내야말로</span> <span class="korean-word" data-translation="the key virtue" data-pronunciation="핵심 덕목이라 [haeksim deongmogira]">핵심 덕목이라</span> <span class="korean-word" data-translation="I believe" data-pronunciation="여깁니다 [yeogipnida]">여깁니다</span>.</p>`,
            translation: "In modern society, labor is not only a means of livelihood but also a way of self-realization. Whatever work one does, as long as self-respect is maintained, that work is worthy of respect, and its contribution to society is great. Reflecting on work ethics, one can assert that honesty and responsibility are the foundation of professionalism. When one works diligently, recognition will come one day, so patience is the key virtue.",
            image: "",
            quiz: [
                { question: "현대 사회에서 노동은 무엇입니까? (Чем является труд в современном обществе?)", options: ["생계 수단만", "자아실현의 방편만", "생계 수단이자 자아실현의 방편", "고통"], correct: 2 },
                { question: "직업 윤리의 근간은 무엇입니까? (Что основа трудовой этики?)", options: ["높은 급여", "정직함과 책임감", "인맥", "학력"], correct: 1 },
                { question: "묵묵히 일하면 어떻게 됩니까? (Что происходит при усердной работе?)", options: ["피로해진다", "언젠가 인정받게 된다", "실패한다", "포기하게 된다"], correct: 1 },
                { question: "핵심 덕목으로 언급된 것은? (Какая добродетель упомянута?)", options: ["용기", "지혜", "인내", "겸손"], correct: 2 }
            ]
        },
        {
            id: 'personal-3',
            title: "The Art of Aging: Wisdom of Mature Years",
            subtitle: "노년의 지혜와 아름다운 늙음",
            korean: `<p><span class="korean-word" data-translation="when a person ages" data-pronunciation="사람이 나이 들어가노라면 [sarami nai deureоganorаmyeon]">사람이 나이 들어가노라면</span> <span class="korean-word" data-translation="the body weakens" data-pronunciation="육체는 쇠약해지거니와 [yukcheneun soeyakhaejigеoniwa]">육체는 쇠약해지거니와</span> <span class="korean-word" data-translation="the spirit on the contrary" data-pronunciation="정신은 오히려 [jeongsineun ohiryeo]">정신은 오히려</span> <span class="korean-word" data-translation="can become richer" data-pronunciation="더욱 풍요로워질 수 있는 바입니다 [deouk pungyorowojil su inneun baimnida]">더욱 풍요로워질 수 있는 바입니다</span>.</p>
<p><span class="korean-word" data-translation="if one thinks about old age" data-pronunciation="노년을 생각할진대 [nonyeoneul saenggakhalchindae]">노년을 생각할진대</span> <span class="korean-word" data-translation="there are not only losses" data-pronunciation="상실만 있는 것이 아니라 [sangsirman inneun geosi anira]">상실만 있는 것이 아니라</span> <span class="korean-word" data-translation="but also gains" data-pronunciation="얻는 것도 [eotneun geotdo]">얻는 것도</span> <span class="korean-word" data-translation="are numerous" data-pronunciation="많은 바이니 [maneun baini]">많은 바이니</span> <span class="korean-word" data-translation="therein lies wisdom" data-pronunciation="여기에 지혜가 있습니다 [yeogie jihyega itseumnida]">여기에 지혜가 있습니다</span>.</p>
<p><span class="korean-word" data-translation="as long as life continues" data-pronunciation="삶이 계속되는 한 [sarmi gyesokdoeneun han]">삶이 계속되는 한</span> <span class="korean-word" data-translation="not only reminisce about the past" data-pronunciation="과거를 회상할뿐더러 [gwageoreul hoesanghalppundeoreo]">과거를 회상할뿐더러</span> <span class="korean-word" data-translation="but also dream about the future" data-pronunciation="미래도 꿈꿀 수 있으니 [miraedo kkumkkul su isseuni]">미래도 꿈꿀 수 있으니</span> <span class="korean-word" data-translation="this is precisely" data-pronunciation="이것이야말로 [igeosiyamallo]">이것이야말로</span> <span class="korean-word" data-translation="the beauty of human existence" data-pronunciation="인간 존재의 아름다움입니다 [ingan jоnjaeui areumdaumimnida]">인간 존재의 아름다움입니다</span>.</p>
<p><span class="korean-word" data-translation="the ability to age gracefully" data-pronunciation="아름답게 늙는다는 것은 [areumdapke neungneundaneun geoseun]">아름답게 늙는다는 것은</span> <span class="korean-word" data-translation="to finish life with dignity" data-pronunciation="삶을 품위 있게 마무리하는 것이라 [sarmeul pumwi itge mamurihaneun geosira]">삶을 품위 있게 마무리하는 것이라</span> <span class="korean-word" data-translation="I believe" data-pronunciation="여깁니다 [yeogipnida]">여깁니다</span>.</p>`,
            translation: "When a person ages, the body weakens, but the spirit can become even richer. Thinking about old age, one realizes there are not only losses but also numerous gains — therein lies wisdom. As long as life continues, one can not only reminisce about the past but also dream about the future — this is the beauty of human existence. The ability to age gracefully means finishing life with dignity.",
            image: "",
            quiz: [
                { question: "나이 들면 정신은 어떻게 됩니까? (Что происходит с духом при старении?)", options: ["쇠약해진다", "변하지 않는다", "더욱 풍요로워질 수 있다", "사라진다"], correct: 2 },
                { question: "노년에 무엇을 얻습니까? (Что приобретаешь в старости?)", options: ["상실만", "얻는 것도 많다", "아무것도 없다", "재산만"], correct: 1 },
                { question: "삶이 계속되는 한 무엇을 할 수 있습니까? (Что можно делать, пока жизнь продолжается?)", options: ["과거만 회상", "미래도 꿈꾸기", "아무것도 못함", "일만 함"], correct: 1 },
                { question: "아름답게 늙는다는 것은 무엇입니까? (Что значит стареть красиво?)", options: ["외모 유지", "삶을 품위 있게 마무리", "돈을 모음", "운동함"], correct: 1 }
            ]
        },
        {
            id: 'personal-4',
            title: "Solitude as a Path to Oneself",
            subtitle: "고독의 가치와 자아 성찰",
            korean: `<p><span class="korean-word" data-translation="in the modern world" data-pronunciation="현대 세계에서 [hyeondae segyeeseo]">현대 세계에서</span> <span class="korean-word" data-translation="solitude" data-pronunciation="고독은 [godоgeun]">고독은</span> <span class="korean-word" data-translation="is often perceived negatively, however" data-pronunciation="흔히 부정적으로 여겨지거니와 [heunhi bujеongjeоgeuro yeоgyeojigеoniwa]">흔히 부정적으로 여겨지거니와</span> <span class="korean-word" data-translation="in reality" data-pronunciation="실은 [sireun]">실은</span> <span class="korean-word" data-translation="holds great value" data-pronunciation="큰 가치를 지닌 바입니다 [keun gachireul jinin baimnida]">큰 가치를 지닌 바입니다</span>.</p>
<p><span class="korean-word" data-translation="when one faces oneself alone" data-pronunciation="홀로 자신과 마주하노라면 [hollo jasigwa majuhanorаmyeon]">홀로 자신과 마주하노라면</span> <span class="korean-word" data-translation="not only fears arise" data-pronunciation="두려움이 생길뿐더러 [duryеoumi saenggilppundeoreo]">두려움이 생길뿐더러</span> <span class="korean-word" data-translation="but also deep insight" data-pronunciation="깊은 통찰도 [gipeun tongchaldo]">깊은 통찰도</span> <span class="korean-word" data-translation="is born" data-pronunciation="얻게 되니 [eotke doeni]">얻게 되니</span> <span class="korean-word" data-translation="this is precisely" data-pronunciation="이것이야말로 [igeosiyamallo]">이것이야말로</span> <span class="korean-word" data-translation="the path to self-discovery" data-pronunciation="자아 발견의 길입니다 [jaa balgyeonui gilimnida]">자아 발견의 길입니다</span>.</p>
<p><span class="korean-word" data-translation="if one contemplates the meaning of solitude" data-pronunciation="고독의 의미를 생각할진대 [godogui uimireul saenggakhalchindae]">고독의 의미를 생각할진대</span> <span class="korean-word" data-translation="great thinkers" data-pronunciation="위대한 사상가들이야말로 [widaehan sasanggadeuriуamallo]">위대한 사상가들이야말로</span> <span class="korean-word" data-translation="through solitude" data-pronunciation="고독을 통해 [godоgeul tonghae]">고독을 통해</span> <span class="korean-word" data-translation="reached the truth" data-pronunciation="진리에 도달한 바입니다 [jillie dodаlhan baimnida]">진리에 도달한 바입니다</span>.</p>
<p><span class="korean-word" data-translation="as long as one is capable of reflection" data-pronunciation="사유할 수 있는 한 [sayuhal su inneun han]">사유할 수 있는 한</span> <span class="korean-word" data-translation="solitude" data-pronunciation="고독은 [godоgeun]">고독은</span> <span class="korean-word" data-translation="is a friend, not a foe" data-pronunciation="적이 아닌 벗이라 [jeogi anin beosira]">적이 아닌 벗이라</span> <span class="korean-word" data-translation="I assert" data-pronunciation="하겠습니다 [hagetseumnida]">하겠습니다</span>.</p>`,
            translation: "In the modern world, solitude is often perceived negatively, but in reality it holds great value. When facing oneself alone, not only do fears arise, but deep insight is also gained — this is the path to self-discovery. Contemplating the meaning of solitude, one realizes that great thinkers reached the truth precisely through solitude. As long as one is capable of reflection, solitude is a friend, not a foe.",
            image: "",
            quiz: [
                { question: "현대 세계에서 고독은 어떻게 여겨집니까? (Как воспринимается одиночество?)", options: ["긍정적으로", "부정적으로", "중립적으로", "무관심하게"], correct: 1 },
                { question: "홀로 자신과 마주하면 무엇을 얻습니까? (Что получаешь наедине с собой?)", options: ["두려움만", "통찰만", "두려움과 통찰", "아무것도"], correct: 2 },
                { question: "위대한 사상가들은 어떻게 진리에 도달했습니까? (Как мыслители достигли истины?)", options: ["돈으로", "고독을 통해", "권력으로", "유명세로"], correct: 1 },
                { question: "고독은 무엇이라 했습니까? (Чем назвали одиночество?)", options: ["적", "벗", "장애물", "질병"], correct: 1 }
            ]
        }
    ],
    stories: [
        {
            id: 'stories-1',
            title: "A Night in a Mountain Monastery",
            subtitle: "산사에서의 하룻밤",
            korean: `<p><span class="korean-word" data-translation="late at night" data-pronunciation="깊은 밤 [gipeun bam]">깊은 밤</span> <span class="korean-word" data-translation="sitting alone in a mountain monastery" data-pronunciation="산사에 홀로 앉아 [sansa-e hollo anja]">산사에 홀로 앉아</span> <span class="korean-word" data-translation="when listening to the silence" data-pronunciation="적막에 귀 기울이노라면 [jeongmage gwi giurinorаmyeon]">적막에 귀 기울이노라면</span> <span class="korean-word" data-translation="the rustling of wind through the pines" data-pronunciation="소나무 사이로 스치는 바람 소리가 [sonamu sairo seuchineun baram soriga]">소나무 사이로 스치는 바람 소리가</span> <span class="korean-word" data-translation="like words of wisdom" data-pronunciation="마치 깨달음의 말씀처럼 [machi kkaedareumui malsseumcheoreom]">마치 깨달음의 말씀처럼</span> <span class="korean-word" data-translation="touches the heart" data-pronunciation="가슴에 와닿습니다 [gaseume wadatnеumnida]">가슴에 와닿습니다</span>.</p>
<p><span class="korean-word" data-translation="the old monk" data-pronunciation="늙은 스님께서는 [neulgeun seunimkkesеoneun]">늙은 스님께서는</span> <span class="korean-word" data-translation="not only poured tea" data-pronunciation="차를 따르실뿐더러 [chareul ttareusibilppundeoreo]">차를 따르실뿐더러</span> <span class="korean-word" data-translation="smiled silently" data-pronunciation="말없이 미소 지으시거니와 [mareobsi miso jieusigеoniwa]">말없이 미소 지으시거니와</span> <span class="korean-word" data-translation="in that silence" data-pronunciation="그 침묵 속에 [geu chimmuk soge]">그 침묵 속에</span> <span class="korean-word" data-translation="a profound teaching was contained" data-pronunciation="깊은 가르침이 담겨 있었습니다 [gipeun gareuchimi damgyeo isseotseumnida]">깊은 가르침이 담겨 있었습니다</span>.</p>
<p><span class="korean-word" data-translation="as long as the bustling world exists" data-pronunciation="속세가 번잡한 한 [soksega beonjaphan han]">속세가 번잡한 한</span> <span class="korean-word" data-translation="such secluded places" data-pronunciation="이런 고즈넉한 곳이야말로 [ireon gojeunеokhan gosiyamallo]">이런 고즈넉한 곳이야말로</span> <span class="korean-word" data-translation="are needed by people" data-pronunciation="사람들에게 필요한 바이니 [saramdeulege pilyohan baini]">사람들에게 필요한 바이니</span> <span class="korean-word" data-translation="monastery culture" data-pronunciation="사찰 문화를 [sachal munhwareul]">사찰 문화를</span> <span class="korean-word" data-translation="should be preserved" data-pronunciation="보존해야 할 것입니다 [bojeonhaeya hal geosimnida]">보존해야 할 것입니다</span>.</p>
<p><span class="korean-word" data-translation="if I recall that night" data-pronunciation="그 밤을 떠올릴진대 [geu bameul ttеoollichindae]">그 밤을 떠올릴진대</span> <span class="korean-word" data-translation="even now" data-pronunciation="지금도 [jigeumdo]">지금도</span> <span class="korean-word" data-translation="peace fills the heart" data-pronunciation="마음이 평온해지는 것은 [maeumi pyeongonhaejineun geoseun]">마음이 평온해지는 것은</span> <span class="korean-word" data-translation="the mystery of silence" data-pronunciation="고요함의 신비라 [goyohamui sinbira]">고요함의 신비라</span> <span class="korean-word" data-translation="one could say" data-pronunciation="하겠습니다 [hagetseumnida]">하겠습니다</span>.</p>`,
            translation: "Late at night, sitting alone in a mountain monastery and listening to the silence, you hear the rustling of wind through the pines touching your heart like words of wisdom. The old monk not only poured tea but also smiled silently, and in that silence a profound teaching was contained. As long as the bustling world exists, such secluded places are needed by people, so monastery culture should be preserved. When I recall that night, even now I find peace in my heart — this is the mystery of silence.",
            image: "",
            quiz: [
                { question: "산사에서 무엇에 귀 기울였습니까? (К чему прислушивался в монастыре?)", options: ["독경 소리", "적막", "새소리", "물소리"], correct: 1 },
                { question: "늙은 스님은 어떻게 가르침을 전했습니까? (Как монах передавал учение?)", options: ["설법으로", "침묵과 미소로", "경전을 읽어서", "노래로"], correct: 1 },
                { question: "속세가 번잡할 때 무엇이 필요합니까? (Что нужно, когда мир суетен?)", options: ["돈", "권력", "고즈넉한 곳", "오락"], correct: 2 },
                { question: "그 밤을 떠올리면 어떻게 됩니까? (Что происходит при воспоминании о той ночи?)", options: ["슬퍼진다", "화가 난다", "마음이 평온해진다", "피곤해진다"], correct: 2 }
            ]
        },
        {
            id: 'stories-2',
            title: "The Legacy of a Calligrapher Grandfather",
            subtitle: "서예가 할아버지의 유산",
            korean: `<p><span class="korean-word" data-translation="my late grandfather" data-pronunciation="돌아가신 할아버지께서는 [doragasin harabeojikkesеoneun]">돌아가신 할아버지께서는</span> <span class="korean-word" data-translation="his entire life" data-pronunciation="평생을 [pyeongsaengeul]">평생을</span> <span class="korean-word" data-translation="devoted to calligraphy" data-pronunciation="서예에 정진하셨거니와 [seoyeе jeongjinhaseyotgeoniwa]">서예에 정진하셨거니와</span> <span class="korean-word" data-translation="his works" data-pronunciation="그분의 작품들은 [geubunui jakpumdeureun]">그분의 작품들은</span> <span class="korean-word" data-translation="even now" data-pronunciation="지금도 [jigeumdo]">지금도</span> <span class="korean-word" data-translation="many people's" data-pronunciation="많은 이들의 [maneun ideului]">많은 이들의</span> <span class="korean-word" data-translation="touch hearts" data-pronunciation="가슴을 울립니다 [gaseumeul ullimnida]">가슴을 울립니다</span>.</p>
<p><span class="korean-word" data-translation="in every stroke" data-pronunciation="한 획 한 획에 [han hoek han hoege]">한 획 한 획에</span> <span class="korean-word" data-translation="not only the master's skill is captured" data-pronunciation="장인의 기량이 담겼을뿐더러 [janginui giryagi damgyeotseulppundeoreo]">장인의 기량이 담겼을뿐더러</span> <span class="korean-word" data-translation="even his soul" data-pronunciation="혼까지 [honkkaji]">혼까지</span> <span class="korean-word" data-translation="is imbued" data-pronunciation="스며들어 있으니 [seumyeodeureo isseuni]">스며들어 있으니</span> <span class="korean-word" data-translation="looking at them" data-pronunciation="그것을 볼 때마다 [geugeoseul bol ttaemada]">그것을 볼 때마다</span> <span class="korean-word" data-translation="grandfather seems to be right before my eyes" data-pronunciation="할아버지가 눈앞에 계신 듯합니다 [harabeojiga nuname gyesin deutamnida]">할아버지가 눈앞에 계신 듯합니다</span>.</p>
<p><span class="korean-word" data-translation="if one thinks about legacy" data-pronunciation="유산을 생각할진대 [yusaneul saenggakhalchindae]">유산을 생각할진대</span> <span class="korean-word" data-translation="material values" data-pronunciation="물질적 가치보다 [muljiljeok gachiboda]">물질적 가치보다</span> <span class="korean-word" data-translation="spiritual heritage" data-pronunciation="정신적 유산이야말로 [jeongsinjeok yusaniyamallo]">정신적 유산이야말로</span> <span class="korean-word" data-translation="true value" data-pronunciation="진정한 가치라 [jinjeonghan gachira]">진정한 가치라</span> <span class="korean-word" data-translation="I assert" data-pronunciation="하겠습니다 [hagetseumnida]">하겠습니다</span>.</p>
<p><span class="korean-word" data-translation="as long as the family line continues" data-pronunciation="가문이 이어지는 한 [gamuni ieojineun han]">가문이 이어지는 한</span> <span class="korean-word" data-translation="his spirit" data-pronunciation="그분의 정신은 [geubunui jeongsineun]">그분의 정신은</span> <span class="korean-word" data-translation="will live forever" data-pronunciation="영원히 살아 있을 바이니 [yeongwonhi sara isseul baini]">영원히 살아 있을 바이니</span> <span class="korean-word" data-translation="this is precisely" data-pronunciation="이것이야말로 [igеosiyamallo]">이것이야말로</span> <span class="korean-word" data-translation="true immortality" data-pronunciation="참된 불멸이라 [chamdoen bulmyeorira]">참된 불멸이라</span> <span class="korean-word" data-translation="I believe" data-pronunciation="믿습니다 [mitseumnida]">믿습니다</span>.</p>`,
            translation: "My late grandfather devoted his entire life to calligraphy, and his works still touch the hearts of many people. In every stroke, not only the master's skill is captured, but his very soul is imbued, so looking at them, it feels as though grandfather is right before my eyes. Thinking about legacy, I assert that spiritual heritage is of greater value than material possessions. As long as the family line continues, his spirit will live forever — this is true immortality.",
            image: "",
            quiz: [
                { question: "할아버지는 평생 무엇에 정진하셨습니까? (Чему дед посвятил жизнь?)", options: ["그림", "서예", "음악", "도예"], correct: 1 },
                { question: "작품에 무엇이 담겨 있습니까? (Что заключено в произведениях?)", options: ["기량만", "혼만", "기량과 혼", "재료만"], correct: 2 },
                { question: "물질적 가치보다 무엇이 진정한 가치입니까? (Что ценнее материального?)", options: ["명예", "권력", "정신적 유산", "돈"], correct: 2 },
                { question: "참된 불멸이란 무엇입니까? (Что есть истинное бессмертие?)", options: ["육체의 보존", "재산의 축적", "정신이 영원히 사는 것", "유명해지는 것"], correct: 2 }
            ]
        },
        {
            id: 'stories-3',
            title: "A Letter from the Past",
            subtitle: "과거에서 온 편지",
            korean: `<p><span class="korean-word" data-translation="when sorting through old things" data-pronunciation="오래된 물건들을 정리하노라면 [oraedoen mulgeondereul jeongnirhanorаmyeon]">오래된 물건들을 정리하노라면</span> <span class="korean-word" data-translation="unexpectedly" data-pronunciation="뜻밖에도 [tteutbakkedo]">뜻밖에도</span> <span class="korean-word" data-translation="letters of my late mother" data-pronunciation="돌아가신 어머니의 편지를 [doragasin eomeoniui pyeonjireul]">돌아가신 어머니의 편지를</span> <span class="korean-word" data-translation="I discovered" data-pronunciation="발견하게 된 바입니다 [balgyeonhage doen baimnida]">발견하게 된 바입니다</span>.</p>
<p><span class="korean-word" data-translation="reading the faded lines" data-pronunciation="바랜 글씨를 읽노라면 [baraen geulsshireul ingnorаmyeon]">바랜 글씨를 읽노라면</span> <span class="korean-word" data-translation="not only tears flow" data-pronunciation="눈물이 흐를뿐더러 [nunmuri heurеulppundeoreo]">눈물이 흐를뿐더러</span> <span class="korean-word" data-translation="but the heart also warms" data-pronunciation="마음도 따뜻해지거니와 [maeumdo ttatteuthаejigеoniwa]">마음도 따뜻해지거니와</span> <span class="korean-word" data-translation="mother's love" data-pronunciation="어머니의 사랑이 [eomeoniui sarangi]">어머니의 사랑이</span> <span class="korean-word" data-translation="is felt anew" data-pronunciation="다시금 느껴집니다 [dasigeum neukkyеojipnida]">다시금 느껴집니다</span>.</p>
<p><span class="korean-word" data-translation="if one contemplates the meaning of time" data-pronunciation="시간의 의미를 생각할진대 [siganui uimireul saenggakhalchindae]">시간의 의미를 생각할진대</span> <span class="korean-word" data-translation="true love" data-pronunciation="진정한 사랑이야말로 [jinjeonghan sarangiyamallo]">진정한 사랑이야말로</span> <span class="korean-word" data-translation="transcends time" data-pronunciation="시간을 초월하는 바입니다 [siganeul chowolhaneun baimnida]">시간을 초월하는 바입니다</span>.</p>
<p><span class="korean-word" data-translation="as long as memory lives" data-pronunciation="기억이 살아 있는 한 [gieogi sara inneun han]">기억이 살아 있는 한</span> <span class="korean-word" data-translation="those who have departed" data-pronunciation="떠난 이들은 [tteonan ideureun]">떠난 이들은</span> <span class="korean-word" data-translation="do not vanish forever" data-pronunciation="영원히 사라지지 않으니 [yeongwonhi sarajiji anheuni]">영원히 사라지지 않으니</span> <span class="korean-word" data-translation="this is consolation" data-pronunciation="이것이 위로입니다 [igeosi wiroimnida]">이것이 위로입니다</span>.</p>`,
            translation: "While sorting through old things, I unexpectedly discovered letters from my late mother. Reading the faded lines, not only do tears flow, but the heart also warms — mother's love is felt anew. Contemplating the meaning of time, one realizes that true love transcends time. As long as memory lives, those who have departed do not vanish forever — therein lies consolation.",
            image: "",
            quiz: [
                { question: "무엇을 정리하다가 편지를 발견했습니까? (Что разбирал, когда нашёл письмо?)", options: ["새 물건", "오래된 물건", "책", "옷"], correct: 1 },
                { question: "편지를 읽으면 어떻게 됩니까? (Что происходит при чтении письма?)", options: ["눈물만 흐름", "마음만 따뜻해짐", "눈물과 따뜻함", "아무 감정 없음"], correct: 2 },
                { question: "진정한 사랑은 무엇을 초월합니까? (Что превосходит истинная любовь?)", options: ["공간", "시간", "물질", "권력"], correct: 1 },
                { question: "기억이 살아 있으면 떠난 이들은 어떻게 됩니까? (Что происходит с ушедшими при живой памяти?)", options: ["완전히 사라짐", "영원히 사라지지 않음", "잊혀짐", "미움받음"], correct: 1 }
            ]
        },
        {
            id: 'stories-4',
            title: "An Encounter at the Crossroads of Fate",
            subtitle: "운명의 교차로에서",
            korean: `<p><span class="korean-word" data-translation="life sometimes" data-pronunciation="삶이란 때로는 [sarmiran ttaeroneun]">삶이란 때로는</span> <span class="korean-word" data-translation="amazing encounters" data-pronunciation="놀라운 만남을 [nollaun mannameul]">놀라운 만남을</span> <span class="korean-word" data-translation="bestows upon us" data-pronunciation="선사하는 바이니 [seonsahaneun baini]">선사하는 바이니</span> <span class="korean-word" data-translation="this is what they call fate" data-pronunciation="이를 운명이라 하겠습니다 [ireul unmyeongira hagetseumnida]">이를 운명이라 하겠습니다</span>.</p>
<p><span class="korean-word" data-translation="when I recall that encounter" data-pronunciation="그 만남을 떠올리노라면 [geu mannameul tteoollinorаmyeon]">그 만남을 떠올리노라면</span> <span class="korean-word" data-translation="not only gratitude I feel" data-pronunciation="감사함을 느낄뿐더러 [gamsahameul neukkilppundeoreo]">감사함을 느낄뿐더러</span> <span class="korean-word" data-translation="but also awe" data-pronunciation="경이로움도 [gyeongiloumdo]">경이로움도</span> <span class="korean-word" data-translation="I experience" data-pronunciation="느끼게 되거니와 [neukkkige doegеoniwa]">느끼게 되거니와</span> <span class="korean-word" data-translation="it changed my life" data-pronunciation="그것이 제 삶을 바꾼 바입니다 [geugeosi je sarmeul bakkun baimnida]">그것이 제 삶을 바꾼 바입니다</span>.</p>
<p><span class="korean-word" data-translation="if one contemplates coincidence" data-pronunciation="우연의 의미를 생각할진대 [uyeonui uimireul saenggakhalchindae]">우연의 의미를 생각할진대</span> <span class="korean-word" data-translation="there are no accidental encounters" data-pronunciation="우연한 만남이란 없는 바이니 [uyeonhan mannamiran eomneun baini]">우연한 만남이란 없는 바이니</span> <span class="korean-word" data-translation="everything is predetermined" data-pronunciation="모든 것이 필연이라 [modeun geosi piryeonira]">모든 것이 필연이라</span> <span class="korean-word" data-translation="I believe" data-pronunciation="믿습니다 [mitseumnida]">믿습니다</span>.</p>
<p><span class="korean-word" data-translation="as long as we are alive" data-pronunciation="우리가 살아 있는 한 [uriga sara inneun han]">우리가 살아 있는 한</span> <span class="korean-word" data-translation="encounters and partings" data-pronunciation="만남과 이별은 [mannamgwa ibyeoreun]">만남과 이별은</span> <span class="korean-word" data-translation="will continue" data-pronunciation="계속될 바이니 [gyesokdoel baini]">계속될 바이니</span> <span class="korean-word" data-translation="every encounter" data-pronunciation="매 만남을 [mae mannameul]">매 만남을</span> <span class="korean-word" data-translation="should be cherished" data-pronunciation="소중히 여겨야 합니다 [sojunghi yeоgyeoya hamnida]">소중히 여겨야 합니다</span>.</p>`,
            translation: "Life sometimes bestows upon us amazing encounters — this is what they call fate. Recalling that encounter, I feel not only gratitude but also awe — it changed my life. Contemplating coincidence, I believe there are no accidental encounters — everything is predetermined. As long as we are alive, encounters and partings will continue, so every encounter should be cherished.",
            image: "",
            quiz: [
                { question: "삶이 선사하는 것은 무엇입니까? (Что преподносит жизнь?)", options: ["돈", "놀라운 만남", "권력", "명예"], correct: 1 },
                { question: "그 만남을 떠올리면 무엇을 느낍니까? (Что чувствуешь при воспоминании?)", options: ["감사함만", "경이로움만", "감사함과 경이로움", "분노"], correct: 2 },
                { question: "우연한 만남에 대해 어떻게 생각합니까? (Что думаете о случайных встречах?)", options: ["존재한다", "존재하지 않는다", "중요하지 않다", "피해야 한다"], correct: 1 },
                { question: "매 만남을 어떻게 해야 합니까? (Как относиться к каждой встрече?)", options: ["무시", "소중히 여김", "피함", "잊음"], correct: 1 }
            ]
        }
    ],
    culture: [
        {
            id: 'culture-1',
            title: "The Aesthetics of Korean Garden Art",
            subtitle: "한국 정원 예술의 미학",
            korean: `<p><span class="korean-word" data-translation="traditional Korean garden" data-pronunciation="전통 한국 정원은 [jeontong hanguk jeongwoneun]">전통 한국 정원은</span> <span class="korean-word" data-translation="unlike Western ones" data-pronunciation="서양 정원과 달리 [seоyang jeongwon-gwa dalli]">서양 정원과 달리</span> <span class="korean-word" data-translation="harmony with nature" data-pronunciation="자연과의 조화를 [jayeon-gwaui johwareul]">자연과의 조화를</span> <span class="korean-word" data-translation="as the highest value" data-pronunciation="최고의 가치로 삼는 바이니 [choеgoui gachiro samneun baini]">최고의 가치로 삼는 바이니</span> <span class="korean-word" data-translation="this is precisely" data-pronunciation="이것이야말로 [igеosiyamallo]">이것이야말로</span> <span class="korean-word" data-translation="the quintessence of Eastern wisdom" data-pronunciation="동양적 지혜의 결정체라 [dongyangjeok jihyeui gyeoljeonchera]">동양적 지혜의 결정체라</span> <span class="korean-word" data-translation="one could say" data-pronunciation="하겠습니다 [hagetseumnida]">하겠습니다</span>.</p>
<p><span class="korean-word" data-translation="when gazing at lotuses in the pond" data-pronunciation="연못의 연꽃을 바라보노라면 [yeonmotui yeonkkocheul barabonorаmyeon]">연못의 연꽃을 바라보노라면</span> <span class="korean-word" data-translation="not only does beauty please the eye" data-pronunciation="아름다움이 눈을 즐겁게 할뿐더러 [areumdaumi nuneul jeulgeobge halppundeoreo]">아름다움이 눈을 즐겁게 할뿐더러</span> <span class="korean-word" data-translation="but the soul is also purified" data-pronunciation="마음까지 정화되거니와 [maeumkkaji jeonghwadoegеoniwa]">마음까지 정화되거니와</span> <span class="korean-word" data-translation="this experience" data-pronunciation="이런 경험이야말로 [ireon gyeongheomiyamallo]">이런 경험이야말로</span> <span class="korean-word" data-translation="the essence of garden art" data-pronunciation="정원 예술의 본질입니다 [jeongwon yesului bonchirimиnida]">정원 예술의 본질입니다</span>.</p>
<p><span class="korean-word" data-translation="as long as modernity rushes" data-pronunciation="현대가 분주한 한 [hyeondaega bunjuhan han]">현대가 분주한 한</span> <span class="korean-word" data-translation="such spaces of tranquility" data-pronunciation="이런 안식의 공간이 [ireon ansikui gonggani]">이런 안식의 공간이</span> <span class="korean-word" data-translation="are necessary" data-pronunciation="필요하니 [pilyohani]">필요하니</span> <span class="korean-word" data-translation="preserving traditions" data-pronunciation="전통 보존에 [jeontong bojone]">전통 보존에</span> <span class="korean-word" data-translation="should be given attention" data-pronunciation="힘써야 할 바입니다 [himssеoya hal baimnida]">힘써야 할 바입니다</span>.</p>
<p><span class="korean-word" data-translation="if one thinks about the future of gardens" data-pronunciation="정원의 미래를 생각할진대 [jeongwonui miraereul saenggakhalchindae]">정원의 미래를 생각할진대</span> <span class="korean-word" data-translation="the blend of tradition and modernity" data-pronunciation="전통과 현대의 조화야말로 [jeontong-gwa hyeondaeui johwayamallo]">전통과 현대의 조화야말로</span> <span class="korean-word" data-translation="the way forward" data-pronunciation="나아갈 길이라 [naagal girira]">나아갈 길이라</span> <span class="korean-word" data-translation="I believe" data-pronunciation="생각합니다 [saenggakhamnida]">생각합니다</span>.</p>`,
            translation: "The traditional Korean garden, unlike Western ones, holds harmony with nature as its highest value — this is the quintessence of Eastern wisdom. Gazing at lotuses in the pond, not only does beauty please the eye, but the soul is also purified — this is the essence of garden art. As long as modernity rushes on, such spaces of tranquility are necessary, so attention should be given to preserving traditions. Thinking about the future of gardens, I believe the blend of tradition and modernity is the way forward.",
            image: "",
            quiz: [
                { question: "전통 한국 정원의 최고 가치는 무엇입니까? (Высшая ценность корейского сада?)", options: ["화려함", "자연과의 조화", "크기", "다양한 식물"], correct: 1 },
                { question: "연꽃을 바라보면 어떻게 됩니까? (Что происходит при созерцании лотосов?)", options: ["지루해진다", "눈과 마음이 정화된다", "배고파진다", "졸려진다"], correct: 1 },
                { question: "현대가 분주할 때 무엇이 필요합니까? (Что нужно в суетливой современности?)", options: ["더 많은 일", "안식의 공간", "더 빠른 속도", "더 많은 돈"], correct: 1 },
                { question: "정원의 미래를 위해 무엇이 필요합니까? (Что нужно для будущего садов?)", options: ["서양화", "전통과 현대의 조화", "완전한 보존만", "완전한 변화만"], correct: 1 }
            ]
        },
        {
            id: 'culture-2',
            title: "The Philosophy of Korean Ceramics",
            subtitle: "한국 도자기의 철학",
            korean: `<p><span class="korean-word" data-translation="Korean ceramics" data-pronunciation="한국 도자기는 [hanguk dojagineun]">한국 도자기는</span> <span class="korean-word" data-translation="not merely a vessel" data-pronunciation="단순한 그릇일뿐더러 [dansunhan geurеusilppundeoreo]">단순한 그릇일뿐더러</span> <span class="korean-word" data-translation="an embodiment of philosophy" data-pronunciation="철학의 구현체이기도 하거니와 [cheolhakui guhyeonchеigido hagеoniwa]">철학의 구현체이기도 하거니와</span> <span class="korean-word" data-translation="the aesthetic ideals of ancestors" data-pronunciation="선조들의 미적 이상이 [seonjoderui mijeok isangi]">선조들의 미적 이상이</span> <span class="korean-word" data-translation="are embodied in them" data-pronunciation="녹아들어 있는 바입니다 [nogadeoreo inneun baimnida]">녹아들어 있는 바입니다</span>.</p>
<p><span class="korean-word" data-translation="the celadon of the Goryeo era" data-pronunciation="고려청자의 비색이야말로 [goryeocheongjaui bisaegiyamallo]">고려청자의 비색이야말로</span> <span class="korean-word" data-translation="an unrivaled color" data-pronunciation="천하제일의 색이라 [cheonhajeirai sаеgira]">천하제일의 색이라</span> <span class="korean-word" data-translation="is called" data-pronunciation="일컬어지거니와 [ilkeoreojigеoniwa]">일컬어지거니와</span> <span class="korean-word" data-translation="the pure white porcelain of Joseon" data-pronunciation="조선백자의 순백함 또한 [joseonbaekjaui sunbaeкham ttohan]">조선백자의 순백함 또한</span> <span class="korean-word" data-translation="is no less beautiful" data-pronunciation="아름다움에 뒤지지 않습니다 [areumdaume dwijiji anseumnida]">아름다움에 뒤지지 않습니다</span>.</p>
<p><span class="korean-word" data-translation="when examining old ceramics" data-pronunciation="옛 도자기를 살피노라면 [yet dojagireul salpinorаmyeon]">옛 도자기를 살피노라면</span> <span class="korean-word" data-translation="in imperfections" data-pronunciation="불완전함 속에서 [bulwanjeonham sogeso]">불완전함 속에서</span> <span class="korean-word" data-translation="perfection is discovered" data-pronunciation="완전함을 발견하게 되니 [wanjeonhameul balgyeonhage doeni]">완전함을 발견하게 되니</span> <span class="korean-word" data-translation="this paradox" data-pronunciation="이 역설이야말로 [i yeoksеoriyamallo]">이 역설이야말로</span> <span class="korean-word" data-translation="the depth of Eastern aesthetics" data-pronunciation="동양 미학의 깊이입니다 [dongyang mihakui gipiimnida]">동양 미학의 깊이입니다</span>.</p>
<p><span class="korean-word" data-translation="as long as beauty is valued" data-pronunciation="아름다움이 존중받는 한 [areumdaumi jonjungbatneun han]">아름다움이 존중받는 한</span> <span class="korean-word" data-translation="this art" data-pronunciation="이 예술은 [i yesureun]">이 예술은</span> <span class="korean-word" data-translation="will be passed on" data-pronunciation="계승될 바이니 [gyeseungdoel baini]">계승될 바이니</span> <span class="korean-word" data-translation="therein lies hope" data-pronunciation="여기에 희망이 있습니다 [yeogie huimangi itseumnida]">여기에 희망이 있습니다</span>.</p>`,
            translation: "Korean ceramics are not merely vessels but also embodiments of philosophy, reflecting the aesthetic ideals of ancestors. The celadon color of the Goryeo era is called unrivaled, yet the pure whiteness of Joseon porcelain is no less beautiful. Examining old ceramics, one discovers perfection within imperfections — in this paradox lies the depth of Eastern aesthetics. As long as beauty is valued, this art will be passed on — therein lies hope.",
            image: "",
            quiz: [
                { question: "한국 도자기는 무엇입니까? (Что такое корейская керамика?)", options: ["단순한 그릇", "철학의 구현체", "장식품만", "현대 예술"], correct: 1 },
                { question: "고려청자의 비색은 어떻게 평가됩니까? (Как оценивается цвет селадона?)", options: ["평범하다", "천하제일의 색", "어둡다", "촌스럽다"], correct: 1 },
                { question: "옛 도자기에서 무엇을 발견합니까? (Что обнаруживается в старой керамике?)", options: ["결함만", "불완전함 속의 완전함", "실용성만", "현대성"], correct: 1 },
                { question: "이 예술이 계승되려면 무엇이 필요합니까? (Что нужно для передачи искусства?)", options: ["돈", "아름다움의 존중", "정부 지원만", "외국의 인정"], correct: 1 }
            ]
        },
        {
            id: 'culture-3',
            title: "Korean Music: From Pansori to K-pop",
            subtitle: "판소리에서 K-pop까지",
            korean: `<p><span class="korean-word" data-translation="the Korean musical tradition" data-pronunciation="한국 음악 전통은 [hanguk еumak jeontоngeun]">한국 음악 전통은</span> <span class="korean-word" data-translation="not only has ancient roots" data-pronunciation="유구한 뿌리를 지녔을뿐더러 [yagunan ppurirul jinyеotseulppundeoreo]">유구한 뿌리를 지녔을뿐더러</span> <span class="korean-word" data-translation="in modern times as well" data-pronunciation="현대에도 [hyeondaedo]">현대에도</span> <span class="korean-word" data-translation="continues to develop" data-pronunciation="발전을 거듭하는 바입니다 [baljеoneul geodeuphaneun baimnida]">발전을 거듭하는 바입니다</span>.</p>
<p><span class="korean-word" data-translation="when listening to pansori" data-pronunciation="판소리를 듣노라면 [pansorireul deungnorаmyeon]">판소리를 듣노라면</span> <span class="korean-word" data-translation="the singer's voice" data-pronunciation="창자의 목소리가 [changraui moksoriga]">창자의 목소리가</span> <span class="korean-word" data-translation="not only pleases the ears" data-pronunciation="귀를 즐겁게 할뿐더러 [gwireul jeulgeopke halppundeoreo]">귀를 즐겁게 할뿐더러</span> <span class="korean-word" data-translation="but also shakes the soul" data-pronunciation="영혼까지 울리거니와 [yeоnghonkkaji ulligеoniwa]">영혼까지 울리거니와</span> <span class="korean-word" data-translation="this is a unique art" data-pronunciation="이것이야말로 독특한 예술입니다 [igеosiyamallo doktukan yesurimmida]">이것이야말로 독특한 예술입니다</span>.</p>
<p><span class="korean-word" data-translation="if one thinks about K-pop" data-pronunciation="K-pop을 생각할진대 [K-pop-eul saenggakhalchindae]">K-pop을 생각할진대</span> <span class="korean-word" data-translation="traditional aesthetics" data-pronunciation="전통적 감수성과 [jeontongjeok gamsuseonggwa]">전통적 감수성과</span> <span class="korean-word" data-translation="modern technology" data-pronunciation="현대적 기술의 [hyeondaejeok gisurui]">현대적 기술의</span> <span class="korean-word" data-translation="fusion" data-pronunciation="융합이야말로 [yunghapiyamallo]">융합이야말로</span> <span class="korean-word" data-translation="the secret of success" data-pronunciation="성공의 비결인 바입니다 [sеonggongui bigyеorin baimnida]">성공의 비결인 바입니다</span>.</p>
<p><span class="korean-word" data-translation="as long as music exists" data-pronunciation="음악이 존재하는 한 [еumagi jonjaehaneun han]">음악이 존재하는 한</span> <span class="korean-word" data-translation="the people" data-pronunciation="민족은 [minjоgeun]">민족은</span> <span class="korean-word" data-translation="will live" data-pronunciation="살아 있을 바이니 [sara isseul baini]">살아 있을 바이니</span> <span class="korean-word" data-translation="music is the soul of culture" data-pronunciation="음악은 문화의 영혼입니다 [еumageun munhwaui yeоnghoninmida]">음악은 문화의 영혼입니다</span>.</p>`,
            translation: "The Korean musical tradition not only has deep ancient roots but also continues to develop in modern times. When listening to pansori, the singer's voice not only pleases the ears but also shakes the soul — this is a unique art. Thinking about K-pop, one realizes that the fusion of traditional aesthetics and modern technology is the secret of success. As long as music exists, the people will live — music is the soul of culture.",
            image: "",
            quiz: [
                { question: "한국 음악 전통은 어떻습니까? (Какова корейская музыкальная традиция?)", options: ["현대에만 존재", "유구한 뿌리와 현대적 발전", "외국에서 유래", "쇠퇴 중"], correct: 1 },
                { question: "판소리를 들으면 어떻게 됩니까? (Что происходит при слушании пхансори?)", options: ["귀만 즐거움", "영혼까지 울림", "지루함", "화남"], correct: 1 },
                { question: "K-pop의 성공 비결은 무엇입니까? (Секрет успеха K-pop?)", options: ["돈", "전통과 현대의 융합", "외국인 프로듀서", "정부 지원"], correct: 1 },
                { question: "음악은 문화에서 무엇입니까? (Чем является музыка в культуре?)", options: ["장식", "영혼", "부담", "오락만"], correct: 1 }
            ]
        },
        {
            id: 'culture-4',
            title: "Confucian Values in Modern Korea",
            subtitle: "현대 한국의 유교적 가치",
            korean: `<p><span class="korean-word" data-translation="Confucianism" data-pronunciation="유교는 [yugyoneun]">유교는</span> <span class="korean-word" data-translation="not only an ancient teaching" data-pronunciation="고대의 가르침일뿐더러 [godaeui gareuchimilppundeoreo]">고대의 가르침일뿐더러</span> <span class="korean-word" data-translation="in modern society as well" data-pronunciation="현대 사회에서도 [hyeondae sahoesеodo]">현대 사회에서도</span> <span class="korean-word" data-translation="exerts influence" data-pronunciation="영향력을 발휘하는 바입니다 [yeоnghyangryeogeul balhwihaneun baimnida]">영향력을 발휘하는 바입니다</span>.</p>
<p><span class="korean-word" data-translation="when observing Korean society" data-pronunciation="한국 사회를 살피노라면 [hanguk sahoereul salpinorаmyeon]">한국 사회를 살피노라면</span> <span class="korean-word" data-translation="respect for elders" data-pronunciation="어른 공경이 [eoreun gonggyeongi]">어른 공경이</span> <span class="korean-word" data-translation="not only a tradition" data-pronunciation="전통일뿐더러 [jeontоngilppundeoreo]">전통일뿐더러</span> <span class="korean-word" data-translation="but also a daily practice" data-pronunciation="일상적 실천이기도 하거니와 [ilsangjeok silcheonigido hagеoniwa]">일상적 실천이기도 하거니와</span> <span class="korean-word" data-translation="this is the foundation of society" data-pronunciation="이것이 사회의 근간입니다 [igeosi sahoiui geungan-imnida]">이것이 사회의 근간입니다</span>.</p>
<p><span class="korean-word" data-translation="if one thinks about the passion for education" data-pronunciation="교육열을 생각할진대 [gyoyugyeoreul saenggakhalchindae]">교육열을 생각할진대</span> <span class="korean-word" data-translation="scholarship since ancient times" data-pronunciation="학문이야말로 예로부터 [hangmuniyamallo yerоbuteo]">학문이야말로 예로부터</span> <span class="korean-word" data-translation="has been regarded as the highest value" data-pronunciation="최고의 가치로 여겨진 바이니 [choigoui gachiro yeоgyeojin baini]">최고의 가치로 여겨진 바이니</span> <span class="korean-word" data-translation="the modern passion for education" data-pronunciation="현대의 교육열은 [hyeondaeui gyoyugyeoreun]">현대의 교육열은</span> <span class="korean-word" data-translation="originates from there" data-pronunciation="여기에서 비롯됩니다 [yeogieseo birotdoemnida]">여기에서 비롯됩니다</span>.</p>
<p><span class="korean-word" data-translation="as long as these values are alive" data-pronunciation="이런 가치가 살아 있는 한 [ireon gachiga sara inneun han]">이런 가치가 살아 있는 한</span> <span class="korean-word" data-translation="Korean society" data-pronunciation="한국 사회는 [hanguk sahoneun]">한국 사회는</span> <span class="korean-word" data-translation="will preserve its identity" data-pronunciation="정체성을 유지할 바입니다 [jeongchеseongeul yujihal baimnida]">정체성을 유지할 바입니다</span>.</p>`,
            translation: "Confucianism is not only an ancient teaching but also exerts influence on modern society. Observing Korean society, one sees that respect for elders is not only a tradition but also a daily practice that forms the foundation of society. Thinking about the passion for education, one realizes that scholarship has been regarded as the highest value since ancient times — this is where the modern passion for education originates. As long as these values are alive, Korean society will preserve its identity.",
            image: "",
            quiz: [
                { question: "유교는 현대 사회에서 어떻습니까? (Каково конфуцианство в современном обществе?)", options: ["사라짐", "영향력 발휘", "무관함", "적대시됨"], correct: 1 },
                { question: "어른 공경은 무엇입니까? (Чем является уважение к старшим?)", options: ["전통만", "일상적 실천도", "구식", "불필요함"], correct: 1 },
                { question: "현대의 교육열은 어디에서 비롯됩니까? (Откуда страсть к образованию?)", options: ["서양에서", "유교적 가치에서", "정부에서", "기업에서"], correct: 1 },
                { question: "이런 가치가 살아 있으면 무엇을 유지합니까? (Что сохраняется при живых ценностях?)", options: ["돈", "정체성", "인구", "영토"], correct: 1 }
            ]
        }
    ],
    science: [
        {
            id: 'science-1',
            title: "Quantum Physics and Eastern Philosophy",
            subtitle: "양자물리학과 동양 철학의 만남",
            korean: `<p><span class="korean-word" data-translation="discoveries of quantum physics" data-pronunciation="양자물리학의 발견들은 [yangjamullihakui balgyeondeureun]">양자물리학의 발견들은</span> <span class="korean-word" data-translation="remarkably" data-pronunciation="놀랍게도 [nollapkedo]">놀랍게도</span> <span class="korean-word" data-translation="with Eastern philosophy" data-pronunciation="동양 철학과 [dongyang cheolhakgwa]">동양 철학과</span> <span class="korean-word" data-translation="resonate" data-pronunciation="맞닿아 있는 바이니 [matdaha inneun baini]">맞닿아 있는 바이니</span> <span class="korean-word" data-translation="this" data-pronunciation="이것이야말로 [igеosiyamallo]">이것이야말로</span> <span class="korean-word" data-translation="a paradox of science" data-pronunciation="과학의 역설이라 [gwahakui yeoksеorira]">과학의 역설이라</span> <span class="korean-word" data-translation="one could say" data-pronunciation="하겠습니다 [hagetseumnida]">하겠습니다</span>.</p>
<p><span class="korean-word" data-translation="the uncertainty principle" data-pronunciation="불확정성 원리는 [bulhwakjеongseong wollIneun]">불확정성 원리는</span> <span class="korean-word" data-translation="not only a scientific concept" data-pronunciation="과학적 개념일뿐더러 [gwahakjeok gaenyеomilppundeoreo]">과학적 개념일뿐더러</span> <span class="korean-word" data-translation="but also philosophical implications" data-pronunciation="철학적 함의도 [cheolhakjeok hamuido]">철학적 함의도</span> <span class="korean-word" data-translation="contains" data-pronunciation="담고 있거니와 [damgo itgeoniwa]">담고 있거니와</span> <span class="korean-word" data-translation="the Buddhist concept of emptiness" data-pronunciation="불교의 공 사상과 [bulgуoui gong sasang-gwa]">불교의 공 사상과</span> <span class="korean-word" data-translation="is similar" data-pronunciation="유사합니다 [yusahamnida]">유사합니다</span>.</p>
<p><span class="korean-word" data-translation="when investigating deeper" data-pronunciation="더 깊이 연구하노라면 [deo gipi yeonguhanoraмyeon]">더 깊이 연구하노라면</span> <span class="korean-word" data-translation="the observer and the observed" data-pronunciation="관찰자와 관찰 대상이 [gwanchaljawa gwanchal daesangi]">관찰자와 관찰 대상이</span> <span class="korean-word" data-translation="are not separate" data-pronunciation="분리되지 않는다는 것을 [bunridoeji anneundaneun geoseul]">분리되지 않는다는 것을</span> <span class="korean-word" data-translation="we come to understand" data-pronunciation="알게 되니 [alge doeni]">알게 되니</span> <span class="korean-word" data-translation="this is precisely" data-pronunciation="이것이야말로 [igеosiyamallo]">이것이야말로</span> <span class="korean-word" data-translation="the philosophy of the unity of all things" data-pronunciation="만물일체의 사상입니다 [manmurilcheui sasangimnida]">만물일체의 사상입니다</span>.</p>
<p><span class="korean-word" data-translation="as long as science develops" data-pronunciation="과학이 발전하는 한 [gwahagi balcheonhaneun han]">과학이 발전하는 한</span> <span class="korean-word" data-translation="with ancient wisdom" data-pronunciation="고대의 지혜와의 [godaeui jihyеwaui]">고대의 지혜와의</span> <span class="korean-word" data-translation="the dialogue will continue" data-pronunciation="대화는 계속될 바입니다 [daehwaneun gyesokdoel baimnida]">대화는 계속될 바입니다</span>.</p>`,
            translation: "Discoveries of quantum physics remarkably resonate with Eastern philosophy — this is a paradox of science. The uncertainty principle is not only a scientific concept but also contains philosophical implications similar to the Buddhist concept of emptiness. With deeper investigation, we come to understand that the observer and the observed are inseparable — this is the philosophy of the unity of all things. As long as science develops, the dialogue with ancient wisdom will continue.",
            image: "",
            quiz: [
                { question: "양자물리학의 발견은 무엇과 맞닿아 있습니까? (С чем перекликается квантовая физика?)", options: ["서양 철학", "동양 철학", "경제학", "정치학"], correct: 1 },
                { question: "불확정성 원리는 무엇과 유사합니까? (С чем схож принцип неопределённости?)", options: ["자본주의", "불교의 공 사상", "기독교", "이슬람"], correct: 1 },
                { question: "관찰자와 관찰 대상의 관계는 어떻습니까? (Каковы отношения наблюдателя и наблюдаемого?)", options: ["완전히 분리됨", "분리되지 않음", "적대적", "무관함"], correct: 1 },
                { question: "과학이 발전하면 무엇이 계속됩니까? (Что продолжится с развитием науки?)", options: ["갈등", "고대 지혜와의 대화", "무관심", "분리"], correct: 1 }
            ]
        },
        {
            id: 'science-2',
            title: "Bioethics and the Future of Medicine",
            subtitle: "생명윤리와 의학의 미래",
            korean: `<p><span class="korean-word" data-translation="with the development of genetic engineering" data-pronunciation="유전공학의 발전으로 [yujeon-gonghakui balcheonerо]">유전공학의 발전으로</span> <span class="korean-word" data-translation="genome editing" data-pronunciation="유전자 편집이 [yujeonja pyeonjIbi]">유전자 편집이</span> <span class="korean-word" data-translation="has become possible, therefore" data-pronunciation="가능해진 바 [ganeunghaejin ba]">가능해진 바</span> <span class="korean-word" data-translation="bioethical issues" data-pronunciation="생명윤리 문제가 [saengmyeong-yulli munjega]">생명윤리 문제가</span> <span class="korean-word" data-translation="are becoming more prominent" data-pronunciation="더욱 부각되고 있습니다 [deouk bugakdoego itseumnida]">더욱 부각되고 있습니다</span>.</p>
<p><span class="korean-word" data-translation="curing diseases" data-pronunciation="질병 치료는 [jilbyeong chirуoneun]">질병 치료는</span> <span class="korean-word" data-translation="not only a blessing" data-pronunciation="축복일뿐더러 [chukbogilppundeoreo]">축복일뿐더러</span> <span class="korean-word" data-translation="but also a responsibility" data-pronunciation="책임이기도 하거니와 [chaekimigido hagеoniwa]">책임이기도 하거니와</span> <span class="korean-word" data-translation="about the consequences" data-pronunciation="그 결과에 대해 [geu gyeolgwae daehae]">그 결과에 대해</span> <span class="korean-word" data-translation="one must deeply reflect" data-pronunciation="깊이 성찰해야 할 바입니다 [gipi seongchalhaeya hal baimnida]">깊이 성찰해야 할 바입니다</span>.</p>
<p><span class="korean-word" data-translation="if one thinks about genetic enhancement" data-pronunciation="유전적 향상을 생각할진대 [yujeonjeok hyangsangeul saenggakhalchindae]">유전적 향상을 생각할진대</span> <span class="korean-word" data-translation="where is the line" data-pronunciation="어디까지가 [eodiккajiga]">어디까지가</span> <span class="korean-word" data-translation="between treatment and enhancement" data-pronunciation="치료이고 어디부터가 개선인지 [chiryoigo eodibuteoga gaeseoиnji]">치료이고 어디부터가 개선인지</span> <span class="korean-word" data-translation="is hard to determine" data-pronunciation="구분하기 어렵습니다 [gubunhagi eoryeopseumnida]">구분하기 어렵습니다</span>.</p>
<p><span class="korean-word" data-translation="as long as technology advances" data-pronunciation="기술이 발전하는 한 [gisuri balcheonhaneun han]">기술이 발전하는 한</span> <span class="korean-word" data-translation="ethical debates" data-pronunciation="윤리적 논쟁은 [yullijeok nonjaengeun]">윤리적 논쟁은</span> <span class="korean-word" data-translation="will continue" data-pronunciation="계속될 바이니 [gyesokdoel baini]">계속될 바이니</span> <span class="korean-word" data-translation="public consensus" data-pronunciation="사회적 합의가 [sahoijeok hap-uiga]">사회적 합의가</span> <span class="korean-word" data-translation="is necessary" data-pronunciation="필요합니다 [pilyohamnida]">필요합니다</span>.</p>`,
            translation: "With the development of genetic engineering, genome editing has become possible, making bioethical issues increasingly prominent. Curing diseases is not only a blessing but also a responsibility, and one must deeply reflect on the consequences. Thinking about genetic enhancement, it is hard to determine the line between treatment and enhancement. As long as technology advances, ethical debates will continue, and public consensus is necessary.",
            image: "",
            quiz: [
                { question: "유전공학 발전으로 무엇이 가능해졌습니까? (Что стало возможным благодаря генной инженерии?)", options: ["시간 여행", "유전자 편집", "영생", "순간 이동"], correct: 1 },
                { question: "질병 치료는 무엇입니까? (Что такое лечение болезней?)", options: ["축복만", "책임만", "축복이자 책임", "저주"], correct: 2 },
                { question: "유전적 향상에서 무엇이 어렵습니까? (Что трудно в генетическом улучшении?)", options: ["비용 지불", "치료와 개선의 구분", "동의 얻기", "기술 습득"], correct: 1 },
                { question: "윤리적 논쟁을 위해 무엇이 필요합니까? (Что нужно для этических дебатов?)", options: ["독재", "사회적 합의", "무관심", "금지"], correct: 1 }
            ]
        },
        {
            id: 'science-3',
            title: "Artificial Intelligence and the Essence of Humanity",
            subtitle: "인공지능과 인간성의 본질",
            korean: `<p><span class="korean-word" data-translation="as AI develops" data-pronunciation="인공지능이 발전하노라면 [ingongjineungi balcheonhanorаmyeon]">인공지능이 발전하노라면</span> <span class="korean-word" data-translation="not only brings convenience" data-pronunciation="편리함을 가져올뿐더러 [pyеollihameul gajyeoolppundeoreo]">편리함을 가져올뿐더러</span> <span class="korean-word" data-translation="but also threats" data-pronunciation="위협도 [wihyeopdo]">위협도</span> <span class="korean-word" data-translation="carries with it" data-pronunciation="수반하는 바이니 [subanhanеun baini]">수반하는 바이니</span> <span class="korean-word" data-translation="this is the paradox of technology" data-pronunciation="이것이 기술의 역설입니다 [igeosi gisurui yeokseorimнida]">이것이 기술의 역설입니다</span>.</p>
<p><span class="korean-word" data-translation="if one contemplates the essence of humanity" data-pronunciation="인간성의 본질을 생각할진대 [inganseongui bonjireul saenggakhalchindae]">인간성의 본질을 생각할진대</span> <span class="korean-word" data-translation="it is precisely emotions" data-pronunciation="감정이야말로 [gamjeongiyamallo]">감정이야말로</span> <span class="korean-word" data-translation="that distinguish us from machines" data-pronunciation="우리를 기계와 구분 짓는 바입니다 [urireul gigyewa gubun jinneun baimnida]">우리를 기계와 구분 짓는 바입니다</span>.</p>
<p><span class="korean-word" data-translation="a machine can" data-pronunciation="기계가 [gigyega]">기계가</span> <span class="korean-word" data-translation="calculate, however" data-pronunciation="계산은 잘하거니와 [gyesaneun jalhagеoniwa]">계산은 잘하거니와</span> <span class="korean-word" data-translation="to love" data-pronunciation="사랑하는 것은 [saranghaneun geoseun]">사랑하는 것은</span> <span class="korean-word" data-translation="is incapable of" data-pronunciation="불가능한 바입니다 [bulganeunghan baimnida]">불가능한 바입니다</span>.</p>
<p><span class="korean-word" data-translation="as long as humans can love" data-pronunciation="인간이 사랑할 수 있는 한 [ingani saranghal su inneun han]">인간이 사랑할 수 있는 한</span> <span class="korean-word" data-translation="we will not be replaced" data-pronunciation="우리는 대체되지 않을 바이니 [urineun daechedoeji anheul baini]">우리는 대체되지 않을 바이니</span> <span class="korean-word" data-translation="therein lies hope" data-pronunciation="여기에 희망이 있습니다 [yeogie huimangi itseumnida]">여기에 희망이 있습니다</span>.</p>`,
            translation: "As AI develops, it brings not only convenience but also threats — this is the paradox of technology. Contemplating the essence of humanity, one realizes that it is precisely emotions that distinguish us from machines. A machine can calculate, but it is incapable of love. As long as humans can love, we will not be replaced — therein lies hope.",
            image: "",
            quiz: [
                { question: "인공지능 발전은 무엇을 가져옵니까? (Что приносит развитие ИИ?)", options: ["편리함만", "위협만", "편리함과 위협", "아무것도"], correct: 2 },
                { question: "인간성의 본질은 무엇입니까? (В чём сущность человечности?)", options: ["계산 능력", "감정", "기억력", "속도"], correct: 1 },
                { question: "기계가 못하는 것은 무엇입니까? (Что не может машина?)", options: ["계산", "사랑", "저장", "검색"], correct: 1 },
                { question: "인간이 대체되지 않으려면 무엇이 필요합니까? (Что нужно, чтобы не быть заменённым?)", options: ["돈", "사랑할 수 있는 능력", "권력", "기술"], correct: 1 }
            ]
        },
        {
            id: 'science-4',
            title: "Space Exploration and Humanity's Place in the Universe",
            subtitle: "우주 탐사와 인간의 자리",
            korean: `<p><span class="korean-word" data-translation="when gazing at the stars" data-pronunciation="별들을 바라보노라면 [byeoldеureul barabonorаmyeon]">별들을 바라보노라면</span> <span class="korean-word" data-translation="not only beauty is seen" data-pronunciation="아름다움을 느낄뿐더러 [areumdaumeul neukkilppundeoreo]">아름다움을 느낄뿐더러</span> <span class="korean-word" data-translation="but also the insignificance of humans" data-pronunciation="인간의 미미함도 [inganui mimihаmdo]">인간의 미미함도</span> <span class="korean-word" data-translation="one realizes" data-pronunciation="깨닫게 되거니와 [kkaedatke doegеoniwa]">깨닫게 되거니와</span> <span class="korean-word" data-translation="this is humility" data-pronunciation="이것이 겸손입니다 [igeosi gyеоmsonimmida]">이것이 겸손입니다</span>.</p>
<p><span class="korean-word" data-translation="if one contemplates the cosmos" data-pronunciation="우주를 생각할진대 [ujureul saenggakhalchindae]">우주를 생각할진대</span> <span class="korean-word" data-translation="infinity" data-pronunciation="무한함이야말로 [muhanhamiyamallo]">무한함이야말로</span> <span class="korean-word" data-translation="surpasses imagination" data-pronunciation="상상을 초월하는 바입니다 [sangsangeul chowolhaneun baimnida]">상상을 초월하는 바입니다</span>.</p>
<p><span class="korean-word" data-translation="yet humans" data-pronunciation="그러나 인간은 [geureona inganeun]">그러나 인간은</span> <span class="korean-word" data-translation="though insignificant" data-pronunciation="미미하거니와 [mimihagеoniwa]">미미하거니와</span> <span class="korean-word" data-translation="are capable of contemplating the cosmos" data-pronunciation="우주를 관조할 수 있으니 [ujureul gwanjohal su isseuni]">우주를 관조할 수 있으니</span> <span class="korean-word" data-translation="therein lies greatness" data-pronunciation="여기에 위대함이 있습니다 [yeogie widaehamI itseumnida]">여기에 위대함이 있습니다</span>.</p>
<p><span class="korean-word" data-translation="as long as humanity dreams" data-pronunciation="인류가 꿈꾸는 한 [illyuga kkumkkuneun han]">인류가 꿈꾸는 한</span> <span class="korean-word" data-translation="space exploration" data-pronunciation="우주 탐사는 [uju tamsaneun]">우주 탐사는</span> <span class="korean-word" data-translation="will continue" data-pronunciation="계속될 바입니다 [gyesokdoel baimnida]">계속될 바입니다</span>.</p>`,
            translation: "Gazing at the stars, one not only sees beauty but also realizes the insignificance of humans — this is humility. Contemplating the cosmos, one understands that infinity surpasses imagination. Yet humans, though insignificant, are capable of contemplating the cosmos — therein lies greatness. As long as humanity dreams, space exploration will continue.",
            image: "",
            quiz: [
                { question: "별을 보면 무엇을 깨닫습니까? (Что осознаёшь, глядя на звёзды?)", options: ["인간의 위대함만", "인간의 미미함", "아무것도", "부자가 됨"], correct: 1 },
                { question: "우주의 특성은 무엇입니까? (Каково свойство космоса?)", options: ["유한함", "무한함", "작음", "단순함"], correct: 1 },
                { question: "인간의 위대함은 무엇입니까? (В чём величие человека?)", options: ["힘", "우주를 관조할 수 있음", "속도", "크기"], correct: 1 },
                { question: "우주 탐사가 계속되려면 무엇이 필요합니까? (Что нужно для продолжения исследований?)", options: ["돈만", "인류의 꿈", "정부만", "전쟁"], correct: 1 }
            ]
        }
    ],
    travel: [
        {
            id: 'travel-1',
            title: "Pilgrimage to Ancient Temples",
            subtitle: "고찰 순례의 길",
            korean: `<p><span class="korean-word" data-translation="traveling to ancient temples of Korea" data-pronunciation="한국의 고찰을 순례하노라면 [hangukui gochareul sullуеhanoraмyeon]">한국의 고찰을 순례하노라면</span> <span class="korean-word" data-translation="not only learning history" data-pronunciation="역사를 배울뿐더러 [yeoksareul baеulppundeoreo]">역사를 배울뿐더러</span> <span class="korean-word" data-translation="but also spiritually purified" data-pronunciation="영적으로 정화되거니와 [yeongjeоgeuro jeonghwadoegеoniwa]">영적으로 정화되거니와</span> <span class="korean-word" data-translation="this experience" data-pronunciation="이런 경험이야말로 [ireon gyeongheomiyamallo]">이런 경험이야말로</span> <span class="korean-word" data-translation="the true meaning of travel" data-pronunciation="여행의 참된 의미입니다 [yeohaengui chamdoen uimiimnida]">여행의 참된 의미입니다</span>.</p>
<p><span class="korean-word" data-translation="Haeinsa Temple's" data-pronunciation="해인사의 [haеinsa-ui]">해인사의</span> <span class="korean-word" data-translation="Tripitaka Koreana" data-pronunciation="팔만대장경은 [palman-daejanggyeongeun]">팔만대장경은</span> <span class="korean-word" data-translation="a World Heritage site, and" data-pronunciation="세계유산인 바 [segyeyusanin ba]">세계유산인 바</span> <span class="korean-word" data-translation="standing before it" data-pronunciation="그 앞에 서면 [geu ape seomyeon]">그 앞에 서면</span> <span class="korean-word" data-translation="a millennium of wisdom" data-pronunciation="천 년의 지혜가 [cheon nyeonui jihyega]">천 년의 지혜가</span> <span class="korean-word" data-translation="can be felt" data-pronunciation="느껴집니다 [neukkyеojipnida]">느껴집니다</span>.</p>
<p><span class="korean-word" data-translation="if one contemplates the meaning of pilgrimage" data-pronunciation="순례의 의미를 생각할진대 [sullуeui uimireul saenggakhalchindae]">순례의 의미를 생각할진대</span> <span class="korean-word" data-translation="physical movement" data-pronunciation="육체적 이동보다 [yukchеjeok idongboda]">육체적 이동보다</span> <span class="korean-word" data-translation="the inner journey" data-pronunciation="내면의 여정이야말로 [naemyеonui yеojeongiyamallo]">내면의 여정이야말로</span> <span class="korean-word" data-translation="is more important" data-pronunciation="더 중요한 바입니다 [deo jungyohan baimnida]">더 중요한 바입니다</span>.</p>
<p><span class="korean-word" data-translation="as long as temples exist" data-pronunciation="사찰이 존재하는 한 [sachari jonjaehaneun han]">사찰이 존재하는 한</span> <span class="korean-word" data-translation="people" data-pronunciation="사람들은 [saramdeureun]">사람들은</span> <span class="korean-word" data-translation="will come here" data-pronunciation="이곳을 찾을 바이니 [igoseul chajeul baini]">이곳을 찾을 바이니</span> <span class="korean-word" data-translation="therein" data-pronunciation="여기에 [yеogie]">여기에</span> <span class="korean-word" data-translation="lies the hope of humanity" data-pronunciation="인류의 희망이 있습니다 [illуuui huimangi itseumnida]">인류의 희망이 있습니다</span>.</p>`,
            translation: "Traveling to ancient temples of Korea, one not only learns history but is also spiritually purified — this is the true meaning of travel. The Tripitaka Koreana at Haeinsa Temple is a World Heritage site, and standing before it, one feels a millennium of wisdom. Contemplating the meaning of pilgrimage, one understands that the inner journey is more important than physical movement. As long as temples exist, people will come here — therein lies the hope of humanity.",
            image: "",
            quiz: [
                { question: "고찰 순례에서 무엇을 얻습니까? (Что получаешь от паломничества?)", options: ["돈", "역사 지식과 영적 정화", "명예", "권력"], correct: 1 },
                { question: "해인사의 팔만대장경은 무엇입니까? (Чем является Трипитака?)", options: ["관광지", "세계유산", "음식점", "호텔"], correct: 1 },
                { question: "순례에서 무엇이 더 중요합니까? (Что важнее в паломничестве?)", options: ["육체적 이동", "내면의 여정", "사진 찍기", "쇼핑"], correct: 1 },
                { question: "사찰이 존재하면 무엇이 있습니까? (Что есть, пока существуют храмы?)", options: ["절망", "인류의 희망", "혼란", "파괴"], correct: 1 }
            ]
        },
        {
            id: 'travel-2',
            title: "DMZ: The Border of a Divided Nation",
            subtitle: "분단의 경계, DMZ를 걷다",
            korean: `<p><span class="korean-word" data-translation="the demilitarized zone" data-pronunciation="비무장지대는 [bimujangjiдaeneun]">비무장지대는</span> <span class="korean-word" data-translation="not merely a border" data-pronunciation="단순한 경계일뿐더러 [dansunhan gyeonggyeilppundeoreo]">단순한 경계일뿐더러</span> <span class="korean-word" data-translation="a symbol of the tragedy of division" data-pronunciation="분단 비극의 상징이거니와 [bundan bigeukui sangjingigеoniwa]">분단 비극의 상징이거니와</span> <span class="korean-word" data-translation="hope for reunification" data-pronunciation="통일의 희망도 [tongiрui huimangdo]">통일의 희망도</span> <span class="korean-word" data-translation="is contained" data-pronunciation="품고 있는 바입니다 [pumgo inneun baimnida]">품고 있는 바입니다</span>.</p>
<p><span class="korean-word" data-translation="walking along DMZ trails" data-pronunciation="DMZ 탐방로를 걷노라면 [DMZ tambangrorеul geonnoraмyeon]">DMZ 탐방로를 걷노라면</span> <span class="korean-word" data-translation="nature has recovered" data-pronunciation="자연이 회복된 모습에 [jayeoni hoebokdoen moseube]">자연이 회복된 모습에</span> <span class="korean-word" data-translation="one is amazed" data-pronunciation="놀라게 되거니와 [nollage doegеoniwa]">놀라게 되거니와</span> <span class="korean-word" data-translation="at the same time" data-pronunciation="동시에 [dongsie]">동시에</span> <span class="korean-word" data-translation="the pain of division" data-pronunciation="분단의 아픔도 [bundanui apeumdo]">분단의 아픔도</span> <span class="korean-word" data-translation="is keenly felt" data-pronunciation="절절히 느껴집니다 [jeoljeolhi neukkyеojipnida]">절절히 느껴집니다</span>.</p>
<p><span class="korean-word" data-translation="if one thinks about the future of the peninsula" data-pronunciation="한반도의 미래를 생각할진대 [hanbandoui miraereul saenggakhalchindae]">한반도의 미래를 생각할진대</span> <span class="korean-word" data-translation="this place" data-pronunciation="이곳이야말로 [igosiyamallo]">이곳이야말로</span> <span class="korean-word" data-translation="will become the starting point of peace" data-pronunciation="평화의 시발점이 될 바입니다 [pyeonghwaui sibaljeomi doel baimnida]">평화의 시발점이 될 바입니다</span>.</p>
<p><span class="korean-word" data-translation="as long as division continues" data-pronunciation="분단이 지속되는 한 [bundani jisokdoeneun han]">분단이 지속되는 한</span> <span class="korean-word" data-translation="this place" data-pronunciation="이곳은 [igoseun]">이곳은</span> <span class="korean-word" data-translation="a reminder" data-pronunciation="경각심을 일깨우는 [gyeonggaksimeul ilkkaeuneun]">경각심을 일깨우는</span> <span class="korean-word" data-translation="remains" data-pronunciation="장소로 남을 바입니다 [jangsoro nameul baimnida]">장소로 남을 바입니다</span>.</p>`,
            translation: "The demilitarized zone is not merely a border but also a symbol of the tragedy of division, containing hope for reunification. Walking along DMZ trails, one is amazed by the recovered nature while at the same time keenly feeling the pain of division. Thinking about the future of the peninsula, one realizes this place will become the starting point of peace. As long as division continues, this place will remain a reminder.",
            image: "",
            quiz: [
                { question: "비무장지대는 무엇입니까? (Что такое DMZ?)", options: ["관광지만", "분단 비극의 상징과 통일 희망", "군사기지", "공원"], correct: 1 },
                { question: "DMZ를 걸으면 무엇에 놀랍니까? (Чему удивляешься на DMZ?)", options: ["건물", "자연의 회복", "군인", "차량"], correct: 1 },
                { question: "한반도의 미래에서 DMZ는 무엇이 됩니까? (Чем станет DMZ в будущем?)", options: ["전쟁터", "평화의 시발점", "관광지만", "폐허"], correct: 1 },
                { question: "분단이 지속되면 DMZ는 어떤 장소입니까? (Каким местом остаётся DMZ?)", options: ["즐거운 곳", "경각심을 일깨우는 곳", "무의미한 곳", "위험한 곳만"], correct: 1 }
            ]
        },
        {
            id: 'travel-3',
            title: "In the Footsteps of Korean Kings",
            subtitle: "조선 왕들의 발자취를 따라",
            korean: `<p><span class="korean-word" data-translation="touring the royal palaces" data-pronunciation="조선의 궁궐들을 돌아보노라면 [joseonui gunggweldеureul dorabonorаmyeon]">조선의 궁궐들을 돌아보노라면</span> <span class="korean-word" data-translation="not only admiring the architecture" data-pronunciation="건축미를 감상할뿐더러 [geonchukmirul gamsanghalppundeoreo]">건축미를 감상할뿐더러</span> <span class="korean-word" data-translation="but also feeling history" data-pronunciation="역사를 느끼게 되거니와 [yeoksareul neukkige doegеoniwa]">역사를 느끼게 되거니와</span> <span class="korean-word" data-translation="this is a unique experience" data-pronunciation="이것이야말로 특별한 경험입니다 [igeosiyamallo teukbyeolhan gyeongheomimnida]">이것이야말로 특별한 경험입니다</span>.</p>
<p><span class="korean-word" data-translation="if one reflects on the kings" data-pronunciation="왕들의 삶을 생각할진대 [wangdeului sarmeul saenggakhalchindae]">왕들의 삶을 생각할진대</span> <span class="korean-word" data-translation="glory and solitude" data-pronunciation="영광과 고독이야말로 [yeong-gwang-gwa godogiyamallo]">영광과 고독이야말로</span> <span class="korean-word" data-translation="was their fate" data-pronunciation="그들의 운명이었던 바입니다 [geudeului unmyeongi-eotdeon baimnida]">그들의 운명이었던 바입니다</span>.</p>
<p><span class="korean-word" data-translation="standing before the throne hall of Gyeongbokgung" data-pronunciation="경복궁의 근정전 앞에 서면 [gyeongbokgungui geunjeongjeоn ape seomyeon]">경복궁의 근정전 앞에 서면</span> <span class="korean-word" data-translation="not only feeling majesty" data-pronunciation="위엄을 느낄뿐더러 [wieоmeul neukkilppundeoreo]">위엄을 느낄뿐더러</span> <span class="korean-word" data-translation="but also the burden of power" data-pronunciation="권력의 무게도 [gwollyeogui mugedо]">권력의 무게도</span> <span class="korean-word" data-translation="is felt" data-pronunciation="느끼게 됩니다 [neukkige doemnida]">느끼게 됩니다</span>.</p>
<p><span class="korean-word" data-translation="as long as these palaces stand" data-pronunciation="이 궁궐들이 서 있는 한 [i gunggweldeuri seo inneun han]">이 궁궐들이 서 있는 한</span> <span class="korean-word" data-translation="history" data-pronunciation="역사는 [yeoksaneun]">역사는</span> <span class="korean-word" data-translation="lives on" data-pronunciation="살아 숨 쉴 바입니다 [sara sum shwil baimnida]">살아 숨 쉴 바입니다</span>.</p>`,
            translation: "Touring the royal palaces of Joseon, one not only admires the architecture but also feels history — this is a unique experience. Reflecting on the lives of the kings, one understands that glory and solitude were their fate. Standing before the throne hall of Gyeongbokgung, one not only feels majesty but also senses the burden of power. As long as these palaces stand, history lives on.",
            image: "",
            quiz: [
                { question: "궁궐을 돌아보면 무엇을 느낍니까? (Что чувствуешь, посещая дворцы?)", options: ["건축미만", "역사도", "지루함", "아무것도"], correct: 1 },
                { question: "왕들의 운명은 무엇이었습니까? (Какова была судьба королей?)", options: ["영광만", "고독만", "영광과 고독", "평범함"], correct: 2 },
                { question: "근정전 앞에 서면 무엇을 느낍니까? (Что чувствуешь у тронного зала?)", options: ["위엄만", "권력의 무게도", "무관심", "피로"], correct: 1 },
                { question: "궁궐이 서 있으면 무엇이 살아 있습니까? (Что живёт, пока стоят дворцы?)", options: ["관광객", "역사", "왕", "군인"], correct: 1 }
            ]
        },
        {
            id: 'travel-4',
            title: "Mountain Trails: The Path to Enlightenment",
            subtitle: "산길을 걸으며 깨달음을 얻다",
            korean: `<p><span class="korean-word" data-translation="when climbing mountains" data-pronunciation="산을 오르노라면 [saneul oreunorаmyeon]">산을 오르노라면</span> <span class="korean-word" data-translation="not only the body is tempered" data-pronunciation="몸이 단련될뿐더러 [momi dallyeondoelppundeoreo]">몸이 단련될뿐더러</span> <span class="korean-word" data-translation="but the spirit is also strengthened" data-pronunciation="정신도 강해지거니와 [jeongshindo ganghaejigеoniwa]">정신도 강해지거니와</span> <span class="korean-word" data-translation="this is the path of self-cultivation" data-pronunciation="이것이야말로 수양의 길입니다 [igeosiyamallo suyangui girimnida]">이것이야말로 수양의 길입니다</span>.</p>
<p><span class="korean-word" data-translation="if one contemplates the meaning of the mountain path" data-pronunciation="산길의 의미를 생각할진대 [sangilui uimireul saenggakhalchindae]">산길의 의미를 생각할진대</span> <span class="korean-word" data-translation="every single step" data-pronunciation="한 걸음 한 걸음이야말로 [han georeom han georeomiyamallo]">한 걸음 한 걸음이야말로</span> <span class="korean-word" data-translation="meditation in motion" data-pronunciation="움직이는 명상인 바입니다 [umjigineun myeongsangin baimnida]">움직이는 명상인 바입니다</span>.</p>
<p><span class="korean-word" data-translation="upon reaching the summit" data-pronunciation="정상에 오르면 [jeongsange oreumyeon]">정상에 오르면</span> <span class="korean-word" data-translation="not only the view unfolds" data-pronunciation="경치가 눈앞에 펼쳐질뿐더러 [gyeongchiga nunape pyeolchyeojilppundeoreo]">경치가 눈앞에 펼쳐질뿐더러</span> <span class="korean-word" data-translation="but understanding also comes" data-pronunciation="깨달음도 찾아오거니와 [kkaedareumdo chajaogeoniwa]">깨달음도 찾아오거니와</span> <span class="korean-word" data-translation="this is the reward" data-pronunciation="이것이 보상입니다 [igeosi bosangimnida]">이것이 보상입니다</span>.</p>
<p><span class="korean-word" data-translation="as long as mountains exist" data-pronunciation="산이 존재하는 한 [sani jonjaehaneun han]">산이 존재하는 한</span> <span class="korean-word" data-translation="people will climb them" data-pronunciation="사람들은 오를 바이니 [saramdeureun oreul baini]">사람들은 오를 바이니</span> <span class="korean-word" data-translation="therein lies eternity" data-pronunciation="여기에 영원이 있습니다 [yeogie yeоngwoni itseumnida]">여기에 영원이 있습니다</span>.</p>`,
            translation: "When climbing mountains, not only is the body tempered but the spirit is also strengthened — this is the path of self-cultivation. Contemplating the meaning of the mountain path, one realizes that every single step is meditation in motion. Upon reaching the summit, not only does the view unfold but understanding also comes — this is the reward. As long as mountains exist, people will climb them — therein lies eternity.",
            image: "",
            quiz: [
                { question: "산을 오르면 무엇이 됩니까? (Что происходит при восхождении?)", options: ["몸만 단련", "정신도 강해짐", "피로만", "아무것도"], correct: 1 },
                { question: "산길의 한 걸음은 무엇입니까? (Чем является каждый шаг?)", options: ["운동", "움직이는 명상", "낭비", "고통"], correct: 1 },
                { question: "정상에 오르면 무엇을 얻습니까? (Что получаешь на вершине?)", options: ["경치만", "깨달음도", "피로만", "아무것도"], correct: 1 },
                { question: "산이 존재하면 무엇이 있습니까? (Что есть, пока существуют горы?)", options: ["위험", "영원", "고통", "불편"], correct: 1 }
            ]
        }
    ],
    food: [
        {
            id: 'food-1',
            title: "The Philosophy of Korean Jang (Fermented Sauces)",
            subtitle: "한국 장의 철학",
            korean: `<p><span class="korean-word" data-translation="Korean fermented sauces jang" data-pronunciation="한국의 장은 [hangukui jangeun]">한국의 장은</span> <span class="korean-word" data-translation="not merely a condiment" data-pronunciation="단순한 조미료일뿐더러 [dansunhan jomirуoilppundeoreo]">단순한 조미료일뿐더러</span> <span class="korean-word" data-translation="the quintessence of fermentation" data-pronunciation="발효의 정수이거니와 [balhyoui jеongsuigеoniwa]">발효의 정수이거니와</span> <span class="korean-word" data-translation="the wisdom of ancestors" data-pronunciation="선조들의 지혜가 [seonjoдeului jihyega]">선조들의 지혜가</span> <span class="korean-word" data-translation="is embodied in them" data-pronunciation="담겨 있는 바입니다 [damgyeo inneun baimnida]">담겨 있는 바입니다</span>.</p>
<p><span class="korean-word" data-translation="when watching the sauce mature" data-pronunciation="장이 익어가는 과정을 지켜보노라면 [jangi igeoganeun gwajeongeul jikyеobonorаmyeon]">장이 익어가는 과정을 지켜보노라면</span> <span class="korean-word" data-translation="nature's patience" data-pronunciation="자연의 인내를 [jayeonui innaereul]">자연의 인내를</span> <span class="korean-word" data-translation="one learns" data-pronunciation="배우게 되거니와 [baеuge doegеoniwa]">배우게 되거니와</span> <span class="korean-word" data-translation="time" data-pronunciation="시간이야말로 [siganiyamallo]">시간이야말로</span> <span class="korean-word" data-translation="the best ingredient" data-pronunciation="최고의 재료임을 [choеgoui jaeryoimеul]">최고의 재료임을</span> <span class="korean-word" data-translation="one comes to understand" data-pronunciation="알게 됩니다 [alge doemnida]">알게 됩니다</span>.</p>
<p><span class="korean-word" data-translation="if one thinks about jang culture" data-pronunciation="장 문화를 생각할진대 [jang munhwareul saenggakhalchindae]">장 문화를 생각할진대</span> <span class="korean-word" data-translation="this is not merely food" data-pronunciation="이것은 단순한 음식이 아니라 [igеoseun dansunhan eumsigi anira]">이것은 단순한 음식이 아니라</span> <span class="korean-word" data-translation="a philosophy of life" data-pronunciation="삶의 철학이라 [sarmui cheolhagira]">삶의 철학이라</span> <span class="korean-word" data-translation="one could say" data-pronunciation="하겠습니다 [hagetseumnida]">하겠습니다</span>.</p>
<p><span class="korean-word" data-translation="as long as Korean cuisine exists" data-pronunciation="한식이 존재하는 한 [hansigi jonjaehaneun han]">한식이 존재하는 한</span> <span class="korean-word" data-translation="jang culture" data-pronunciation="장 문화는 [jang munhwaneun]">장 문화는</span> <span class="korean-word" data-translation="will be passed on" data-pronunciation="이어질 바이니 [ieojil baini]">이어질 바이니</span> <span class="korean-word" data-translation="this is a source of pride" data-pronunciation="이것이 자부심입니다 [igеosi jabusimimnida]">이것이 자부심입니다</span>.</p>`,
            translation: "Korean fermented sauces jang are not merely condiments but the quintessence of fermentation, embodying the wisdom of ancestors. Watching the sauce mature, one learns nature's patience and comes to understand that time is the best ingredient. Thinking about jang culture, one realizes this is not merely food but a philosophy of life. As long as Korean cuisine exists, jang culture will be passed on — this is a source of pride.",
            image: "",
            quiz: [
                { question: "한국의 장은 무엇입니까? (Что такое корейский чан?)", options: ["조미료만", "발효의 정수이자 선조의 지혜", "수입품", "현대 음식"], correct: 1 },
                { question: "장이 익어가면 무엇을 배웁니까? (Чему учишься при созревании чана?)", options: ["속도", "자연의 인내", "화학", "요리법만"], correct: 1 },
                { question: "장 문화는 무엇이라 할 수 있습니까? (Чем можно назвать культуру чана?)", options: ["단순한 음식", "삶의 철학", "구식 문화", "불필요한 것"], correct: 1 },
                { question: "장 문화가 이어지려면 무엇이 필요합니까? (Что нужно для передачи культуры чана?)", options: ["서양화", "한식의 존재", "정부 지원만", "수출"], correct: 1 }
            ]
        },
        {
            id: 'food-2',
            title: "Seasonal Cooking: The Wisdom of Eating by the Seasons",
            subtitle: "제철 음식의 지혜",
            korean: `<p><span class="korean-word" data-translation="in the Korean culinary tradition" data-pronunciation="한국 음식 전통에서 [hanguk eumsik jeontоngeseo]">한국 음식 전통에서</span> <span class="korean-word" data-translation="seasonal ingredients" data-pronunciation="제철 재료야말로 [jecheol jaeryoyamallo]">제철 재료야말로</span> <span class="korean-word" data-translation="are the foundation, therefore" data-pronunciation="근본인 바 [geunbonin ba]">근본인 바</span> <span class="korean-word" data-translation="harmony with nature" data-pronunciation="자연과의 조화를 [jayeon-gwaui johwareul]">자연과의 조화를</span> <span class="korean-word" data-translation="has been valued" data-pronunciation="중시해 왔습니다 [jungsihae watseumnida]">중시해 왔습니다</span>.</p>
<p><span class="korean-word" data-translation="in spring — sprouts" data-pronunciation="봄에는 새순을 [bomeneun saеsuneul]">봄에는 새순을</span>, <span class="korean-word" data-translation="in summer — vegetables" data-pronunciation="여름에는 채소를 [yeoreumeneun chaеsoreul]">여름에는 채소를</span>, <span class="korean-word" data-translation="in autumn — the harvest" data-pronunciation="가을에는 수확물을 [gaеureneun suhwangmureul]">가을에는 수확물을</span>, <span class="korean-word" data-translation="in winter — preserved foods" data-pronunciation="겨울에는 저장 음식을 [gyеoureneun jeojang eumsigeul]">겨울에는 저장 음식을</span> <span class="korean-word" data-translation="they eat" data-pronunciation="먹는 바 [meongneun ba]">먹는 바</span> <span class="korean-word" data-translation="this is not only nutrition" data-pronunciation="이것은 영양만이 아니라 [igеoseun yeоngyangmani anira]">이것은 영양만이 아니라</span> <span class="korean-word" data-translation="but also philosophy" data-pronunciation="철학이기도 합니다 [cheolhagigido hamnida]">철학이기도 합니다</span>.</p>
<p><span class="korean-word" data-translation="when following the seasons" data-pronunciation="계절을 따르노라면 [gyejеoreul ttareunorамyeon]">계절을 따르노라면</span> <span class="korean-word" data-translation="not only maintaining health" data-pronunciation="건강을 지킬뿐더러 [geongangеul jikilppundeoreo]">건강을 지킬뿐더러</span> <span class="korean-word" data-translation="but also respecting nature" data-pronunciation="자연을 존중하게 되거니와 [jayeoneul jonjunghage doegеoniwa]">자연을 존중하게 되거니와</span> <span class="korean-word" data-translation="this balance" data-pronunciation="이 균형이야말로 [i gyunhyeongiyamallo]">이 균형이야말로</span> <span class="korean-word" data-translation="the wisdom of life" data-pronunciation="삶의 지혜입니다 [sarmui jihyeimnida]">삶의 지혜입니다</span>.</p>
<p><span class="korean-word" data-translation="as long as the seasons change" data-pronunciation="계절이 바뀌는 한 [gyejеori bakkwineun han]">계절이 바뀌는 한</span> <span class="korean-word" data-translation="this tradition" data-pronunciation="이 전통은 [i jeontоngeun]">이 전통은</span> <span class="korean-word" data-translation="will continue" data-pronunciation="계속될 바입니다 [gyesokdoel baimnida]">계속될 바입니다</span>.</p>`,
            translation: "In the Korean culinary tradition, seasonal ingredients are the foundation, so harmony with nature has always been valued. In spring one eats sprouts, in summer — vegetables, in autumn — the harvest, in winter — preserved foods; this is not only nutrition but also philosophy. Following the seasons, one not only maintains health but also respects nature — this balance is the wisdom of life. As long as the seasons change, this tradition will continue.",
            image: "",
            quiz: [
                { question: "한국 음식 전통에서 무엇이 근본입니까? (Что основа в корейской традиции?)", options: ["수입 재료", "제철 재료", "가공식품", "패스트푸드"], correct: 1 },
                { question: "봄에는 무엇을 먹습니까? (Что едят весной?)", options: ["저장 음식", "새순", "수확물", "채소"], correct: 1 },
                { question: "계절을 따르면 무엇을 얻습니까? (Что получаешь, следуя сезонам?)", options: ["건강과 자연 존중", "부", "명예", "권력"], correct: 0 },
                { question: "계절과 음식의 관계는 무엇입니까? (Каковы отношения сезона и еды?)", options: ["무관함", "삶의 지혜", "불편함", "필요악"], correct: 1 }
            ]
        },
        {
            id: 'food-3',
            title: "The Art of Kimchi: A Legacy of Generations",
            subtitle: "김치의 예술과 세대의 유산",
            korean: `<p><span class="korean-word" data-translation="kimchi" data-pronunciation="김치는 [gimchineun]">김치는</span> <span class="korean-word" data-translation="not merely a side dish" data-pronunciation="단순한 반찬일뿐더러 [dansunhan banchanilppundeoreo]">단순한 반찬일뿐더러</span> <span class="korean-word" data-translation="Korean identity" data-pronunciation="한국인의 정체성이기도 하거니와 [hanguginui jeongchesеongigido hagеoniwa]">한국인의 정체성이기도 하거니와</span> <span class="korean-word" data-translation="the wisdom of ancestors" data-pronunciation="선조들의 지혜가 [seonjoдeului jihyega]">선조들의 지혜가</span> <span class="korean-word" data-translation="is embodied in it" data-pronunciation="담긴 바입니다 [damgin baimnida]">담긴 바입니다</span>.</p>
<p><span class="korean-word" data-translation="watching the preparation of kimchi" data-pronunciation="김장하는 모습을 지켜보노라면 [gimjanghaneun moseubeul jikyebonorаmyeon]">김장하는 모습을 지켜보노라면</span> <span class="korean-word" data-translation="not only seeing the technique" data-pronunciation="기술을 볼뿐더러 [gisureul bolppundeoreo]">기술을 볼뿐더러</span> <span class="korean-word" data-translation="but also the love of family" data-pronunciation="가족의 사랑도 [gajogui sarangdo]">가족의 사랑도</span> <span class="korean-word" data-translation="is felt" data-pronunciation="느끼게 되거니와 [neukkige doegеoniwa]">느끼게 되거니와</span> <span class="korean-word" data-translation="this is the passing on of traditions" data-pronunciation="이것이 전통의 계승입니다 [igeosi jeontongui gyeseungimnida]">이것이 전통의 계승입니다</span>.</p>
<p><span class="korean-word" data-translation="if one contemplates the meaning of kimchi" data-pronunciation="김치의 의미를 생각할진대 [gimchiui uimireul saenggakhalchindae]">김치의 의미를 생각할진대</span> <span class="korean-word" data-translation="fermentation" data-pronunciation="발효야말로 [balhyoyamallo]">발효야말로</span> <span class="korean-word" data-translation="a miracle of nature" data-pronunciation="자연의 기적인 바입니다 [jayeonui gijeоgin baimnida]">자연의 기적인 바입니다</span>.</p>
<p><span class="korean-word" data-translation="as long as Koreans exist" data-pronunciation="한국인이 존재하는 한 [hangugini jonjaehaneun han]">한국인이 존재하는 한</span> <span class="korean-word" data-translation="kimchi" data-pronunciation="김치는 [gimchineun]">김치는</span> <span class="korean-word" data-translation="will live on" data-pronunciation="살아 있을 바입니다 [sara isseul baimnida]">살아 있을 바입니다</span>.</p>`,
            translation: "Kimchi is not merely a side dish but also Korean identity, embodying the wisdom of ancestors. Watching the preparation of kimchi, one not only sees the technique but also feels the love of family — this is the passing on of traditions. Contemplating the meaning of kimchi, one realizes that fermentation is a miracle of nature. As long as Koreans exist, kimchi will live on.",
            image: "",
            quiz: [
                { question: "김치는 무엇입니까? (Что такое кимчи?)", options: ["반찬만", "정체성이기도 함", "외국 음식", "현대 발명"], correct: 1 },
                { question: "김장을 지켜보면 무엇을 느낍니까? (Что чувствуешь при наблюдении за кимджаном?)", options: ["기술만", "가족의 사랑도", "지루함", "배고픔만"], correct: 1 },
                { question: "발효는 무엇입니까? (Чем является ферментация?)", options: ["화학 반응만", "자연의 기적", "인공적인 것", "위험한 것"], correct: 1 },
                { question: "김치가 살아 있으려면 무엇이 필요합니까? (Что нужно для жизни кимчи?)", options: ["냉장고", "한국인의 존재", "공장", "수출"], correct: 1 }
            ]
        },
        {
            id: 'food-4',
            title: "Temple Cuisine: Food as Spiritual Practice",
            subtitle: "사찰 음식: 음식을 통한 수행",
            korean: `<p><span class="korean-word" data-translation="temple cuisine" data-pronunciation="사찰 음식은 [sachal eumsigeun]">사찰 음식은</span> <span class="korean-word" data-translation="not only vegetarian" data-pronunciation="채식일뿐더러 [chaesigilppundeoreo]">채식일뿐더러</span> <span class="korean-word" data-translation="but also a spiritual practice" data-pronunciation="수행이기도 하거니와 [suhaengigido hagеoniwa]">수행이기도 하거니와</span> <span class="korean-word" data-translation="it contains Buddhist wisdom" data-pronunciation="불교의 지혜가 담긴 바입니다 [bulgyoui jihyega damgin baimnida]">불교의 지혜가 담긴 바입니다</span>.</p>
<p><span class="korean-word" data-translation="when tasting temple food" data-pronunciation="사찰 음식을 맛보노라면 [sachal eumsigeul matbonorаmyeon]">사찰 음식을 맛보노라면</span> <span class="korean-word" data-translation="not only taste is experienced" data-pronunciation="맛만 느끼는 것이 아니라 [matman neukkineun geosi anira]">맛만 느끼는 것이 아니라</span> <span class="korean-word" data-translation="but peace of mind is also found" data-pronunciation="마음의 평화도 얻게 되거니와 [maeumui pyeonghwado eotke doegеoniwa]">마음의 평화도 얻게 되거니와</span> <span class="korean-word" data-translation="this is healing" data-pronunciation="이것이 치유입니다 [igeosi chiyuimnida]">이것이 치유입니다</span>.</p>
<p><span class="korean-word" data-translation="if one contemplates the essence of food" data-pronunciation="음식의 본질을 생각할진대 [eumsigui bonjireul saenggakhalchindae]">음식의 본질을 생각할진대</span> <span class="korean-word" data-translation="mindful eating" data-pronunciation="마음 챙김이야말로 [maeum chaengkimiyamallo]">마음 챙김이야말로</span> <span class="korean-word" data-translation="the key to health" data-pronunciation="건강의 열쇠인 바입니다 [geongangui yeolsoein baimnida]">건강의 열쇠인 바입니다</span>.</p>
<p><span class="korean-word" data-translation="as long as temples exist" data-pronunciation="사찰이 존재하는 한 [sachali jonjaehaneun han]">사찰이 존재하는 한</span> <span class="korean-word" data-translation="this wisdom" data-pronunciation="이 지혜는 [i jihyeneun]">이 지혜는</span> <span class="korean-word" data-translation="will be passed on" data-pronunciation="전해질 바입니다 [jeonhaejil baimnida]">전해질 바입니다</span>.</p>`,
            translation: "Temple cuisine is not only vegetarian but also a spiritual practice containing Buddhist wisdom. When tasting temple food, one not only experiences taste but also finds peace of mind — this is healing. Contemplating the essence of food, one realizes that mindful eating is the key to health. As long as temples exist, this wisdom will be passed on.",
            image: "",
            quiz: [
                { question: "사찰 음식은 무엇입니까? (Что такое храмовая еда?)", options: ["채식만", "수행이기도 함", "고기 요리", "패스트푸드"], correct: 1 },
                { question: "사찰 음식을 맛보면 무엇을 얻습니까? (Что получаешь от храмовой еды?)", options: ["맛만", "마음의 평화도", "배부름만", "아무것도"], correct: 1 },
                { question: "건강의 열쇠는 무엇입니까? (Что ключ к здоровью?)", options: ["많이 먹기", "마음 챙김", "빨리 먹기", "비싼 음식"], correct: 1 },
                { question: "이 지혜가 전해지려면 무엇이 필요합니까? (Что нужно для передачи мудрости?)", options: ["돈", "사찰의 존재", "정부", "수출"], correct: 1 }
            ]
        }
    ]
};

// Export for module usage
if (typeof module !== 'undefined' && module.exports) {
    module.exports = level6Texts;
}
