/**
 * Русские названия уроков и словарей для ссылок «Теория по этим темам».
 * 522 страниц. Собрано из <title> самих страниц.
 *
 * Файл сгенерирован tools/lesson-titles.py — правки вносите в сами уроки.
 */
window.lessonTitles = {
 "lesson_01_korea": "🇰🇷 Знакомство с Кореей",
 "lesson_02_alphabet": "🔤 Корейский алфавит 한글",
 "lesson_03_greetings": "Приветствие и знакомство - 인사와 만남",
 "lesson_04_numbers": "🔢 Числа и время",
 "lesson_05_family": "👨‍👩‍👧‍👦 Семья и отношения",
 "lesson_06_grammar": "Грамматика 1: Частицы 이/가 и 은/는 — основа",
 "lesson_07_verb_tenses": "Времена глаголов 현재/과거/미래",
 "lesson_08_politeness": "Формы вежливости 존댓말",
 "lesson_09_negation": "Отрицательные формы 부정문",
 "lesson_100_any_deunji": "Что угодно, когда угодно -(이)든지",
 "lesson_101_becoming_i_ga_doeda": "Становиться кем-то -이/가 되다",
 "lesson_102_nothing_amu_do": "Ничего и никто — 아무 -도",
 "lesson_103_price_jjari_eochi": "Цена и сумма: -짜리 и -어치",
 "lesson_104_consonant_assimilation": "Урок: Пары согласных и ассимиляция — правила чтения",
 "lesson_105_retrospective_deoragoyo": "Личное наблюдение -더라고요 · -던데요",
 "lesson_106_cause_gillae": "Повод для действия -길래",
 "lesson_107_shared_knowledge_janayo": "Общее знание -잖아요",
 "lesson_108_hearsay_damyeonseo": "Слухи и упрёк -다면서요 · -라면서요",
 "lesson_109_verbal_postpositions": "Отглагольные послелоги 대하여 · 위하여 · 통하여",
 "lesson_10_copula": "Связка 이에요/예요",
 "lesson_110_adjective_derivation": "Именные прилагательные -적 и словообразование",
 "lesson_111_probability_beophada": "Правдоподобие -(으)ㄹ 법하다 · -(으)ㄹ 성싶다",
 "lesson_112_situation_madang_cha": "Ситуация -는 마당에 · -는 차에",
 "lesson_113_formal_time_apseo": "Официальное время -기에 앞서 · -는 데 있어",
 "lesson_114_belittling_bulgwahada": "Принижение -에 불과하다 · -느니만 못하다",
 "lesson_115_extreme_geujieopda": "Крайняя степень -기 그지없다 · -기 짝이 없다",
 "lesson_116_literary_eullachimyeon": "Литературные обороты -(으)ㄹ라치면 · -(으)ㄹ세라",
 "lesson_117_state_chae": "Не меняя положения -(으)ㄴ 채(로)",
 "lesson_118_busy_neurago": "Был занят -느라(고)",
 "lesson_119_causative_ge_hada": "Заставить и позволить -게 하다",
 "lesson_11_informal_copula": "Неформальная связка 이야/야",
 "lesson_120_worry_kkabwa": "Как бы не -(으)ㄹ까 봐",
 "lesson_121_past_adnominal_deon": "Прошлое в определении -던 · -았/었던",
 "lesson_122_concession_deorado": "Даже если -더라도",
 "lesson_123_regret_go_malda": "В итоге всё-таки -고 말다",
 "lesson_124_almost_ppeonhada": "Чуть не -(으)ㄹ 뻔하다",
 "lesson_125_no_choice_subakke": "Ничего не остаётся -(으)ㄹ 수밖에 없다",
 "lesson_126_even_jocha_majeo": "Даже и это -조차 · -마저",
 "lesson_127_for_a_chigo": "Для такого-то -치고",
 "lesson_128_approx_time_muryeop": "Около того времени -(으)ㄹ 무렵",
 "lesson_129_supposition_tende": "Наверное же -(으)ㄹ 텐데",
 "lesson_12_formal_copula": "Официальная связка 입니다/습니다",
 "lesson_130_pretend_cheokhada": "Притворяться -는 척하다",
 "lesson_131_regret_geol_geuraetda": "Сожаление -(으)ㄹ 걸 그랬다",
 "lesson_132_degree_jeongdoro": "Степень действия -(으)ㄹ 정도로",
 "lesson_133_only_ppunida": "Только и всего -(으)ㄹ 뿐이다",
 "lesson_13_copula_negation": "Отрицание связок 아니에요/아냐/아닙니다",
 "lesson_14_demonstratives": "Указательные слова 이것/그것/저것",
 "lesson_15_demonstratives_practice": "Глаголы \"иметь\" и \"не иметь\" 있어요/없어요",
 "lesson_16_location_verbs": "Глаголы местонахождения 있어요/없어요",
 "lesson_17_verb_conjugation": "Спряжение глаголов в настоящем времени 아요/어요",
 "lesson_18_informal_verbs": "Просто-личный стиль глаголов 아/어",
 "lesson_19_formal_verbs": "Вежливо-официальный стиль глаголов 습니다/ㅂ니다",
 "lesson_20_accusative_case": "Винительный падеж 을/를",
 "lesson_21_location_ending": "Окончание места действия 에서",
 "lesson_22_direction_ending": "Окончание направления 에",
 "lesson_23_time_marker": "Временной показатель 에",
 "lesson_24_adjective_conjugation": "Склонение прилагательных",
 "lesson_25_hago_conjunction": "Союз \"и\" или предлог \"с\" - 하고",
 "lesson_26_conjunction_particles": "Соединение существительных 란/이란, 과/와",
 "lesson_27_past_tense": "Прошедшее время глаголов и прилагательных",
 "lesson_28_conjunction_go": "Соединительное окончание -고",
 "lesson_29_sequence_go": "Последовательность действий с -고",
 "lesson_30_future_tense": "Будущее время 을/ㄹ 거예요",
 "lesson_32_dative_case": "Дательный падеж 에게/한테/께",
 "lesson_33_possessive_case": "Притяжательный падеж 의",
 "lesson_34_want_desire": "Выражение желания 고 싶다",
 "lesson_38_also_do": "Частица \"тоже, также\" - 도",
 "lesson_39_only_man": "Частица \"только\" - 만",
 "lesson_47_simultaneous_actions": "Одновременные действия -면서",
 "lesson_48_after_action": "После действия -은/ㄴ 후에",
 "lesson_50_before_action": "Перед действием -기 전에",
 "lesson_51_after_formal": "Формальное \"после\" -고 나서 / -은 다음에",
 "lesson_53_instrumental_ro": "Инструментальный 로/으로",
 "lesson_54_purpose_movement": "Цель движения -러/으러",
 "lesson_55_honorific_si": "Почтительная частица -(으)시-",
 "lesson_56_contrast_jiman": "Противопоставление -지만",
 "lesson_57_choice_ina": "Выбор 이나",
 "lesson_58_choice_geona": "Выбор 거나",
 "lesson_59_suggestion_eulkayo": "Предложение -(으)ㄹ까요",
 "lesson_61_helping_actions": "Действия для других 아/어/여 주다",
 "lesson_62_obligation": "Долженствование 아/어/여야 하다/되다",
 "lesson_63_ability": "Возможность и способность -(으)ㄹ 수 있다/없다",
 "lesson_64_conditional_intention": "Условие для намерения -(으)려면",
 "lesson_65_minimum_condition": "Минимальные условия -기만 하면",
 "lesson_66_permission": "Разрешение -아도/어도/여도 되다",
 "lesson_67_prohibition": "Запрет -(으)면 안 되다",
 "lesson_68_inability_ji_moshada": "Неспособность -지 못하다",
 "lesson_69_intention_promise": "Намерение и обещание -(으)ㄹ게요",
 "lesson_70_trying_experience": "Попытка и опыт -아/어 보다",
 "lesson_71_from_whom": "От кого -에게서/-한테서",
 "lesson_72_future_intention": "Намерение и воля -겠-",
 "lesson_73_supposition": "Предположение -겠-",
 "lesson_74_irregular_bieup": "Неправильные глаголы ㅂ-неправильные",
 "lesson_75_irregular_digeut": "Неправильные глаголы ㄷ-неправильные",
 "lesson_76_irregular_siot": "Неправильные глаголы ㅅ-неправильные",
 "lesson_77_irregular_eu": "Неправильные глаголы ㅡ-неправильные",
 "lesson_78_irregular_hieut": "Неправильные глаголы ㅎ-неправильные",
 "lesson_79_irregular_rieul": "Неправильные глаголы 르-неправильные",
 "lesson_80_possession_advanced": "Обладание и владение 가지다/갖다",
 "lesson_81_comparative_constructions": "Сравнительные конструкции -보다 더/덜/같이",
 "lesson_82_reason_consequence": "Причина и следствие -기 때문에",
 "lesson_83_passive_constructions": "Пассивные конструкции (пассивный залог)",
 "lesson_84_constructions_neun_daero": "Конструкции -는 대로",
 "lesson_85_conditional_damyeon": "Условное -다면",
 "lesson_86_time_constructions": "Временные конструкции",
 "lesson_87_not_vs_cant": "Урок: 안 vs 못 — Не хочу vs Не могу",
 "lesson_88_time_adverbs": "Урок: 아직/이미/벌써 — Временные наречия",
 "lesson_89_conjunctions_practice": "Урок: 그래서/그런데/그러면 — Союзы",
 "lesson_90_topik_prep": "Подготовка к TOPIK II",
 "lesson_91_essay_writing": "Написание эссе на корейском",
 "lesson_92_traditions": "Корейские традиции и праздники",
 "lesson_93_large_numbers": "Большие числа и деньги -- 큰 숫자와 돈",
 "lesson_94_medicine": "Корейская медицина и аптека",
 "lesson_95_assumption_geot_gatda": "Предположение -(으)ㄹ 것 같다",
 "lesson_96_tendency_pyeonida": "Скорее да, чем нет -는/(으)ㄴ 편이다",
 "lesson_97_solution_myeon_doeda": "Достаточно сделать -(으)면 되다",
 "lesson_98_concession_gineun_hada": "Вообще-то да, но… -기는 하다",
 "lesson_99_modesty_gineunyo": "Ну что вы! -기는요",
 "level_1/lesson_01_grammar": "Основы корейской грамматики",
 "level_1/lesson_about_me": "Описание себя | 1급 Корейский язык",
 "level_1/lesson_adverb_da": "다 — «всё», «полностью» — 1급 Корейский",
 "level_1/lesson_adverbs_degree": "Наречия степени — 아주, 너무, 정말 | 1급 Корейский язык",
 "level_1/lesson_antonyms": "Противоположности (антонимы) | 1급 Корейский язык",
 "level_1/lesson_cafe_shopping": "В кафе и магазине | 1급 Корейский язык",
 "level_1/lesson_campus": "Университет: аудитория и кампус | 1급 Корейский язык",
 "level_1/lesson_casual_slang": "Разговорный корейский и сленг | 1급 Корейский язык",
 "level_1/lesson_confusing_words": "Слова, которые легко перепутать | 1급 Корейский язык",
 "level_1/lesson_connecting_go": "Соединительный союз -고 | 1급 Корейский язык",
 "level_1/lesson_counters_basic": "Счётные слова — основы | 1급 Корейский язык",
 "level_1/lesson_daily_routine": "Распорядок дня — 1급 Корейский язык",
 "level_1/lesson_demonstratives_full": "이/그/저 — полная система указательных — 1급 Корейский",
 "level_1/lesson_describe_person": "Описание человека | 1급 Корейский язык",
 "level_1/lesson_direction_euro": "Частица направления 으로/로 — направление, средство, материал",
 "level_1/lesson_directions_basic": "Как спросить дорогу | 1급 Корейский язык",
 "level_1/lesson_emotions_basic": "Базовые эмоции | 1급 Корейский язык",
 "level_1/lesson_english_loanwords": "Английские заимствования (외래어) | 1급 Корейский язык",
 "level_1/lesson_eseo_kkaji": "에서 ~ 까지 — от … до — 1급 Корейский",
 "level_1/lesson_etiquette": "Корейский этикет | 1급 Корейский язык",
 "level_1/lesson_fill_form": "Заполняем анкету | 1급 Корейский язык",
 "level_1/lesson_food_order": "Виды кухни и заказ в ресторане | 1급 Корейский язык",
 "level_1/lesson_formal_imperative": "Вежливая просьба -(으)십시오 / -(으)세요 | 1급 Корейский язык",
 "level_1/lesson_from_eseo": "에서 как \"из/от\" — происхождение и направление \"откуда\"",
 "level_1/lesson_future_georeyeo": "Будущее время -(으)ㄹ 거예요 — планы и намерения",
 "level_1/lesson_h_deletion": "ㅎ 탈락 — исчезающая ㅎ — 1급 Корейский",
 "level_1/lesson_health_phrases": "Здоровье и самочувствие | 1급 Корейский язык",
 "level_1/lesson_holidays": "Корейские праздники | 1급 Корейский язык",
 "level_1/lesson_honorific_words": "Почтительные слова: 계시다, 드시다, 주무시다 | 1급 Корейский язык",
 "level_1/lesson_introduction_dialogue": "Диалог \"Знакомство\" | 1급 Корейский язык",
 "level_1/lesson_kdrama_phrases": "K-drama фразы | 1급 Корейский язык",
 "level_1/lesson_korean_age": "Корейский возраст | 1급 Корейский язык",
 "level_1/lesson_korean_food": "Корейская кухня | 1급 Корейский язык",
 "level_1/lesson_korean_keyboard": "Корейская клавиатура — 1급 Корейский язык",
 "level_1/lesson_korean_names": "Обращения и имена в корейском",
 "level_1/lesson_korean_vs_russian": "Корейский vs Русский — логика языка | 1급 Корейский язык",
 "level_1/lesson_lateralization": "유음화 — ㄴ превращается в ㄹ — 1급 Корейский",
 "level_1/lesson_liaison": "연음 — связывание звуков — 1급 Корейский",
 "level_1/lesson_location_eseo": "Частица 에서 — место действия",
 "level_1/lesson_majors": "Специальность и учёба — 전공 | 1급 Корейский язык",
 "level_1/lesson_minimal_pairs": "Минимальные пары — произношение | 1급 Корейский язык",
 "level_1/lesson_movement_verbs": "Базовые глаголы движения | 1급 Корейский язык",
 "level_1/lesson_n_insertion": "ㄴ 첨가 — появление звука ㄴ — 1급 Корейский",
 "level_1/lesson_nature_simple": "Простая природа | 1급 Корейский язык",
 "level_1/lesson_negation": "Отрицание глаголов — 안/못 | 1급 Корейский язык",
 "level_1/lesson_neunyo_short": "-은요? / -는요? · N-요 — короткий вопрос — 1급 Корейский",
 "level_1/lesson_not_but_anira": "이/가 아니라 — «не X, а Y» | 1급 Корейский язык",
 "level_1/lesson_numbers_life": "Числа в повседневной жизни | 1급 Корейский язык",
 "level_1/lesson_numbers_units": "Урок: Числа с единицами — 시간, 분, 일, 달/개월, 년",
 "level_1/lesson_object_particle": "Частица объекта 을/를 — винительный падеж",
 "level_1/lesson_palatalization": "구개음화 — ㄷ/ㅌ переходят в ㅈ/ㅊ — 1급 Корейский",
 "level_1/lesson_particle_do": "Частица 도 — тоже",
 "level_1/lesson_particle_e": "Частица места 에 — нахождение",
 "level_1/lesson_particle_ege": "Частица 에게/한테 — кому | 1급 Корейский язык",
 "level_1/lesson_particle_man": "Частица 만 — «только» | 1급 Корейский язык",
 "level_1/lesson_pharmacy_dialogue": "В аптеке и больнице | 1급 Корейский язык",
 "level_1/lesson_phone_numbers": "Телефон и адрес по-корейски | 1급 Корейский язык",
 "level_1/lesson_place_prepositions": "Предлоги места: 위에, 아래에, 옆에, 앞에, 뒤에",
 "level_1/lesson_possessive_ui": "Частица 의 — притяжательность | 1급 Корейский язык",
 "level_1/lesson_price_per_unit": "N에 얼마예요? — цена за единицу — 1급 Корейский",
 "level_1/lesson_pronouns": "Местоимения: 나, 저, 너, 이것, 그것, 저것",
 "level_1/lesson_pronunciation": "Правила произношения — 1급 Корейский язык",
 "level_1/lesson_question_determiners": "무슨 / 어느 / 어떤 / 몇 — четыре «какой» | 1급 Корейский язык",
 "level_1/lesson_question_sentences": "Вопросительные предложения",
 "level_1/lesson_rieul_verbs": "ㄹ-глаголы: 살다 → 삽니다 | 1급 Корейский язык",
 "level_1/lesson_russian_mistakes": "Частые ошибки русскоязычных в корейском",
 "level_1/lesson_shopping_clothes": "В магазине одежды | 1급 Корейский язык",
 "level_1/lesson_sms_chat": "SMS и KakaoTalk | 1급 Корейский язык",
 "level_1/lesson_sov_order": "SOV: Порядок слов в корейском языке",
 "level_1/lesson_street_greetings": "Живые приветствия и прощания | 1급 Корейский язык",
 "level_1/lesson_stroke_order": "Порядок написания черт — 1급 Корейский язык",
 "level_1/lesson_subject_particle": "Частица подлежащего 이/가",
 "level_1/lesson_tensification": "경음화 — напряжение согласных — 1급 Корейский",
 "level_1/lesson_time_age": "Время и возраст | 1급 Корейский язык",
 "level_1/lesson_topic_particle": "Частица темы 은/는",
 "level_1/lesson_transport_dialogue": "В транспорте | 1급 Корейский язык",
 "level_1/lesson_verb_conjugation": "Спряжение базовых глаголов -- 아요/어요/해요 | 1급 Корейский язык",
 "level_1/lesson_want_gosipda": "Хочу делать — -고 싶다 | 1급 Корейский язык",
 "level_1/lesson_weather_basic": "Погода — базовый уровень | 1급 Корейский язык",
 "level_1/lesson_yes_no": "네/아니요 — Да и Нет в корейском",
 "level_1/lesson_yonsei_review": "Повторяем всё: 정리해 봅시다 | 1급 Корейский язык",
 "level_2/lesson_02_politeness": "Формы вежливости 존댓말",
 "level_2/lesson_abstract_nouns": "Абстрактные существительные — 2급 Корейский",
 "level_2/lesson_adjective_modifier": "Прилагательные перед существительными -(으)ㄴ — 2급 Корейский",
 "level_2/lesson_adverbs_degree": "Наречия степени — 2급 Корейский",
 "level_2/lesson_advice_jigeuraeyo": "-지 그래요? · -는 게 좋겠다 — совет — 2급 Корейский",
 "level_2/lesson_aseo_cause": "-아서/어서 — причина и последовательность — 2급",
 "level_2/lesson_before_after": "-기 전에 / -(으)ㄴ 후에 — до и после — 2급 Корейский",
 "level_2/lesson_boida": "A-아/어 보이다 — «выглядит как» — 2급 Корейский",
 "level_2/lesson_but_jiman": "-지만 — но, однако — 2급",
 "level_2/lesson_changes": "-아/어지다 · -게 되다 — изменения — 2급 Корейский",
 "level_2/lesson_concession_wish": "-아/어도 · -지 않아도 되다 · -았으면 좋겠다 — 2급 Корейский",
 "level_2/lesson_condition_myeon": "-(으)면 — если: подробно — 2급",
 "level_2/lesson_confirmation_jyo": "-지요/죠? — правда ведь? — 2급 Корейский",
 "level_2/lesson_connecting_go": "Соединительный союз -고 — и, а потом — 2급",
 "level_2/lesson_counters": "Счётные слова — расширенный (번, 대, 송이, 켤레, 장) — 2급",
 "level_2/lesson_culture_etiquette": "한국의 예절 — этикет и извинения — 2급 Корейский",
 "level_2/lesson_culture_gestures": "한국의 몸짓 언어 — жесты и язык тела — 2급 Корейский",
 "level_2/lesson_culture_health_habits": "건강에 좋은 생활 습관 — здоровые привычки — 2급 Корейский",
 "level_2/lesson_culture_hobbies": "한국인의 취미와 여가 생활 — хобби и досуг — 2급 Корейский",
 "level_2/lesson_culture_traffic_signs": "한국의 교통 표지판 — дорожные знаки и указатели — 2급 Корейский",
 "level_2/lesson_culture_weather_life": "날씨와 생활 — погода и жизнь по сезонам — 2급 Корейский",
 "level_2/lesson_daily_detail": "Распорядок дня — подробно — 2급 Корейский",
 "level_2/lesson_duration": "는 중 · 동안 · (으)ㄴ 지 — время — 2급 Корейский",
 "level_2/lesson_education": "Образование и учёба — 2급 Корейский",
 "level_2/lesson_emotions": "Эмоции и чувства — 2급 Корейский",
 "level_2/lesson_eo_deurida": "-아/어 드리다 — сделать для старшего — 2급 Корейский",
 "level_2/lesson_eupsida": "-(으)ㅂ시다 — давайте сделаем — 2급 Корейский",
 "level_2/lesson_experience_jeoki": "-ㄴ/은 적이 있다/없다 — бывало ли",
 "level_2/lesson_filler_words": "Слова-связки и филлеры — 2급 Корейский",
 "level_2/lesson_friends_titles": "Друзья, знакомства и обращения | 2급 Корейский язык",
 "level_2/lesson_gajigo": "-아/어 가지고 · 가지고 오다/가다 — 2급 Корейский",
 "level_2/lesson_ge_adverb": "-게 · -아/어하다 · -는 데 걸리다 · -(으)ㄹ까요? ③ — 2급 Корейский",
 "level_2/lesson_geodeunyo": "-거든요 · -(으)ㄴ데요 — объяснение и мягкий заход — 2급 Корейский",
 "level_2/lesson_go_sipahada": "Конструкция -고 싶어하다 — он/она хочет — 2급",
 "level_2/lesson_ida_questions": "이다 в вопросах — 누구예요? 뭐예요? 어디예요?",
 "level_2/lesson_if_myeon": "-(으)면 — если: введение (условие)",
 "level_2/lesson_intonation": "억양 — интонация корейского предложения — 2급 Корейский",
 "level_2/lesson_intro_ability": "-(으)ㄹ 수 있다/없다 — умею, могу (вводный) — 2급 Корейский",
 "level_2/lesson_intro_attributive": "관형사형 -는 / -(으)ㄴ / -(으)ㄹ — причастия (вводный) — 2급 Корейский",
 "level_2/lesson_intro_geoyo": "-(으)ㄹ게요 — я сделаю (вводный) — 2급 Корейский",
 "level_2/lesson_intro_haeboda": "-아/어 보다 — попробовать сделать (вводный) — 2급 Корейский",
 "level_2/lesson_intro_must": "-아/어야 하다 — надо сделать (вводный) — 2급 Корейский",
 "level_2/lesson_intro_myeonseo": "-(으)면서 — делая одно и другое (вводный) — 2급 Корейский",
 "level_2/lesson_irregular_verbs": "Неправильные глаголы (불규칙 동사) — 2급",
 "level_2/lesson_jul_alda": "-(으)ㄹ 줄 알다/모르다 — уметь — 2급 Корейский",
 "level_2/lesson_meeting_friend": "Договариваемся о встрече — практика — 2급 Корейский",
 "level_2/lesson_nature_environment": "Природа и окружающая среда — 2급 Корейский",
 "level_2/lesson_nature_vocab": "Природа и пейзаж — 자연과 풍경",
 "level_2/lesson_neunde": "-(으)ㄴ/는데 — а, но, кстати — 2급 Корейский",
 "level_2/lesson_nikkayo": "-(으)니까요 — потому что (в конце) — 2급 Корейский",
 "level_2/lesson_noda_duda": "-아/어 놓다 · -아/어 두다 — сделать заранее — 2급 Корейский",
 "level_2/lesson_particle_ege": "께 / 께서 — вежливое «кому» и «кто» (углублённый) — 2급",
 "level_2/lesson_past_perfect": "-았/었었어요 — давнопрошедшее время — 2급 Корейский",
 "level_2/lesson_past_questions": "Вопросы в прошедшем времени — практика — 2급",
 "level_2/lesson_personality": "Характер и личность — 2급 Корейский",
 "level_2/lesson_plans_intention": "-(으)ㄹ까 하다 · -아/어야겠다 — планы и решения — 2급 Корейский",
 "level_2/lesson_progressive": "Прогрессив -고 있다 — действие прямо сейчас",
 "level_2/lesson_purpose": "-(으)려고 · -기 위해서 · -기로 하다 — цель — 2급 Корейский",
 "level_2/lesson_quantity_particles": "부터 · 씩 · 이상/이하 · 만 빼고 — количество и границы — 2급",
 "level_2/lesson_reactions": "-네요 · -군요 · -나요? — реакция — 2급 Корейский",
 "level_2/lesson_requests": "Просьбы и команды — 주세요, 하세요, 가세요",
 "level_2/lesson_restaurant_dialogue": "В ресторане — практические диалоги — 2급 Корейский",
 "level_2/lesson_seems_like": "-는 것 같다 vs -(으)ㄹ 것 같다 — кажется",
 "level_2/lesson_shopping": "Покупки в магазине — 2급 Корейский",
 "level_2/lesson_small_particles": "밖에 · 마다 · 처럼 · 쯤 — частицы — 2급 Корейский",
 "level_2/lesson_spoken_shortcuts": "Разговорные сокращения — 2급 Корейский",
 "level_2/lesson_sports_vocab": "Спорт и фитнес — 스포츠와 운동",
 "level_2/lesson_state_adjectives": "Прилагательные состояния — 2급 Корейский",
 "level_2/lesson_state_verbs": "-고 있다 ② · -아/어 있다 — состояния — 2급 Корейский",
 "level_2/lesson_supposition_geoyeyo": "-(으)ㄹ 거예요 — предположение (추측) — 2급 Корейский",
 "level_2/lesson_tense_comparison": "Три времени вместе — 2급 Корейский",
 "level_2/lesson_time_frequency_adverbs": "Наречия времени и частотности (시간/빈도 부사) — 2급",
 "level_2/lesson_time_now": "지금 · 이제 · 요즘 · 아까 · 이따가 · 나중에 — 2급 Корейский",
 "level_2/lesson_topic_vs_subject": "은/는 vs 이/가 — Тема и подлежащее",
 "level_2/lesson_uncertainty": "Неопределённость — 글쎄요, 아마도, 모르겠어요",
 "level_2/lesson_vocab_cooking": "요리법과 요리 도구 — рецепты и посуда — 2급 Корейский",
 "level_2/lesson_vocab_housing": "주거 형태와 이사 — жильё и переезд — 2급 Корейский",
 "level_2/lesson_vocab_lost_items": "분실 — потеря вещей — 2급 Корейский",
 "level_2/lesson_vocab_medicine_types": "증상과 약품 종류 — симптомы и лекарства — 2급 Корейский",
 "level_2/lesson_vocab_office_supplies": "사무용품과 직장 생활 — офис и работа — 2급 Корейский",
 "level_2/lesson_vocab_pop_culture": "대중문화 — поп-культура — 2급 Корейский",
 "level_2/lesson_vocab_public_offices": "공공 기관 — государственные учреждения — 2급 Корейский",
 "level_2/lesson_vocab_public_places": "공공장소 — общественные места и правила — 2급 Корейский",
 "level_2/lesson_vocab_recycling": "분리수거 — сортировка мусора — 2급 Корейский",
 "level_2/lesson_vocab_school_life": "학교생활 — школьная жизнь — 2급 Корейский",
 "level_2/lesson_volition": "-겠어요 · -(으)ㄹ래요 · -(으)시겠어요 — 2급 Корейский",
 "level_2/lesson_weather_detailed": "Погода подробно — 2급 Корейский",
 "level_2/lesson_weather_talk": "Погода в разговоре — 2급 Корейский",
 "level_2/lesson_when_ttae": "-(으)ㄹ 때 — когда делаю — 2급 Корейский",
 "level_3/lesson_appearance": "Урок: Описание внешности — 외모 묘사",
 "level_3/lesson_aseo_vs_nikka": "-아/어서 vs -니까 — разница причин",
 "level_3/lesson_attributive_forms": "Урок: Атрибутивные формы глаголов",
 "level_3/lesson_bank": "Урок: В банке — 은행에서",
 "level_3/lesson_because_aseo": "Урок: Причина 아서/어서",
 "level_3/lesson_cooking_vocab": "Кулинария и рецепты — 요리와 레시피 | 3급",
 "level_3/lesson_daesin_irado": "N 대신(에) · N(이)라도 — замена и компромисс — 3급",
 "level_3/lesson_daga_interruption": "-다가 — делал и вдруг",
 "level_3/lesson_description_compare": "N에 대해서 · N에 비해서 · N적 — тема и сравнение — 3급",
 "level_3/lesson_directions": "Урок: Дорога и навигация — 길 찾기",
 "level_3/lesson_experience_jeok": "Урок: Опыт -(으)ㄴ 적이 있다/없다",
 "level_3/lesson_formal_expressions": "-(스)ㅂ니다만 · -기 바랍니다 · 한다체 — официальный стиль — 3급",
 "level_3/lesson_future_geoyeyo": "Урок: Будущее время -(으)ㄹ 거예요",
 "level_3/lesson_gi_evaluation": "-기가 쉽다/어렵다 · -기에 좋다 · -기 시작하다 — 3급 Корейский",
 "level_3/lesson_honorific_si": "Урок: Почтительная речь -(으)시-",
 "level_3/lesson_hotel": "Урок: В гостинице — 호텔/숙소에서",
 "level_3/lesson_inability_su_eopda": "-을/ㄹ 수 없다 — не могу",
 "level_3/lesson_indirect_question": "-는지 알다/모르다 — знаю ли",
 "level_3/lesson_indirect_short": "-대요 · -냬요 · -재요 · -래요 — сокращённая косвенная речь — 3급",
 "level_3/lesson_indirect_speech_basic": "Урок: Косвенная речь (базовая)",
 "level_3/lesson_intention_ryeogo": "Урок: Намерение -(으)려고 하다",
 "level_3/lesson_irregular_verbs_intro": "Урок: Введение в неправильные глаголы",
 "level_3/lesson_jamaja": "-자마자 — как только",
 "level_3/lesson_medical": "Урок: В больнице и аптеке — 병원과 약국에서",
 "level_3/lesson_moreugetda": "-(으)ㄹ지 모르겠다 · 얼마나 -(으)ㄴ지 모르다 — 3급 Корейский",
 "level_3/lesson_must_deep": "Урок: Долженствование (углублённый)",
 "level_3/lesson_myeonseo_simultaneous": "-(으)면서 — одновременно",
 "level_3/lesson_nominalization": "Номинализация 기/는 것 — превращаем глагол в существительное",
 "level_3/lesson_not_but_anira": "Урок: Не X, а Y — 이/가 아니라",
 "level_3/lesson_party_korean": "Тусовка по-корейски: 술자리 и 노래방 | 3급 Корейский язык",
 "level_3/lesson_permission_prohibition": "Урок: Разрешение и запрет",
 "level_3/lesson_phone_talk": "Урок: Телефонные разговоры — 전화 통화",
 "level_3/lesson_question_particles": "Урок: Вопросительные частицы — 죠?, 잖아요, 거예요?, 을까요?",
 "level_3/lesson_rhetorical": "Урок: Риторические вопросы (잖아요, 죠/지요, 잖다)",
 "level_3/lesson_ro_uses": "(으)로 해서 · (으)로 만들다 · (으)로 유명하다 — 3급 Корейский",
 "level_3/lesson_social_topics": "🌍 Социальные темы - 3급",
 "level_3/lesson_tenikka_tende": "-(으)ㄹ 테니까 · -(으)ㄹ 텐데 — предположение с выводом — 3급",
 "level_3/lesson_topic_subject_deep": "Урок: 이/가 vs 은/는 — подробное сравнение",
 "level_3/lesson_transport_detail": "Транспорт и путешествия — 교통과 여행",
 "level_3/lesson_work_university": "На работе и в университете — общение — 3급 Корейский",
 "level_4/lesson_baramae": "-는 바람에 — из-за внезапной причины",
 "level_4/lesson_beorida": "-아/어 버리다 и -고 말다 — завершённость с эмоцией",
 "level_4/lesson_boni": "-다 보니 — незаметно для себя...",
 "level_4/lesson_causative": "Каузатив — заставляем и позволяем действовать",
 "level_4/lesson_chaero": "-(으)ㄴ 채(로) — в неизменном состоянии",
 "level_4/lesson_dedaga": "-는 데다가 — вдобавок ко всему",
 "level_4/lesson_deon": "Ретроспективное -던 и -았/었던 — воспоминания",
 "level_4/lesson_deoni": "-았/었더니 — сделал и обнаружил, что...",
 "level_4/lesson_dorok": "-도록 — чтобы / до такой степени",
 "level_4/lesson_eulsurok": "-(으)ㄹ수록 — чем..., тем...",
 "level_4/lesson_finance_vocab": "Финансы и банк — 금융과 은행",
 "level_4/lesson_ge_hada": "-게 하다 — заставить, позволить, сделать так, чтобы",
 "level_4/lesson_gime": "-는 김에 — раз уж делаю",
 "level_4/lesson_indirect_speech": "Косвенная речь 고 하다 — передаем чужие слова",
 "level_4/lesson_internet_slang": "Интернет-сленг — 인터넷 슬랭 | 4급",
 "level_4/lesson_legal_basics": "Юридические основы — 법률 기초",
 "level_4/lesson_maryeonida": "-기 마련이다 — так уж заведено",
 "level_4/lesson_neundedo": "-(으)ㄴ/는데도 — несмотря на то, что",
 "level_4/lesson_neurago": "-느라고 — из-за того, что был занят",
 "level_4/lesson_people_types": "Социальные типажи и ярлыки | 4급 Корейский язык",
 "level_4/lesson_ppeonhada": "-(으)ㄹ 뻔하다 — чуть не...",
 "level_4/lesson_semida": "-(으)ㄴ/는 셈이다 — можно сказать, что...",
 "level_4/lesson_symptoms_vocab": "Симптомы и жалобы — 증상과 불편",
 "level_4/lesson_through_tonghae": "을/를 통해(서) — через, посредством | 4급",
 "level_4/lesson_writing_messages": "Написание писем и сообщений — 편지와 메시지 쓰기 | 4급",
 "level_4/lesson_written_style": "Письменный стиль 문어체 — -ㄴ다/는다, -(으)며, -(으)나",
 "level_5/lesson_addition": "-거니와 · -(으)ㄹ뿐더러 · 마저 · 을/를 비롯해서 — 5급",
 "level_5/lesson_appearance_slang": "Внешность: 얼짱, 몸짱 и 성형수술 | 5급 Корейский язык",
 "level_5/lesson_apprehension": "-(으)ㄹ세라 · -는 양 · -(으)ㄹ 턱이 없다 — 5급 Корейский",
 "level_5/lesson_bookish_cause": "-기에 망정이지 · -답시고 · -기로서니 · 에 의하면 — 5급",
 "level_5/lesson_bookish_connectors": "-(으)므로 · -(으)나 · -(으)며 · -는 한편 — 5급 Корейский",
 "level_5/lesson_causative_passive_full": "Урок: Полная система 사동/피동 (каузатив и пассив)",
 "level_5/lesson_choice_advanced": "-(으)ㄹ 바에야 · -건 -건 · -다기보다는 · -느니만큼 — 5급",
 "level_5/lesson_concession_advanced": "-더라도 · -(으)ㄹ지라도 · -(으)ㄴ들 · -고도 — 5급 Корейский",
 "level_5/lesson_conditions_decisions": "-는 한 · -기 나름이다 · -느냐에 달려 있다 — 5급 Корейский",
 "level_5/lesson_dialects": "Диалекты корейского языка",
 "level_5/lesson_doe": "-(으)되 — да, но при условии (формальный стиль)",
 "level_5/lesson_emotions_deep": "Эмоции и психология — глубже | 5급",
 "level_5/lesson_enumeration": "-는가 하면 · -(으)랴 -(으)랴 · -는 법이다 — 5급",
 "level_5/lesson_ganjeop_nuance": "Урок: Оттенки косвенной речи (간접화법의 뉘앙스) — 5급",
 "level_5/lesson_goja": "-고자 — с целью, намереваясь (формальный стиль)",
 "level_5/lesson_guoche_chukyak": "Урок: Разговорная редукция (구어체 축약) — 5급",
 "level_5/lesson_gyeokssik_jeonhwan": "Урок: Переключение регистров (격식 전환 훈련) — 5급",
 "level_5/lesson_habits_degree": "-아/어 대다 · -기 일쑤이다 · -다 못해 · -(으)리만치 — 5급",
 "level_5/lesson_intention_advanced": "-(느)ㄴ다는 것이 · -(으)려고 들다 · -(으)려다가 — 5급",
 "level_5/lesson_isang": "-는 이상 — раз уж так, поскольку",
 "level_5/lesson_mangjeong": "-을망정 — пусть даже, но всё же (формальная уступка)",
 "level_5/lesson_matchumbeop": "Урок: Орфография C1 (맞춤법) — 5급",
 "level_5/lesson_meanwhile_banmyeon": "-는 반면에 — в то время как | 5급",
 "level_5/lesson_media_news": "Медиа и новости — 미디어와 뉴스 | 5급",
 "level_5/lesson_narrative_style": "Урок: Нарративный стиль (다고, 라며, 답니다)",
 "level_5/lesson_neunba": "Урок: -는바 — согласно нижеследующему (официальный стиль)",
 "level_5/lesson_neuni": "-느니 — уж лучше... чем...",
 "level_5/lesson_not_only": "-(으)ㄹ 뿐만 아니라 — не только, но и | 5급",
 "level_5/lesson_proverbs": "Корейские пословицы — 한국 속담 | 5급",
 "level_5/lesson_punctuation": "Урок: Корейская пунктуация",
 "level_5/lesson_result_retrospect": "-(으)ㄴ 끝에 · -아/어 내다 · -(으)ㄴ 나머지 · -데요 — 5급",
 "level_5/lesson_situation_emphasis": "-는 가운데 · 치고 · -(으)ㅁ에 따라 · 여간 -지 않다 — 5급",
 "level_5/lesson_subjunctive_if_only": "-(았/었)더라면 — если бы | 5급",
 "level_5/lesson_supposition_advanced": "-다고 치다 · -는 셈치다 · -듯이 — 5급 Корейский",
 "level_5/lesson_supposition_degree": "-는 듯하다 · -(으)ㄹ 게 뻔하다 · -기 십상이다 — 5급",
 "level_5/lesson_suryang_eorimsu": "Урок: Приблизительное количество (수량 어림수) — 5급",
 "level_5/lesson_topik_54_essay": "Урок: TOPIK 쓰기 54번 — эссе-рассуждение — 5급",
 "level_5/lesson_yangtae_chuchuk": "Урок: Модальность предположения (추측과 가능성의 양태) — 5급",
 "level_6/lesson_academic_vocabulary": "📚 Академическая лексика - 6급",
 "level_6/lesson_academic_writing": "Структура научной статьи — 학술 논문 작성법",
 "level_6/lesson_balpyo_qna": "Урок: Публичное выступление и Q&A (발표와 질의응답) — 6급",
 "level_6/lesson_bokmun_nopim": "Расширенные правила 주체 높임 — 6급",
 "level_6/lesson_business_email_writing": "Урок: Написание деловых писем (업무 이메일) — 6급",
 "level_6/lesson_business_vocabulary": "🏢 Деловая лексика - 6급",
 "level_6/lesson_classic_texts": "Классические тексты - 6급",
 "level_6/lesson_dasipi_evidential": "Конструкция -다시피 — 6급",
 "level_6/lesson_diplomatic_language": "Урок: Язык дипломатии и переговоров — 외교와 협상 언어",
 "level_6/lesson_dopyo_tonggye": "Урок: Описание графиков и статистики (도표·통계 해석) — 6급",
 "level_6/lesson_editorial_style": "Урок: 사설과 논평 문체 — Стиль газетных передовиц",
 "level_6/lesson_etymology": "Этимология корейского языка — 어원 | 6급",
 "level_6/lesson_eumeurosseo_means": "Конструкция -음으로써 — 6급",
 "level_6/lesson_geonman_contrast": "Конструкция -건만 — 6급",
 "level_6/lesson_geosigyeongje": "Урок: Макроэкономическая лексика (거시경제 용어) — 6급",
 "level_6/lesson_gie_literary_cause": "Конструкция -기에 — 6급",
 "level_6/lesson_gime_maryeon": "Конструкции -는 김에 и -기 마련이다 — 6급",
 "level_6/lesson_gugeo_sunhwa": "Урок: История языковой политики (국어순화 운동) — 6급",
 "level_6/lesson_guknae_jeongchi": "Урок: Лексика внутренней политики (국내 정치 용어) — 6급",
 "level_6/lesson_hanja_nuances": "Нюансы 한자어 - 6급",
 "level_6/lesson_hoeuirok_writing": "Урок: Написание 회의록 (протокола совещания) — 6급",
 "level_6/lesson_homonyms": "Урок: Омонимы и паронимы корейского языка",
 "level_6/lesson_honorifics_real": "Гонорификативность в реальности - 6급",
 "level_6/lesson_hyeondaesa_baegyeong": "Урок: Культурно-исторический фон XX века (현대사 배경지식) — 6급",
 "level_6/lesson_idioms": "🎭 Идиомы и фразеологизмы - 6급",
 "level_6/lesson_it_vocabulary": "💻 IT-лексика - 6급",
 "level_6/lesson_jagi_sogaeseo_writing": "Урок: Написание 자기소개서 (резюме-эссе) — 6급",
 "level_6/lesson_jondaenmal_banmal": "Урок: 존댓말 vs 반말 — Полная система вежливости",
 "level_6/lesson_keonyeong_farfrom": "Конструкция -기는커녕 — 6급",
 "level_6/lesson_ko_ru_translation": "Урок: Ловушки корейско-русского перевода — 6급",
 "level_6/lesson_korean_humor": "Корейский юмор и отсылки - 6급",
 "level_6/lesson_legal_language": "Язык юридических документов и договоров — 법률 문서 언어",
 "level_6/lesson_legal_litigation": "⚖️ Юридическая лексика: судопроизводство - 6급",
 "level_6/lesson_literary_expressions": "📖 Литературные выражения - 6급",
 "level_6/lesson_mangjeong_concessive": "Конструкция -을망정 — 6급",
 "level_6/lesson_medical_vocabulary": "🏥 Медицинская лексика - 6급",
 "level_6/lesson_minwon_writing": "Урок: Написание 민원 (гражданского обращения) — 6급",
 "level_6/lesson_museopge_immediacy": "Конструкция -기가 무섭게 — 6급",
 "level_6/lesson_north_korean": "Северокорейский язык — 북한어 | 6급",
 "level_6/lesson_official_documents": "Урок: Язык судебных решений и госдокументов — 판결문과 공문서",
 "level_6/lesson_pair_distinctions": "Различение близких конструкций — 6급",
 "level_6/lesson_pidong_nuances": "Нюансы пассива (피동) — 6급",
 "level_6/lesson_poetry_analysis": "Урок: 시 분석과 상징 — Анализ поэзии и символизм",
 "level_6/lesson_rhetoric": "Урок: Корейская риторика и аргументация",
 "level_6/lesson_sadong_nuances": "Нюансы каузатива (사동) — 6급",
 "level_6/lesson_sajaseongeo": "Урок: 사자성어 — Четырёхсимвольные идиомы",
 "level_6/lesson_seosa_gibeop": "Урок: 서사 기법과 시점 — Анализ повествовательной техники — 6급",
 "level_6/lesson_sinche_gwanyongeo": "Урок: Идиомы с частями тела (신체 관용어) — 6급",
 "level_6/lesson_street_korean": "Уличный корейский: понимать, но не говорить | 6급 Корейский язык",
 "level_6/lesson_tonge_circumstance": "Конструкция -는 통에 — 6급",
 "level_6/lesson_topik_reading_strategy": "Урок: Стратегия чтения TOPIK 6급 — 6급",
 "vocabulary/abstract_life": "Словарь: Понятия, люди и служебные слова",
 "vocabulary/accidents": "Словарь: Происшествия и аварии",
 "vocabulary/adjectives": "Словарь: 🌟 Прилагательные - 형용사",
 "vocabulary/adverbs_spoken": "Словарь: Разговорные наречия",
 "vocabulary/aegyo": "Словарь: Милая речь (애교)",
 "vocabulary/animals": "Словарь: Животные - 동물",
 "vocabulary/appearance": "Словарь: Внешность и стиль",
 "vocabulary/basicfood": "Словарь: Урок: Еда и напитки (базовая)",
 "vocabulary/bathroom": "Словарь: Ванная и туалет",
 "vocabulary/beauty": "Словарь: Косметика и уход",
 "vocabulary/body": "Словарь: 🧍 Части тела - 신체",
 "vocabulary/city": "Словарь: 🌆 Город и места - 도시와 장소",
 "vocabulary/clothes": "Словарь: Одежда (옷)",
 "vocabulary/colors": "Словарь: Цвета - 색깔",
 "vocabulary/communication": "Словарь: Урок: Общение",
 "vocabulary/conjunctions": "Словарь: 🔗 Союзы - 접속사",
 "vocabulary/counters": "Словарь: Счётные слова",
 "vocabulary/countries": "Словарь: 🌍 Страны и национальности - 나라",
 "vocabulary/daily_routine": "Словарь: Урок: Распорядок дня",
 "vocabulary/date": "Словарь: Дата - 날짜",
 "vocabulary/daystime": "Словарь: Урок: Дни недели и время",
 "vocabulary/emotions": "Словарь: Урок: Эмоции по-корейски",
 "vocabulary/everyday_nouns": "Словарь: Быт, вещи и заимствования",
 "vocabulary/fairy_tale": "Словарь: Сказка «Красная Шапочка»",
 "vocabulary/food": "Словарь: 🍜 Корейская еда — 한국 음식",
 "vocabulary/games": "Словарь: Игры и школьные забавы",
 "vocabulary/hairstyle": "Словарь: В парикмахерской",
 "vocabulary/health": "Словарь: Урок: Здоровье и симптомы",
 "vocabulary/hobbies": "Словарь: 🎨 Хобби и свободное время - 취미",
 "vocabulary/holidays": "Словарь: Корейские праздники",
 "vocabulary/house": "Словарь: 🏠 Дом и мебель - 집과 가구",
 "vocabulary/korea_realia": "Словарь: Реалии Кореи: места, услуги, связь",
 "vocabulary/kpop_fandom": "Словарь: K-POP и фандом",
 "vocabulary/marriage": "Словарь: Отношения и брак",
 "vocabulary/money": "Словарь: 🔢 Деньги и покупки - 돈과 쇼핑",
 "vocabulary/mystic": "Словарь: Мистика и суеверия",
 "vocabulary/office": "Словарь: Урок: Офис и работа",
 "vocabulary/onomatopoeia": "Словарь: Звукоподражания и миметика",
 "vocabulary/opposites": "Словарь: ↔️ Противоположности - 반의어",
 "vocabulary/party": "Словарь: Тусовка и застолье",
 "vocabulary/people_types": "Словарь: Люди, роли и типажи",
 "vocabulary/personality": "Словарь: Характер и личность",
 "vocabulary/phone": "Словарь: Урок: Телефон и связь",
 "vocabulary/places": "Словарь: 🗺️ География Кореи - 지도",
 "vocabulary/polite_formulas": "Словарь: Вежливые формулы и фразы",
 "vocabulary/professions": "Словарь: 💼 Профессии - 직업",
 "vocabulary/questions": "Словарь: Урок: Вопросительные слова",
 "vocabulary/religion": "Словарь: Религии и мировоззрение",
 "vocabulary/restaurant": "Словарь: Урок: В ресторане",
 "vocabulary/romance": "Словарь: Любовь и отношения",
 "vocabulary/school": "Словарь: 🏫 Школа - 학교",
 "vocabulary/seasons": "Словарь: Времена года и месяцы - 계절과 달",
 "vocabulary/shopping": "Словарь: Урок: Покупки",
 "vocabulary/slang": "Словарь: Живая разговорная речь",
 "vocabulary/space": "Словарь: Космос и планеты",
 "vocabulary/sports": "Словарь: Урок: Спорт и фитнес",
 "vocabulary/symptoms": "Словарь: Симптомы и болезни",
 "vocabulary/synonyms": "Словарь: 🟰 Синонимы - 유의어",
 "vocabulary/taste_cooking": "Словарь: Вкус и готовка",
 "vocabulary/time_adverbs": "Словарь: Наречия времени - 시간 부사",
 "vocabulary/topik1_adj_adv": "Словарь: TOPIK 초급: прилагательные и наречия",
 "vocabulary/topik1_nouns_1": "Словарь: TOPIK 초급: существительные I",
 "vocabulary/topik1_nouns_2": "Словарь: TOPIK 초급: существительные II",
 "vocabulary/topik1_numbers_pronouns": "Словарь: TOPIK 초급: числа, местоимения, счётные слова",
 "vocabulary/topik1_verbs": "Словарь: TOPIK 초급: глаголы",
 "vocabulary/topik3_adjectives": "Словарь: TOPIK 중급: прилагательные",
 "vocabulary/topik3_adverbs": "Словарь: TOPIK 중급: наречия",
 "vocabulary/topik3_nouns_1": "Словарь: TOPIK 중급: существительные I",
 "vocabulary/topik3_nouns_2": "Словарь: TOPIK 중급: существительные II",
 "vocabulary/topik3_nouns_3": "Словарь: TOPIK 중급: существительные III",
 "vocabulary/topik3_verbs_1": "Словарь: TOPIK 중급: глаголы I",
 "vocabulary/topik3_verbs_2": "Словарь: TOPIK 중급: глаголы II",
 "vocabulary/transport": "Словарь: Урок: Транспорт",
 "vocabulary/travel_vocab": "Словарь: Урок: Путешествия",
 "vocabulary/trip_planning": "Словарь: Планируем поездку",
 "vocabulary/verbs": "Словарь: 🏃 Глаголы - 동사",
 "vocabulary/verbs_actions": "Словарь: Глаголы: второй круг",
 "vocabulary/weather": "Словарь: Погода (날씨)"
};
