// Level 6 texts (мастерский уровень - 최고급)
// Уровень носителя языка: литература, научные статьи, философия, специализированные темы
// Грамматика: -(으)ㄴ/는 한, -거니와, -(으)ㄹ진대, -노라면, -(으)ㄹ뿐더러, -는 바이다

const level6Texts = {
    personal: [
        {
            id: 'personal-1',
            title: "Философия жизненного пути",
            subtitle: "삶의 철학적 여정",
            korean: `<p><span class="korean-word" data-translation="оглядываясь на прожитые годы" data-pronunciation="살아온 세월을 돌아보노라면 [saraon seworeul dorabonorамyeon]">살아온 세월을 돌아보노라면</span> <span class="korean-word" data-translation="невзирая на многочисленные трудности" data-pronunciation="숱한 고난에도 불구하고 [sutan gonane-do bulguhago]">숱한 고난에도 불구하고</span> <span class="korean-word" data-translation="каждое мгновение" data-pronunciation="매 순간이 [mae sungani]">매 순간이</span> <span class="korean-word" data-translation="содержало смысл" data-pronunciation="의미를 품고 있었음을 [uimireul pumgo isseosseumeul]">의미를 품고 있었음을</span> <span class="korean-word" data-translation="понимаю" data-pronunciation="깨닫게 됩니다 [kkaedatke doemnida]">깨닫게 됩니다</span>.</p>
<p><span class="korean-word" data-translation="в молодости" data-pronunciation="젊은 시절에는 [jeolmeun sijeoreneun]">젊은 시절에는</span> <span class="korean-word" data-translation="достижение успеха" data-pronunciation="성공을 이루는 것이야말로 [seonggongeul iruneun geosiyamallo]">성공을 이루는 것이야말로</span> <span class="korean-word" data-translation="смыслом жизни" data-pronunciation="삶의 목적이라 [sarеui mokjeokirа]">삶의 목적이라</span> <span class="korean-word" data-translation="ошибочно полагал, однако" data-pronunciation="착각했거니와 [chakgakhaetgeoniwa]">착각했거니와</span> <span class="korean-word" data-translation="с течением времени" data-pronunciation="세월이 흐르면서 [sewori heureumyeonseo]">세월이 흐르면서</span> <span class="korean-word" data-translation="отношения с людьми" data-pronunciation="사람들과의 관계가 [saramdeulgwaui gwangyega]">사람들과의 관계가</span> <span class="korean-word" data-translation="более ценны" data-pronunciation="더욱 소중하다는 것을 [deouk sojunghadaneun geoseul]">더욱 소중하다는 것을</span> <span class="korean-word" data-translation="осознал" data-pronunciation="알게 되었습니다 [alge doeeotseumnida]">알게 되었습니다</span>.</p>
<p><span class="korean-word" data-translation="пока человек жив" data-pronunciation="인간이 살아 있는 한 [ingani sara inneun han]">인간이 살아 있는 한</span> <span class="korean-word" data-translation="не только страдания испытывает" data-pronunciation="고통을 겪을뿐더러 [gotongeul gyeokeulppundeoreo]">고통을 겪을뿐더러</span> <span class="korean-word" data-translation="и радость" data-pronunciation="기쁨도 [gippeumdo]">기쁨도</span> <span class="korean-word" data-translation="может переживать" data-pronunciation="느낄 수 있는 바이니 [neukkilsu inneun baini]">느낄 수 있는 바이니</span> <span class="korean-word" data-translation="это и есть" data-pronunciation="이것이야말로 [igеosiyamallo]">이것이야말로</span> <span class="korean-word" data-translation="сущность человеческого бытия" data-pronunciation="인생의 본질이라 [insaengui bonjirira]">인생의 본질이라</span> <span class="korean-word" data-translation="считаю" data-pronunciation="생각합니다 [saenggakhamnida]">생각합니다</span>.</p>
<p><span class="korean-word" data-translation="если задуматься о будущем" data-pronunciation="앞날을 생각할진대 [apnareul saenggakhalchindae]">앞날을 생각할진대</span> <span class="korean-word" data-translation="накопленный опыт" data-pronunciation="쌓아온 경험을 [ssaaon gyeongheomeul]">쌓아온 경험을</span> <span class="korean-word" data-translation="следующему поколению" data-pronunciation="다음 세대에 [daeum sedae-e]">다음 세대에</span> <span class="korean-word" data-translation="передать" data-pronunciation="전하는 것이 [jeonhaneun geosi]">전하는 것이</span> <span class="korean-word" data-translation="моя обязанность" data-pronunciation="제 소임이라 [je soimira]">제 소임이라</span> <span class="korean-word" data-translation="полагаю" data-pronunciation="여깁니다 [yeogipnida]">여깁니다</span>.</p>`,
            translation: "Оглядываясь на прожитые годы, понимаю, что, несмотря на многочисленные трудности, каждое мгновение было наполнено смыслом. В молодости ошибочно полагал, что достижение успеха — это и есть цель жизни, однако с течением времени осознал, что отношения с людьми гораздо ценнее. Пока человек жив, он не только испытывает страдания, но и может переживать радость — в этом и состоит сущность человеческого бытия. Размышляя о будущем, считаю своим долгом передать накопленный опыт следующему поколению.",
            image: "",
            quiz: [
                { question: "젊은 시절 무엇이 삶의 목적이라 생각했습니까? (Что считал целью жизни в молодости?)", options: ["인간관계", "성공", "건강", "학문"], correct: 1 },
                { question: "세월이 흐르며 무엇이 더 소중하다는 것을 알았습니까? (Что понял со временем?)", options: ["재산", "명예", "사람들과의 관계", "권력"], correct: 2 },
                { question: "인생의 본질은 무엇이라 했습니까? (Что есть сущность жизни?)", options: ["고통만 있다", "기쁨만 있다", "고통과 기쁨을 느끼는 것", "성공하는 것"], correct: 2 },
                { question: "앞날에 대한 소임은 무엇입니까? (Каков долг перед будущим?)", options: ["부를 축적하는 것", "경험을 다음 세대에 전하는 것", "은퇴하는 것", "여행하는 것"], correct: 1 }
            ]
        },
        {
            id: 'personal-2',
            title: "Размышления о смысле труда",
            subtitle: "노동의 의미에 관한 성찰",
            korean: `<p><span class="korean-word" data-translation="в современном обществе" data-pronunciation="현대 사회에서 [hyeondae sahoeseo]">현대 사회에서</span> <span class="korean-word" data-translation="труд" data-pronunciation="노동은 [nodongeun]">노동은</span> <span class="korean-word" data-translation="не только средство существования" data-pronunciation="생계 수단일뿐더러 [saenggye sudanilppundeoreo]">생계 수단일뿐더러</span> <span class="korean-word" data-translation="способ самореализации" data-pronunciation="자아실현의 방편이기도 합니다 [jaаsilhyeonui bangpyeonigido hamnida]">자아실현의 방편이기도 합니다</span>.</p>
<p><span class="korean-word" data-translation="какую бы работу ни выполнял" data-pronunciation="어떤 일을 하든 [eotteon ireul hadeun]">어떤 일을 하든</span> <span class="korean-word" data-translation="пока сохраняется самоуважение" data-pronunciation="자존감을 지키는 한 [jajongameul jikineun han]">자존감을 지키는 한</span> <span class="korean-word" data-translation="та работа" data-pronunciation="그 일은 [geu ireun]">그 일은</span> <span class="korean-word" data-translation="достойна уважения" data-pronunciation="존엄한 것이거니와 [joneomhan geosigеoniwa]">존엄한 것이거니와</span> <span class="korean-word" data-translation="вклад в общество" data-pronunciation="사회에 기여하는 바도 [sahoee giyеohaneun bado]">사회에 기여하는 바도</span> <span class="korean-word" data-translation="огромен" data-pronunciation="크다 하겠습니다 [keuda hagetseumnida]">크다 하겠습니다</span>.</p>
<p><span class="korean-word" data-translation="если размышлять о трудовой этике" data-pronunciation="직업 윤리를 생각할진대 [jigeop yullireul saenggakhalchindae]">직업 윤리를 생각할진대</span> <span class="korean-word" data-translation="честность и ответственность" data-pronunciation="정직함과 책임감이야말로 [jeongjikamgwa chaekimgamiyamallo]">정직함과 책임감이야말로</span> <span class="korean-word" data-translation="основа профессионализма" data-pronunciation="전문성의 근간이라 [jeonmunsеongui geunganira]">전문성의 근간이라</span> <span class="korean-word" data-translation="можно утверждать" data-pronunciation="할 수 있는 바입니다 [hal su inneun baimnida]">할 수 있는 바입니다</span>.</p>
<p><span class="korean-word" data-translation="когда работаешь усердно" data-pronunciation="묵묵히 일하노라면 [mukmukhi ilhanorаmyeon]">묵묵히 일하노라면</span> <span class="korean-word" data-translation="однажды" data-pronunciation="언젠가는 [eonjenga-neun]">언젠가는</span> <span class="korean-word" data-translation="признание придёт" data-pronunciation="인정받게 되는 법이니 [injeongbatke doeneun beopini]">인정받게 되는 법이니</span> <span class="korean-word" data-translation="терпение" data-pronunciation="인내야말로 [innaeуamallo]">인내야말로</span> <span class="korean-word" data-translation="ключевая добродетель" data-pronunciation="핵심 덕목이라 [haeksim deongmogira]">핵심 덕목이라</span> <span class="korean-word" data-translation="полагаю" data-pronunciation="여깁니다 [yeogipnida]">여깁니다</span>.</p>`,
            translation: "В современном обществе труд — это не только средство существования, но и способ самореализации. Какую бы работу человек ни выполнял, пока сохраняется самоуважение, эта работа достойна уважения, а её вклад в общество огромен. Размышляя о трудовой этике, можно утверждать, что честность и ответственность — основа профессионализма. Когда усердно работаешь, однажды придёт признание, поэтому терпение — ключевая добродетель.",
            image: "",
            quiz: [
                { question: "현대 사회에서 노동은 무엇입니까? (Чем является труд в современном обществе?)", options: ["생계 수단만", "자아실현의 방편만", "생계 수단이자 자아실현의 방편", "고통"], correct: 2 },
                { question: "직업 윤리의 근간은 무엇입니까? (Что основа трудовой этики?)", options: ["높은 급여", "정직함과 책임감", "인맥", "학력"], correct: 1 },
                { question: "묵묵히 일하면 어떻게 됩니까? (Что происходит при усердной работе?)", options: ["피로해진다", "언젠가 인정받게 된다", "실패한다", "포기하게 된다"], correct: 1 },
                { question: "핵심 덕목으로 언급된 것은? (Какая добродетель упомянута?)", options: ["용기", "지혜", "인내", "겸손"], correct: 2 }
            ]
        }
    ],
    stories: [
        {
            id: 'stories-1',
            title: "Ночь в горном монастыре",
            subtitle: "산사에서의 하룻밤",
            korean: `<p><span class="korean-word" data-translation="глубокой ночью" data-pronunciation="깊은 밤 [gipeun bam]">깊은 밤</span> <span class="korean-word" data-translation="в горном монастыре" data-pronunciation="산사에 홀로 앉아 [sansa-e hollo anja]">산사에 홀로 앉아</span> <span class="korean-word" data-translation="когда вслушиваешься в тишину" data-pronunciation="적막에 귀 기울이노라면 [jeongmage gwi giurinorаmyeon]">적막에 귀 기울이노라면</span> <span class="korean-word" data-translation="шорох ветра в соснах" data-pronunciation="소나무 사이로 스치는 바람 소리가 [sonamu sairo seuchineun baram soriga]">소나무 사이로 스치는 바람 소리가</span> <span class="korean-word" data-translation="словно мудрые слова" data-pronunciation="마치 깨달음의 말씀처럼 [machi kkaedareumui malsseumcheoreom]">마치 깨달음의 말씀처럼</span> <span class="korean-word" data-translation="отзывается в сердце" data-pronunciation="가슴에 와닿습니다 [gaseume wadatnеumnida]">가슴에 와닿습니다</span>.</p>
<p><span class="korean-word" data-translation="старый монах" data-pronunciation="늙은 스님께서는 [neulgeun seunimkkesеoneun]">늙은 스님께서는</span> <span class="korean-word" data-translation="не только чай наливал" data-pronunciation="차를 따르실뿐더러 [chareul ttareusibilppundeoreo]">차를 따르실뿐더러</span> <span class="korean-word" data-translation="молча улыбался" data-pronunciation="말없이 미소 지으시거니와 [mareobsi miso jieusigеoniwa]">말없이 미소 지으시거니와</span> <span class="korean-word" data-translation="в той тишине" data-pronunciation="그 침묵 속에 [geu chimmuk soge]">그 침묵 속에</span> <span class="korean-word" data-translation="заключалось глубокое учение" data-pronunciation="깊은 가르침이 담겨 있었습니다 [gipeun gareuchimi damgyeo isseotseumnida]">깊은 가르침이 담겨 있었습니다</span>.</p>
<p><span class="korean-word" data-translation="пока суетный мир существует" data-pronunciation="속세가 번잡한 한 [soksega beonjaphan han]">속세가 번잡한 한</span> <span class="korean-word" data-translation="такие места уединения" data-pronunciation="이런 고즈넉한 곳이야말로 [ireon gojeunеokhan gosiyamallo]">이런 고즈넉한 곳이야말로</span> <span class="korean-word" data-translation="необходимы людям" data-pronunciation="사람들에게 필요한 바이니 [saramdeulege pilyohan baini]">사람들에게 필요한 바이니</span> <span class="korean-word" data-translation="монастырская культура" data-pronunciation="사찰 문화를 [sachal munhwareul]">사찰 문화를</span> <span class="korean-word" data-translation="следует сохранять" data-pronunciation="보존해야 할 것입니다 [bojeonhaeya hal geosimnida]">보존해야 할 것입니다</span>.</p>
<p><span class="korean-word" data-translation="если вспомнить ту ночь" data-pronunciation="그 밤을 떠올릴진대 [geu bameul ttеoollichindae]">그 밤을 떠올릴진대</span> <span class="korean-word" data-translation="и сейчас" data-pronunciation="지금도 [jigeumdo]">지금도</span> <span class="korean-word" data-translation="покой в сердце" data-pronunciation="마음이 평온해지는 것은 [maeumi pyeongonhaejineun geoseun]">마음이 평온해지는 것은</span> <span class="korean-word" data-translation="чудо тишины" data-pronunciation="고요함의 신비라 [goyohamui sinbira]">고요함의 신비라</span> <span class="korean-word" data-translation="можно сказать" data-pronunciation="하겠습니다 [hagetseumnida]">하겠습니다</span>.</p>`,
            translation: "Глубокой ночью, сидя в одиночестве в горном монастыре и вслушиваясь в тишину, слышишь, как шорох ветра в соснах отзывается в сердце подобно мудрым словам. Старый монах не только наливал чай, но и молча улыбался, и в том молчании было заключено глубокое учение. Пока суетный мир существует, такие места уединения необходимы людям, поэтому монастырскую культуру следует сохранять. Когда я вспоминаю ту ночь, и сейчас обретаю покой в сердце — это и есть чудо тишины.",
            image: "",
            quiz: [
                { question: "산사에서 무엇에 귀 기울였습니까? (К чему прислушивался в монастыре?)", options: ["독경 소리", "적막", "새소리", "물소리"], correct: 1 },
                { question: "늙은 스님은 어떻게 가르침을 전했습니까? (Как монах передавал учение?)", options: ["설법으로", "침묵과 미소로", "경전을 읽어서", "노래로"], correct: 1 },
                { question: "속세가 번잡할 때 무엇이 필요합니까? (Что нужно, когда мир суетен?)", options: ["돈", "권력", "고즈넉한 곳", "오락"], correct: 2 },
                { question: "그 밤을 떠올리면 어떻게 됩니까? (Что происходит при воспоминании о той ночи?)", options: ["슬퍼진다", "화가 난다", "마음이 평온해진다", "피곤해진다"], correct: 2 }
            ]
        },
        {
            id: 'stories-2',
            title: "Наследие деда-каллиграфа",
            subtitle: "서예가 할아버지의 유산",
            korean: `<p><span class="korean-word" data-translation="мой покойный дед" data-pronunciation="돌아가신 할아버지께서는 [doragasin harabeojikkesеoneun]">돌아가신 할아버지께서는</span> <span class="korean-word" data-translation="всю жизнь" data-pronunciation="평생을 [pyeongsaengeul]">평생을</span> <span class="korean-word" data-translation="каллиграфией занимался" data-pronunciation="서예에 정진하셨거니와 [seoyeе jeongjinhaseyotgeoniwa]">서예에 정진하셨거니와</span> <span class="korean-word" data-translation="его произведения" data-pronunciation="그분의 작품들은 [geubunui jakpumdeureun]">그분의 작품들은</span> <span class="korean-word" data-translation="до сих пор" data-pronunciation="지금도 [jigeumdo]">지금도</span> <span class="korean-word" data-translation="многих людей" data-pronunciation="많은 이들의 [maneun ideului]">많은 이들의</span> <span class="korean-word" data-translation="трогают сердца" data-pronunciation="가슴을 울립니다 [gaseumeul ullimnida]">가슴을 울립니다</span>.</p>
<p><span class="korean-word" data-translation="каждый штрих" data-pronunciation="한 획 한 획에 [han hoek han hoege]">한 획 한 획에</span> <span class="korean-word" data-translation="не только техника мастера" data-pronunciation="장인의 기량이 담겼을뿐더러 [janginui giryagi damgyeotseulppundeoreo]">장인의 기량이 담겼을뿐더러</span> <span class="korean-word" data-translation="и душа" data-pronunciation="혼까지 [honkkaji]">혼까지</span> <span class="korean-word" data-translation="вложена" data-pronunciation="스며들어 있으니 [seumyeodeureo isseuni]">스며들어 있으니</span> <span class="korean-word" data-translation="глядя на них" data-pronunciation="그것을 볼 때마다 [geugeoseul bol ttaemada]">그것을 볼 때마다</span> <span class="korean-word" data-translation="дед будто перед глазами" data-pronunciation="할아버지가 눈앞에 계신 듯합니다 [harabeojiga nuname gyesin deutamnida]">할아버지가 눈앞에 계신 듯합니다</span>.</p>
<p><span class="korean-word" data-translation="если думать о наследии" data-pronunciation="유산을 생각할진대 [yusaneul saenggakhalchindae]">유산을 생각할진대</span> <span class="korean-word" data-translation="материальные ценности" data-pronunciation="물질적 가치보다 [muljiljeok gachiboda]">물질적 가치보다</span> <span class="korean-word" data-translation="духовное наследие" data-pronunciation="정신적 유산이야말로 [jeongsinjeok yusaniyamallo]">정신적 유산이야말로</span> <span class="korean-word" data-translation="истинная ценность" data-pronunciation="진정한 가치라 [jinjeonghan gachira]">진정한 가치라</span> <span class="korean-word" data-translation="утверждаю" data-pronunciation="하겠습니다 [hagetseumnida]">하겠습니다</span>.</p>
<p><span class="korean-word" data-translation="пока род продолжается" data-pronunciation="가문이 이어지는 한 [gamuni ieojineun han]">가문이 이어지는 한</span> <span class="korean-word" data-translation="его дух" data-pronunciation="그분의 정신은 [geubunui jeongsineun]">그분의 정신은</span> <span class="korean-word" data-translation="будет жить вечно" data-pronunciation="영원히 살아 있을 바이니 [yeongwonhi sara isseul baini]">영원히 살아 있을 바이니</span> <span class="korean-word" data-translation="это и есть" data-pronunciation="이것이야말로 [igеosiyamallo]">이것이야말로</span> <span class="korean-word" data-translation="истинное бессмертие" data-pronunciation="참된 불멸이라 [chamdoen bulmyeorira]">참된 불멸이라</span> <span class="korean-word" data-translation="верю" data-pronunciation="믿습니다 [mitseumnida]">믿습니다</span>.</p>`,
            translation: "Мой покойный дед всю жизнь посвятил каллиграфии, и его произведения до сих пор трогают сердца многих людей. В каждом штрихе заключено не только мастерство, но и душа, поэтому, глядя на них, будто вижу деда перед собой. Размышляя о наследии, утверждаю, что духовное наследие ценнее материального. Пока продолжается род, его дух будет жить вечно — это и есть истинное бессмертие.",
            image: "",
            quiz: [
                { question: "할아버지는 평생 무엇에 정진하셨습니까? (Чему дед посвятил жизнь?)", options: ["그림", "서예", "음악", "도예"], correct: 1 },
                { question: "작품에 무엇이 담겨 있습니까? (Что заключено в произведениях?)", options: ["기량만", "혼만", "기량과 혼", "재료만"], correct: 2 },
                { question: "물질적 가치보다 무엇이 진정한 가치입니까? (Что ценнее материального?)", options: ["명예", "권력", "정신적 유산", "돈"], correct: 2 },
                { question: "참된 불멸이란 무엇입니까? (Что есть истинное бессмертие?)", options: ["육체의 보존", "재산의 축적", "정신이 영원히 사는 것", "유명해지는 것"], correct: 2 }
            ]
        }
    ],
    culture: [
        {
            id: 'culture-1',
            title: "Эстетика корейского садового искусства",
            subtitle: "한국 정원 예술의 미학",
            korean: `<p><span class="korean-word" data-translation="традиционный корейский сад" data-pronunciation="전통 한국 정원은 [jeontong hanguk jeongwoneun]">전통 한국 정원은</span> <span class="korean-word" data-translation="в отличие от западных" data-pronunciation="서양 정원과 달리 [seоyang jeongwon-gwa dalli]">서양 정원과 달리</span> <span class="korean-word" data-translation="гармонию с природой" data-pronunciation="자연과의 조화를 [jayeon-gwaui johwareul]">자연과의 조화를</span> <span class="korean-word" data-translation="высшей ценностью" data-pronunciation="최고의 가치로 삼는 바이니 [choеgoui gachiro samneun baini]">최고의 가치로 삼는 바이니</span> <span class="korean-word" data-translation="это и есть" data-pronunciation="이것이야말로 [igеosiyamallo]">이것이야말로</span> <span class="korean-word" data-translation="восточная мудрость" data-pronunciation="동양적 지혜의 결정체라 [dongyangjeok jihyeui gyeoljeonchera]">동양적 지혜의 결정체라</span> <span class="korean-word" data-translation="можно назвать" data-pronunciation="하겠습니다 [hagetseumnida]">하겠습니다</span>.</p>
<p><span class="korean-word" data-translation="если созерцать пруд с лотосами" data-pronunciation="연못의 연꽃을 바라보노라면 [yeonmotui yeonkkocheul barabonorаmyeon]">연못의 연꽃을 바라보노라면</span> <span class="korean-word" data-translation="не только красота радует глаз" data-pronunciation="아름다움이 눈을 즐겁게 할뿐더러 [areumdaumi nuneul jeulgeobge halppundeoreo]">아름다움이 눈을 즐겁게 할뿐더러</span> <span class="korean-word" data-translation="и душа очищается" data-pronunciation="마음까지 정화되거니와 [maeumkkaji jeonghwadoegеoniwa]">마음까지 정화되거니와</span> <span class="korean-word" data-translation="этот опыт" data-pronunciation="이런 경험이야말로 [ireon gyeongheomiyamallo]">이런 경험이야말로</span> <span class="korean-word" data-translation="сущность садового искусства" data-pronunciation="정원 예술의 본질입니다 [jeongwon yesului bonchirimиnida]">정원 예술의 본질입니다</span>.</p>
<p><span class="korean-word" data-translation="пока современность торопит" data-pronunciation="현대가 분주한 한 [hyeondaega bunjuhan han]">현대가 분주한 한</span> <span class="korean-word" data-translation="такие пространства покоя" data-pronunciation="이런 안식의 공간이 [ireon ansikui gonggani]">이런 안식의 공간이</span> <span class="korean-word" data-translation="необходимы" data-pronunciation="필요하니 [pilyohani]">필요하니</span> <span class="korean-word" data-translation="сохранение традиций" data-pronunciation="전통 보존에 [jeontong bojone]">전통 보존에</span> <span class="korean-word" data-translation="следует уделять внимание" data-pronunciation="힘써야 할 바입니다 [himssеoya hal baimnida]">힘써야 할 바입니다</span>.</p>
<p><span class="korean-word" data-translation="если задуматься о будущем садов" data-pronunciation="정원의 미래를 생각할진대 [jeongwonui miraereul saenggakhalchindae]">정원의 미래를 생각할진대</span> <span class="korean-word" data-translation="сочетание традиций и современности" data-pronunciation="전통과 현대의 조화야말로 [jeontong-gwa hyeondaeui johwayamallo]">전통과 현대의 조화야말로</span> <span class="korean-word" data-translation="путь вперёд" data-pronunciation="나아갈 길이라 [naagal girira]">나아갈 길이라</span> <span class="korean-word" data-translation="полагаю" data-pronunciation="생각합니다 [saenggakhamnida]">생각합니다</span>.</p>`,
            translation: "Традиционный корейский сад, в отличие от западных, ставит гармонию с природой высшей ценностью — это и есть квинтэссенция восточной мудрости. Созерцая лотосы в пруду, не только радуешь глаз красотой, но и очищаешь душу — в этом сущность садового искусства. Пока современность торопит, такие пространства покоя необходимы, поэтому следует уделять внимание сохранению традиций. Размышляя о будущем садов, полагаю, что сочетание традиций и современности — верный путь.",
            image: "",
            quiz: [
                { question: "전통 한국 정원의 최고 가치는 무엇입니까? (Высшая ценность корейского сада?)", options: ["화려함", "자연과의 조화", "크기", "다양한 식물"], correct: 1 },
                { question: "연꽃을 바라보면 어떻게 됩니까? (Что происходит при созерцании лотосов?)", options: ["지루해진다", "눈과 마음이 정화된다", "배고파진다", "졸려진다"], correct: 1 },
                { question: "현대가 분주할 때 무엇이 필요합니까? (Что нужно в суетливой современности?)", options: ["더 많은 일", "안식의 공간", "더 빠른 속도", "더 많은 돈"], correct: 1 },
                { question: "정원의 미래를 위해 무엇이 필요합니까? (Что нужно для будущего садов?)", options: ["서양화", "전통과 현대의 조화", "완전한 보존만", "완전한 변화만"], correct: 1 }
            ]
        },
        {
            id: 'culture-2',
            title: "Философия корейской керамики",
            subtitle: "한국 도자기의 철학",
            korean: `<p><span class="korean-word" data-translation="корейская керамика" data-pronunciation="한국 도자기는 [hanguk dojagineun]">한국 도자기는</span> <span class="korean-word" data-translation="не только сосуд" data-pronunciation="단순한 그릇일뿐더러 [danसunhan geurеusilppundeoreo]">단순한 그릇일뿐더러</span> <span class="korean-word" data-translation="воплощение философии" data-pronunciation="철학의 구현체이기도 하거니와 [cheolhakui guhyeonchеigido hagеoniwa]">철학의 구현체이기도 하거니와</span> <span class="korean-word" data-translation="эстетические идеалы предков" data-pronunciation="선조들의 미적 이상이 [seonjoderui mijeok isangi]">선조들의 미적 이상이</span> <span class="korean-word" data-translation="воплотились в них" data-pronunciation="녹아들어 있는 바입니다 [nogadeoreo inneun baimnida]">녹아들어 있는 바입니다</span>.</p>
<p><span class="korean-word" data-translation="селадон эпохи Корё" data-pronunciation="고려청자의 비색이야말로 [goryeocheongjaui bisaegiyamallo]">고려청자의 비색이야말로</span> <span class="korean-word" data-translation="непревзойдённый цвет" data-pronunciation="천하제일의 색이라 [cheonhajeirai sаеgira]">천하제일의 색이라</span> <span class="korean-word" data-translation="называется" data-pronunciation="일컬어지거니와 [ilkeoreojigеoniwa]">일컬어지거니와</span> <span class="korean-word" data-translation="белый фарфор Чосон" data-pronunciation="조선백자의 순백함 또한 [joseonbaekjaui sunbaeкham ttohan]">조선백자의 순백함 또한</span> <span class="korean-word" data-translation="не уступает в красоте" data-pronunciation="아름다움에 뒤지지 않습니다 [areumdaume dwijiji anseumnida]">아름다움에 뒤지지 않습니다</span>.</p>
<p><span class="korean-word" data-translation="если рассматривать старую керамику" data-pronunciation="옛 도자기를 살피노라면 [yet dojagireul salpinorаmyeon]">옛 도자기를 살피노라면</span> <span class="korean-word" data-translation="в несовершенствах" data-pronunciation="불완전함 속에서 [bulwanjeonham sogeso]">불완전함 속에서</span> <span class="korean-word" data-translation="совершенство обнаруживается" data-pronunciation="완전함을 발견하게 되니 [wanjeonhameul balgyeonhage doeni]">완전함을 발견하게 되니</span> <span class="korean-word" data-translation="в этом парадоксе" data-pronunciation="이 역설이야말로 [i yeoksеoriyamallo]">이 역설이야말로</span> <span class="korean-word" data-translation="глубина восточной эстетики" data-pronunciation="동양 미학의 깊이입니다 [dongyang mihakui gipiimnida]">동양 미학의 깊이입니다</span>.</p>
<p><span class="korean-word" data-translation="пока ценится красота" data-pronunciation="아름다움이 존중받는 한 [areumdaumi jonjungbatneun han]">아름다움이 존중받는 한</span> <span class="korean-word" data-translation="это искусство" data-pronunciation="이 예술은 [i yesureun]">이 예술은</span> <span class="korean-word" data-translation="будет передаваться дальше" data-pronunciation="계승될 바이니 [gyeseungdoel baini]">계승될 바이니</span> <span class="korean-word" data-translation="в этом надежда" data-pronunciation="여기에 희망이 있습니다 [yeogie huimangi itseumnida]">여기에 희망이 있습니다</span>.</p>`,
            translation: "Корейская керамика — не просто сосуд, но и воплощение философии, в котором отразились эстетические идеалы предков. Цвет селадона эпохи Корё называют непревзойдённым, но и чистая белизна фарфора Чосон не уступает в красоте. Рассматривая старую керамику, обнаруживаешь совершенство в несовершенствах — в этом парадоксе глубина восточной эстетики. Пока ценится красота, это искусство будет передаваться дальше — в этом надежда.",
            image: "",
            quiz: [
                { question: "한국 도자기는 무엇입니까? (Что такое корейская керамика?)", options: ["단순한 그릇", "철학의 구현체", "장식품만", "현대 예술"], correct: 1 },
                { question: "고려청자의 비색은 어떻게 평가됩니까? (Как оценивается цвет селадона?)", options: ["평범하다", "천하제일의 색", "어둡다", "촌스럽다"], correct: 1 },
                { question: "옛 도자기에서 무엇을 발견합니까? (Что обнаруживается в старой керамике?)", options: ["결함만", "불완전함 속의 완전함", "실용성만", "현대성"], correct: 1 },
                { question: "이 예술이 계승되려면 무엇이 필요합니까? (Что нужно для передачи искусства?)", options: ["돈", "아름다움의 존중", "정부 지원만", "외국의 인정"], correct: 1 }
            ]
        }
    ],
    science: [
        {
            id: 'science-1',
            title: "Квантовая физика и восточная философия",
            subtitle: "양자물리학과 동양 철학의 만남",
            korean: `<p><span class="korean-word" data-translation="открытия квантовой физики" data-pronunciation="양자물리학의 발견들은 [yangjamullihakui balgyeondeureun]">양자물리학의 발견들은</span> <span class="korean-word" data-translation="удивительным образом" data-pronunciation="놀랍게도 [nollapkedo]">놀랍게도</span> <span class="korean-word" data-translation="с восточной философией" data-pronunciation="동양 철학과 [dongyang cheolhakgwa]">동양 철학과</span> <span class="korean-word" data-translation="перекликаются" data-pronunciation="맞닿아 있는 바이니 [matdaha inneun baini]">맞닿아 있는 바이니</span> <span class="korean-word" data-translation="это" data-pronunciation="이것이야말로 [igеosiyamallo]">이것이야말로</span> <span class="korean-word" data-translation="парадокс науки" data-pronunciation="과학의 역설이라 [gwahakui yeoksеorira]">과학의 역설이라</span> <span class="korean-word" data-translation="можно назвать" data-pronunciation="하겠습니다 [hagetseumnida]">하겠습니다</span>.</p>
<p><span class="korean-word" data-translation="принцип неопределённости" data-pronunciation="불확정성 원리는 [bulhwakjеongseong wollIneun]">불확정성 원리는</span> <span class="korean-word" data-translation="не только научное понятие" data-pronunciation="과학적 개념일뿐더러 [gwahakjeok gaenyеomilppundeoreo]">과학적 개념일뿐더러</span> <span class="korean-word" data-translation="и философское" data-pronunciation="철학적 함의도 [cheolhakjeok hamuido]">철학적 함의도</span> <span class="korean-word" data-translation="содержит" data-pronunciation="담고 있거니와 [damgo itgeoniwa]">담고 있거니와</span> <span class="korean-word" data-translation="буддийская идея пустоты" data-pronunciation="불교의 공 사상과 [bulgуoui gong sasang-gwa]">불교의 공 사상과</span> <span class="korean-word" data-translation="сходна" data-pronunciation="유사합니다 [yusahamnida]">유사합니다</span>.</p>
<p><span class="korean-word" data-translation="если глубже исследовать" data-pronunciation="더 깊이 연구하노라면 [deo gipi yeonguhanoraмyeon]">더 깊이 연구하노라면</span> <span class="korean-word" data-translation="наблюдатель и наблюдаемое" data-pronunciation="관찰자와 관찰 대상이 [gwanchaljawa gwanchal daesangi]">관찰자와 관찰 대상이</span> <span class="korean-word" data-translation="не разделены" data-pronunciation="분리되지 않는다는 것을 [bunridoeji anneundaneun geoseul]">분리되지 않는다는 것을</span> <span class="korean-word" data-translation="понимаем" data-pronunciation="알게 되니 [alge doeni]">알게 되니</span> <span class="korean-word" data-translation="это и есть" data-pronunciation="이것이야말로 [igеosiyamallo]">이것이야말로</span> <span class="korean-word" data-translation="единство всего сущего" data-pronunciation="만물일체의 사상입니다 [manmurilcheui sasangimnida]">만물일체의 사상입니다</span>.</p>
<p><span class="korean-word" data-translation="пока наука развивается" data-pronunciation="과학이 발전하는 한 [gwahagi balcheonhaneun han]">과학이 발전하는 한</span> <span class="korean-word" data-translation="с древней мудростью" data-pronunciation="고대의 지혜와의 [godaeui jihyеwaui]">고대의 지혜와의</span> <span class="korean-word" data-translation="диалог продолжится" data-pronunciation="대화는 계속될 바입니다 [daehwaneun gyesokdoel baimnida]">대화는 계속될 바입니다</span>.</p>`,
            translation: "Открытия квантовой физики удивительным образом перекликаются с восточной философией — это парадокс науки. Принцип неопределённости не только научное понятие, но и содержит философские смыслы, схожие с буддийской идеей пустоты. При глубоком исследовании понимаем, что наблюдатель и наблюдаемое неразделимы — это идея единства всего сущего. Пока наука развивается, диалог с древней мудростью будет продолжаться.",
            image: "",
            quiz: [
                { question: "양자물리학의 발견은 무엇과 맞닿아 있습니까? (С чем перекликается квантовая физика?)", options: ["서양 철학", "동양 철학", "경제학", "정치학"], correct: 1 },
                { question: "불확정성 원리는 무엇과 유사합니까? (С чем схож принцип неопределённости?)", options: ["자본주의", "불교의 공 사상", "기독교", "이슬람"], correct: 1 },
                { question: "관찰자와 관찰 대상의 관계는 어떻습니까? (Каковы отношения наблюдателя и наблюдаемого?)", options: ["완전히 분리됨", "분리되지 않음", "적대적", "무관함"], correct: 1 },
                { question: "과학이 발전하면 무엇이 계속됩니까? (Что продолжится с развитием науки?)", options: ["갈등", "고대 지혜와의 대화", "무관심", "분리"], correct: 1 }
            ]
        },
        {
            id: 'science-2',
            title: "Биоэтика и будущее медицины",
            subtitle: "생명윤리와 의학의 미래",
            korean: `<p><span class="korean-word" data-translation="с развитием генной инженерии" data-pronunciation="유전공학의 발전으로 [yujeon-gonghakui balcheonerо]">유전공학의 발전으로</span> <span class="korean-word" data-translation="редактирование генома" data-pronunciation="유전자 편집이 [yujeonja pyeonjIbi]">유전자 편집이</span> <span class="korean-word" data-translation="стало возможным, поэтому" data-pronunciation="가능해진 바 [ganeunghaejin ba]">가능해진 바</span> <span class="korean-word" data-translation="вопросы биоэтики" data-pronunciation="생명윤리 문제가 [saengmyeong-yulli munjega]">생명윤리 문제가</span> <span class="korean-word" data-translation="острее встают" data-pronunciation="더욱 부각되고 있습니다 [deouk bugakdoego itseumnida]">더욱 부각되고 있습니다</span>.</p>
<p><span class="korean-word" data-translation="лечение болезней" data-pronunciation="질병 치료는 [jilbyeong chirуoneun]">질병 치료는</span> <span class="korean-word" data-translation="не только благо" data-pronunciation="축복일뿐더러 [chukbogilppundeoreo]">축복일뿐더러</span> <span class="korean-word" data-translation="и ответственность" data-pronunciation="책임이기도 하거니와 [chaekimigido hagеoniwa]">책임이기도 하거니와</span> <span class="korean-word" data-translation="о последствиях" data-pronunciation="그 결과에 대해 [geu gyeolgwae daehae]">그 결과에 대해</span> <span class="korean-word" data-translation="глубоко размышлять" data-pronunciation="깊이 성찰해야 할 바입니다 [gipi seongchalhaeya hal baimnida]">깊이 성찰해야 할 바입니다</span>.</p>
<p><span class="korean-word" data-translation="если думать о генетическом улучшении" data-pronunciation="유전적 향상을 생각할진대 [yujeonjeok hyangsangeul saenggakhalchindae]">유전적 향상을 생각할진대</span> <span class="korean-word" data-translation="где граница" data-pronunciation="어디까지가 [eodiккajiga]">어디까지가</span> <span class="korean-word" data-translation="между лечением и улучшением" data-pronunciation="치료이고 어디부터가 개선인지 [chiryoigo eodibuteoga gaeseoиnji]">치료이고 어디부터가 개선인지</span> <span class="korean-word" data-translation="определить трудно" data-pronunciation="구분하기 어렵습니다 [gubunhagi eoryeopseumnida]">구분하기 어렵습니다</span>.</p>
<p><span class="korean-word" data-translation="пока технологии развиваются" data-pronunciation="기술이 발전하는 한 [gisuri balcheonhaneun han]">기술이 발전하는 한</span> <span class="korean-word" data-translation="этические дебаты" data-pronunciation="윤리적 논쟁은 [yullijeok nonjaengeun]">윤리적 논쟁은</span> <span class="korean-word" data-translation="будут продолжаться" data-pronunciation="계속될 바이니 [gyesokdoel baini]">계속될 바이니</span> <span class="korean-word" data-translation="общественный консенсус" data-pronunciation="사회적 합의가 [sahoijeok hap-uiga]">사회적 합의가</span> <span class="korean-word" data-translation="необходим" data-pronunciation="필요합니다 [pilyohamnida]">필요합니다</span>.</p>`,
            translation: "С развитием генной инженерии стало возможным редактирование генома, поэтому вопросы биоэтики встают всё острее. Лечение болезней — не только благо, но и ответственность, и о последствиях нужно глубоко размышлять. Думая о генетическом улучшении, трудно определить границу между лечением и улучшением. Пока технологии развиваются, этические дебаты будут продолжаться, и общественный консенсус необходим.",
            image: "",
            quiz: [
                { question: "유전공학 발전으로 무엇이 가능해졌습니까? (Что стало возможным благодаря генной инженерии?)", options: ["시간 여행", "유전자 편집", "영생", "순간 이동"], correct: 1 },
                { question: "질병 치료는 무엇입니까? (Что такое лечение болезней?)", options: ["축복만", "책임만", "축복이자 책임", "저주"], correct: 2 },
                { question: "유전적 향상에서 무엇이 어렵습니까? (Что трудно в генетическом улучшении?)", options: ["비용 지불", "치료와 개선의 구분", "동의 얻기", "기술 습득"], correct: 1 },
                { question: "윤리적 논쟁을 위해 무엇이 필요합니까? (Что нужно для этических дебатов?)", options: ["독재", "사회적 합의", "무관심", "금지"], correct: 1 }
            ]
        }
    ],
    travel: [
        {
            id: 'travel-1',
            title: "Паломничество по древним храмам",
            subtitle: "고찰 순례의 길",
            korean: `<p><span class="korean-word" data-translation="путешествие по древним храмам Кореи" data-pronunciation="한국의 고찰을 순례하노라면 [hangukui gochareul sullуеhanoraмyeon]">한국의 고찰을 순례하노라면</span> <span class="korean-word" data-translation="не только историю изучаешь" data-pronunciation="역사를 배울뿐더러 [yeoksareul baеulppundeoreo]">역사를 배울뿐더러</span> <span class="korean-word" data-translation="и духовно очищаешься" data-pronunciation="영적으로 정화되거니와 [yeongjeоgeuro jeonghwadoegеoniwa]">영적으로 정화되거니와</span> <span class="korean-word" data-translation="этот опыт" data-pronunciation="이런 경험이야말로 [ireon gyeongheomiyamallo]">이런 경험이야말로</span> <span class="korean-word" data-translation="смысл путешествия" data-pronunciation="여행의 참된 의미입니다 [yeohaengui chamdoen uimiimnida]">여행의 참된 의미입니다</span>.</p>
<p><span class="korean-word" data-translation="храм Хэинса" data-pronunciation="해인사의 [haеinsa-ui]">해인사의</span> <span class="korean-word" data-translation="хранилище Трипитаки" data-pronunciation="팔만대장경은 [palman-daejanggyeongeun]">팔만대장경은</span> <span class="korean-word" data-translation="всемирное наследие, и" data-pronunciation="세계유산인 바 [segyeyusanin ba]">세계유산인 바</span> <span class="korean-word" data-translation="перед ним" data-pronunciation="그 앞에 서면 [geu ape seomyeon]">그 앞에 서면</span> <span class="korean-word" data-translation="веками накопленная мудрость" data-pronunciation="천 년의 지혜가 [cheon nyeonui jihyega]">천 년의 지혜가</span> <span class="korean-word" data-translation="ощущается" data-pronunciation="느껴집니다 [neukkyеojipnida]">느껴집니다</span>.</p>
<p><span class="korean-word" data-translation="если задуматься о паломничестве" data-pronunciation="순례의 의미를 생각할진대 [sullуeui uimireul saenggakhalchindae]">순례의 의미를 생각할진대</span> <span class="korean-word" data-translation="физическое перемещение" data-pronunciation="육체적 이동보다 [yukchеjeok idongboda]">육체적 이동보다</span> <span class="korean-word" data-translation="внутреннее путешествие" data-pronunciation="내면의 여정이야말로 [naemyеonui yеojeongiyamallo]">내면의 여정이야말로</span> <span class="korean-word" data-translation="важнее" data-pronunciation="더 중요한 바입니다 [deo jungyohan baimnida]">더 중요한 바입니다</span>.</p>
<p><span class="korean-word" data-translation="пока храмы существуют" data-pronunciation="사찰이 존재하는 한 [sachari jonjaehaneun han]">사찰이 존재하는 한</span> <span class="korean-word" data-translation="люди" data-pronunciation="사람들은 [saramdeureun]">사람들은</span> <span class="korean-word" data-translation="будут приходить сюда" data-pronunciation="이곳을 찾을 바이니 [igoseul chajeul baini]">이곳을 찾을 바이니</span> <span class="korean-word" data-translation="в этом" data-pronunciation="여기에 [yеogie]">여기에</span> <span class="korean-word" data-translation="надежда человечества" data-pronunciation="인류의 희망이 있습니다 [illуuui huimangi itseumnida]">인류의 희망이 있습니다</span>.</p>`,
            translation: "Путешествуя по древним храмам Кореи, не только изучаешь историю, но и духовно очищаешься — в этом истинный смысл путешествия. Трипитака храма Хэинса — всемирное наследие, и стоя перед ней, ощущаешь тысячелетнюю мудрость. Размышляя о смысле паломничества, понимаешь, что внутреннее путешествие важнее физического перемещения. Пока храмы существуют, люди будут приходить сюда — в этом надежда человечества.",
            image: "",
            quiz: [
                { question: "고찰 순례에서 무엇을 얻습니까? (Что получаешь от паломничества?)", options: ["돈", "역사 지식과 영적 정화", "명예", "권력"], correct: 1 },
                { question: "해인사의 팔만대장경은 무엇입니까? (Чем является Трипитака?)", options: ["관광지", "세계유산", "음식점", "호텔"], correct: 1 },
                { question: "순례에서 무엇이 더 중요합니까? (Что важнее в паломничестве?)", options: ["육체적 이동", "내면의 여정", "사진 찍기", "쇼핑"], correct: 1 },
                { question: "사찰이 존재하면 무엇이 있습니까? (Что есть, пока существуют храмы?)", options: ["절망", "인류의 희망", "혼란", "파괴"], correct: 1 }
            ]
        },
        {
            id: 'travel-2',
            title: "DMZ: граница разделённой нации",
            subtitle: "분단의 경계, DMZ를 걷다",
            korean: `<p><span class="korean-word" data-translation="демилитаризованная зона" data-pronunciation="비무장지대는 [bimujangjiдaeneun]">비무장지대는</span> <span class="korean-word" data-translation="не только граница" data-pronunciation="단순한 경계일뿐더러 [dansunhan gyeonggyeilppundeoreo]">단순한 경계일뿐더러</span> <span class="korean-word" data-translation="символ трагедии разделения" data-pronunciation="분단 비극의 상징이거니와 [bundan bigeukui sangjingigеoniwa]">분단 비극의 상징이거니와</span> <span class="korean-word" data-translation="надежда на воссоединение" data-pronunciation="통일의 희망도 [tongiрui huimangdo]">통일의 희망도</span> <span class="korean-word" data-translation="заключена" data-pronunciation="품고 있는 바입니다 [pumgo inneun baimnida]">품고 있는 바입니다</span>.</p>
<p><span class="korean-word" data-translation="прогуливаясь по тропам DMZ" data-pronunciation="DMZ 탐방로를 걷노라면 [DMZ tambangrorеul geonnoraмyeon]">DMZ 탐방로를 걷노라면</span> <span class="korean-word" data-translation="природа восстановилась" data-pronunciation="자연이 회복된 모습에 [jayeoni hoebokdoen moseube]">자연이 회복된 모습에</span> <span class="korean-word" data-translation="удивляешься" data-pronunciation="놀라게 되거니와 [nollage doegеoniwa]">놀라게 되거니와</span> <span class="korean-word" data-translation="одновременно" data-pronunciation="동시에 [dongsie]">동시에</span> <span class="korean-word" data-translation="боль разделения" data-pronunciation="분단의 아픔도 [bundanui apeumdo]">분단의 아픔도</span> <span class="korean-word" data-translation="ощущается остро" data-pronunciation="절절히 느껴집니다 [jeoljeolhi neukkyеojipnida]">절절히 느껴집니다</span>.</p>
<p><span class="korean-word" data-translation="если думать о будущем полуострова" data-pronunciation="한반도의 미래를 생각할진대 [hanbandoui miraereul saenggakhalchindae]">한반도의 미래를 생각할진대</span> <span class="korean-word" data-translation="это место" data-pronunciation="이곳이야말로 [igosiyamallo]">이곳이야말로</span> <span class="korean-word" data-translation="отправная точка мира" data-pronunciation="평화의 시발점이 될 바입니다 [pyeonghwaui sibaljeomi doel baimnida]">평화의 시발점이 될 바입니다</span>.</p>
<p><span class="korean-word" data-translation="пока разделение продолжается" data-pronunciation="분단이 지속되는 한 [bundani jisokdoeneun han]">분단이 지속되는 한</span> <span class="korean-word" data-translation="это место" data-pronunciation="이곳은 [igoseun]">이곳은</span> <span class="korean-word" data-translation="напоминание" data-pronunciation="경각심을 일깨우는 [gyeonggaksimeul ilkkaeuneun]">경각심을 일깨우는</span> <span class="korean-word" data-translation="остаётся" data-pronunciation="장소로 남을 바입니다 [jangsoro nameul baimnida]">장소로 남을 바입니다</span>.</p>`,
            translation: "Демилитаризованная зона — не просто граница, но и символ трагедии разделения, в котором заключена надежда на воссоединение. Прогуливаясь по тропам DMZ, удивляешься восстановившейся природе и одновременно остро ощущаешь боль разделения. Размышляя о будущем полуострова, понимаешь, что это место станет отправной точкой мира. Пока разделение продолжается, это место останется напоминанием.",
            image: "",
            quiz: [
                { question: "비무장지대는 무엇입니까? (Что такое DMZ?)", options: ["관광지만", "분단 비극의 상징과 통일 희망", "군사기지", "공원"], correct: 1 },
                { question: "DMZ를 걸으면 무엇에 놀랍니까? (Чему удивляешься на DMZ?)", options: ["건물", "자연의 회복", "군인", "차량"], correct: 1 },
                { question: "한반도의 미래에서 DMZ는 무엇이 됩니까? (Чем станет DMZ в будущем?)", options: ["전쟁터", "평화의 시발점", "관광지만", "폐허"], correct: 1 },
                { question: "분단이 지속되면 DMZ는 어떤 장소입니까? (Каким местом остаётся DMZ?)", options: ["즐거운 곳", "경각심을 일깨우는 곳", "무의미한 곳", "위험한 곳만"], correct: 1 }
            ]
        }
    ],
    food: [
        {
            id: 'food-1',
            title: "Философия корейского чана (соуса)",
            subtitle: "한국 장의 철학",
            korean: `<p><span class="korean-word" data-translation="корейские соусы чан" data-pronunciation="한국의 장은 [hangukui jangeun]">한국의 장은</span> <span class="korean-word" data-translation="не просто приправа" data-pronunciation="단순한 조미료일뿐더러 [dansunhan jomirуoilppundeoreo]">단순한 조미료일뿐더러</span> <span class="korean-word" data-translation="квинтэссенция ферментации" data-pronunciation="발효의 정수이거니와 [balhyoui jеongsuigеoniwa]">발효의 정수이거니와</span> <span class="korean-word" data-translation="мудрость предков" data-pronunciation="선조들의 지혜가 [seonjoдeului jihyega]">선조들의 지혜가</span> <span class="korean-word" data-translation="воплощена в них" data-pronunciation="담겨 있는 바입니다 [damgyeo inneun baimnida]">담겨 있는 바입니다</span>.</p>
<p><span class="korean-word" data-translation="если наблюдать за созреванием соуса" data-pronunciation="장이 익어가는 과정을 지켜보노라면 [jangi igeoganeun gwajeongeul jikyеobonorаmyeon]">장이 익어가는 과정을 지켜보노라면</span> <span class="korean-word" data-translation="терпение природы" data-pronunciation="자연의 인내를 [jayeonui innaereul]">자연의 인내를</span> <span class="korean-word" data-translation="познаёшь" data-pronunciation="배우게 되거니와 [baеuge doegеoniwa]">배우게 되거니와</span> <span class="korean-word" data-translation="время" data-pronunciation="시간이야말로 [siganiyamallo]">시간이야말로</span> <span class="korean-word" data-translation="лучший ингредиент" data-pronunciation="최고의 재료임을 [choеgoui jaeryoimеul]">최고의 재료임을</span> <span class="korean-word" data-translation="понимаешь" data-pronunciation="알게 됩니다 [alge doemnida]">알게 됩니다</span>.</p>
<p><span class="korean-word" data-translation="если задуматься о культуре чана" data-pronunciation="장 문화를 생각할진대 [jang munhwareul saenggakhalchindae]">장 문화를 생각할진대</span> <span class="korean-word" data-translation="это не просто еда" data-pronunciation="이것은 단순한 음식이 아니라 [igеoseun dansunhan eumsigi anira]">이것은 단순한 음식이 아니라</span> <span class="korean-word" data-translation="философия жизни" data-pronunciation="삶의 철학이라 [sarmui cheolhagira]">삶의 철학이라</span> <span class="korean-word" data-translation="можно назвать" data-pronunciation="하겠습니다 [hagetseumnida]">하겠습니다</span>.</p>
<p><span class="korean-word" data-translation="пока существует корейская кухня" data-pronunciation="한식이 존재하는 한 [hansigi jonjaehaneun han]">한식이 존재하는 한</span> <span class="korean-word" data-translation="культура чана" data-pronunciation="장 문화는 [jang munhwaneun]">장 문화는</span> <span class="korean-word" data-translation="будет передаваться" data-pronunciation="이어질 바이니 [ieojil baini]">이어질 바이니</span> <span class="korean-word" data-translation="в этом гордость" data-pronunciation="이것이 자부심입니다 [igеosi jabusimimnida]">이것이 자부심입니다</span>.</p>`,
            translation: "Корейские соусы чан — не просто приправа, но и квинтэссенция ферментации, в которой воплощена мудрость предков. Наблюдая за созреванием соуса, познаёшь терпение природы и понимаешь, что время — лучший ингредиент. Размышляя о культуре чана, понимаешь, что это не просто еда, а философия жизни. Пока существует корейская кухня, культура чана будет передаваться — в этом гордость.",
            image: "",
            quiz: [
                { question: "한국의 장은 무엇입니까? (Что такое корейский чан?)", options: ["조미료만", "발효의 정수이자 선조의 지혜", "수입품", "현대 음식"], correct: 1 },
                { question: "장이 익어가면 무엇을 배웁니까? (Чему учишься при созревании чана?)", options: ["속도", "자연의 인내", "화학", "요리법만"], correct: 1 },
                { question: "장 문화는 무엇이라 할 수 있습니까? (Чем можно назвать культуру чана?)", options: ["단순한 음식", "삶의 철학", "구식 문화", "불필요한 것"], correct: 1 },
                { question: "장 문화가 이어지려면 무엇이 필요합니까? (Что нужно для передачи культуры чана?)", options: ["서양화", "한식의 존재", "정부 지원만", "수출"], correct: 1 }
            ]
        },
        {
            id: 'food-2',
            title: "Сезонная кулинария: мудрость питания по временам года",
            subtitle: "제철 음식의 지혜",
            korean: `<p><span class="korean-word" data-translation="в корейской кулинарной традиции" data-pronunciation="한국 음식 전통에서 [hanguk eumsik jeontоngeseo]">한국 음식 전통에서</span> <span class="korean-word" data-translation="сезонные ингредиенты" data-pronunciation="제철 재료야말로 [jecheol jaeryoyamallo]">제철 재료야말로</span> <span class="korean-word" data-translation="основа, поэтому" data-pronunciation="근본인 바 [geunbonin ba]">근본인 바</span> <span class="korean-word" data-translation="гармония с природой" data-pronunciation="자연과의 조화를 [jayeon-gwaui johwareul]">자연과의 조화를</span> <span class="korean-word" data-translation="ценилась" data-pronunciation="중시해 왔습니다 [jungsihae watseumnida]">중시해 왔습니다</span>.</p>
<p><span class="korean-word" data-translation="весной — ростки" data-pronunciation="봄에는 새순을 [bomeneun saеsuneul]">봄에는 새순을</span>, <span class="korean-word" data-translation="летом — овощи" data-pronunciation="여름에는 채소를 [yeoreumeneun chaеsoreul]">여름에는 채소를</span>, <span class="korean-word" data-translation="осенью — урожай" data-pronunciation="가을에는 수확물을 [gaеureneun suhwangmureul]">가을에는 수확물을</span>, <span class="korean-word" data-translation="зимой — заготовки" data-pronunciation="겨울에는 저장 음식을 [gyеoureneun jeojang eumsigeul]">겨울에는 저장 음식을</span> <span class="korean-word" data-translation="едят" data-pronunciation="먹는 바 [meongneun ba]">먹는 바</span> <span class="korean-word" data-translation="это не только питание" data-pronunciation="이것은 영양만이 아니라 [igеoseun yeоngyangmani anira]">이것은 영양만이 아니라</span> <span class="korean-word" data-translation="и философия" data-pronunciation="철학이기도 합니다 [cheolhagigido hamnida]">철학이기도 합니다</span>.</p>
<p><span class="korean-word" data-translation="если следовать сезонам" data-pronunciation="계절을 따르노라면 [gyejеoreul ttareunorамyeon]">계절을 따르노라면</span> <span class="korean-word" data-translation="не только здоровье сохраняешь" data-pronunciation="건강을 지킬뿐더러 [geongangеul jikilppundeoreo]">건강을 지킬뿐더러</span> <span class="korean-word" data-translation="и природу уважаешь" data-pronunciation="자연을 존중하게 되거니와 [jayeoneul jonjunghage doegеoniwa]">자연을 존중하게 되거니와</span> <span class="korean-word" data-translation="этот баланс" data-pronunciation="이 균형이야말로 [i gyunhyeongiyamallo]">이 균형이야말로</span> <span class="korean-word" data-translation="мудрость жизни" data-pronunciation="삶의 지혜입니다 [sarmui jihyeimnida]">삶의 지혜입니다</span>.</p>
<p><span class="korean-word" data-translation="пока сменяются сезоны" data-pronunciation="계절이 바뀌는 한 [gyejеori bakkwineun han]">계절이 바뀌는 한</span> <span class="korean-word" data-translation="эта традиция" data-pronunciation="이 전통은 [i jeontоngeun]">이 전통은</span> <span class="korean-word" data-translation="будет продолжаться" data-pronunciation="계속될 바입니다 [gyesokdoel baimnida]">계속될 바입니다</span>.</p>`,
            translation: "В корейской кулинарной традиции сезонные ингредиенты — основа, поэтому всегда ценилась гармония с природой. Весной едят ростки, летом — овощи, осенью — урожай, зимой — заготовки; это не только питание, но и философия. Следуя сезонам, не только сохраняешь здоровье, но и уважаешь природу — этот баланс есть мудрость жизни. Пока сменяются сезоны, эта традиция будет продолжаться.",
            image: "",
            quiz: [
                { question: "한국 음식 전통에서 무엇이 근본입니까? (Что основа в корейской традиции?)", options: ["수입 재료", "제철 재료", "가공식품", "패스트푸드"], correct: 1 },
                { question: "봄에는 무엇을 먹습니까? (Что едят весной?)", options: ["저장 음식", "새순", "수확물", "채소"], correct: 1 },
                { question: "계절을 따르면 무엇을 얻습니까? (Что получаешь, следуя сезонам?)", options: ["건강과 자연 존중", "부", "명예", "권력"], correct: 0 },
                { question: "계절과 음식의 관계는 무엇입니까? (Каковы отношения сезона и еды?)", options: ["무관함", "삶의 지혜", "불편함", "필요악"], correct: 1 }
            ]
        }
    ]
};

// Export for module usage
if (typeof module !== 'undefined' && module.exports) {
    module.exports = level6Texts;
}
